### ISSUE TITLE
BUG report--string template error

### ISSUE THREAD

**Issue by xioajiumi** [00-Evan/shattered-pixel-dungeon#1501] opened 2023-09-20 13:21 UTC
Hi Evan, I might find a **bug** while playing SPD, and as a coder I consider the bug may due to the **string message template replacement**.
The wrong green msg is in Chinese, and it means **"you are familiar with your ring and thus identify it. It is %s"**
More info: version-V2.2.0-8ETA-0.5 from Google Play, Android
![812f8e7f4837df60db106514519e3e2](https://github.com/00-Evan/shattered-pixel-dungeon/assets/62926886/1019a8d8-b6e9-4eb7-97cd-349fc97e8335)

**Comment by 00-Evan** [comment] 2023-09-20 13:58
Duplicate of #1497

**Closed by 00-Evan** 2023-09-20 13:58 UTC
