### ISSUE TITLE
"!!!NO TEXT FOUND!!!" when reading scroll of mystical energy

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#531] opened 2020-11-10 08:41 UTC
I got the message "!!!NO TEXT FOUND!!!" when I made and read a scroll of mystical energy. In case it matters, I had the Horn of Plenty and the Talisman of Foresight equipped.

Can provide a screenshot if that description isn't sufficient for debugging.

**Comment by 00-Evan** [comment] 2020-11-10 16:03
Looks like this is caused by the talisman, will fix in v0.9.1

**Comment by 00-Evan** [comment] 2020-12-11 21:52
fixed in commit 09c714db84b1f74bb0fbef255a649c56dfc9e5cf

**Closed by 00-Evan** 2020-12-11 21:52 UTC
Labels: Fixed Indev, Quirk
