### ISSUE TITLE
All pre-2.0.0 ranking entries are broken after the update

### ISSUE THREAD

**Issue by gnollwieldinghalberd** [00-Evan/shattered-pixel-dungeon#1378] opened 2023-05-26 08:54 UTC
![Screenshot_20230526_175143](https://github.com/00-Evan/shattered-pixel-dungeon/assets/123718935/d45a5592-905b-4879-91cf-6b6476d103f1)

All of pre-2.0.0 ranking entries are broken, only score is left.

**Comment by 00-Evan** [comment] 2023-05-26 18:23
This occurs when the game is unable to load game data from prioer rankings, which can happen for a number of reasons. Unfortunately there's nothing I can really do just from this error message alone.

**Comment by gnollwieldinghalberd** [comment] 2023-05-26 19:01
Is there anything I can do to provide more information for solving this issue?

**Comment by 00-Evan** [comment] 2023-05-28 21:44
Which type of device are you using (android phone, iphone, etc.) and are you playing on v2.0.2 or on the latest v2.1.0 beta?

Unfortunately aside from that there is no other information to give, as the rankings data cannot be displayed. If there was some error while loading it (and it isn't simply gone) then I should get an automated report about it.

**Comment by gnollwieldinghalberd** [comment] 2023-05-29 02:08
I'm using android and this happened since 2.0.2.

**Comment by 00-Evan** [comment] 2023-05-29 02:43
I did make some changes to rankings managment in v2.0.2, to make these sorts of error screens a bit more useful (still showing your score), and changing rankings conversion behaviour to show errors like this instead of fsimply silently daleting rankings entries. This shouldn't genereate any new rankings errors, but I have also gotten more reports since v2.0.2 relesaed. I'll look into this again to try and be sure that there are no new errors being introduced.

**Comment by 00-Evan** [comment] 2023-06-04 19:16
Closing this for now as I cannot reproduce this issue, and have re-inspected the code change and can't find any reason why this change would result in more errors that previously. My best bet is that your rankings would have simply disappeared were it not for this change. If you or someone else encounters this again or has any more evidence please comment and I'll be happy to look into this again.

**Closed by 00-Evan** 2023-06-04 19:16 UTC
