### ISSUE TITLE
After using an Ankh, the wand of the mage doesn't recharge

### ISSUE THREAD

**Issue by Ezelty** [00-Evan/shattered-pixel-dungeon#55] opened 2015-07-20 19:25 UTC
I've played several games with the mage, and every time I used an Ankh, the wand of the mage stopped recharging. It didn't recharge neither with time, nor by eating. I had the buff "recharging", but nothing happened.
However, when I imbued the wand after using the Ankh, after a few turns the wand started to recharge normally. (perhaps it does the same if you upgrade your wand, but I don't remember if I tried)

It might be a normal feature, but it seems to me that it is a bug. Playing a mage without his wand is really hard...

I play with Shattered Pixel Dungeon v0.3.0e.

**Comment by 00-Evan** [comment] 2015-07-21 14:30
This is a bug which I had made a fix for in 0.3.0a, will attempt to reproduce again and come up with a fix.

**Comment by 00-Evan** [comment] 2015-07-24 19:18
It looks like the mages staff and wands aren't correctly charging themselves if an ankh revives the hero and they are in the inventory, but not equipped.

Will correct this for 0.3.1

**Comment by Ezelty** [comment] 2015-07-25 19:00
Thank you!

**Comment by 00-Evan** [comment] 2015-08-10 01:13
This issue has been addressed in the latest beta.

You can opt in to receive betas from google play here: https://play.google.com/apps/testing/com.shatteredpixel.shatteredpixeldungeon

Once the source is released this ticket will be closed with the commit referenced.

**Comment by Ezelty** [comment] 2015-08-13 17:54
Great! Thank you!
I would have loved to try the beta but I can't as I don't use google play. Why not releasing the source of the beta so that f-droid users can try it too ?

**Comment by 00-Evan** [comment] 2015-08-13 18:42
Unfortunately the betas are not built from the open-source, but rather from the private source of that update (source is released after each update). F-droid must be built from open-source so that won't quite work. You'll be able to get this stuff fairly soon, as 0.3.1 is almost done and the source will be released a few days after that (unless there are any immediate issues that need patching)

**Comment by 00-Evan** [comment] 2015-08-24 22:43
fixed in commit: 3ac41624f98568be339efb39a63e727e2933f256

**Closed by 00-Evan** 2015-08-24 22:43 UTC
Labels: Fixed In Beta, Minor
