### ISSUE TITLE
Fire-wall room and locked room generated mutually locked

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#1147] opened 2022-11-04 01:01 UTC
As I understand it, if a puzzle room (like the fire-wall room) generates on a floor, there's supposed to be a guaranteed solution item (like the potion of frost) on the floor.

In version 1.4.3, with the seed MKZ-VPN-GBT, floor 9 has a fire-wall room with a key behind it, and a locked room with a potion of frost within it. I didn't find any other potion of frost on the floor, and I used a scroll of magic mapping trying to confirm that.

I don't *think* anything happened that could have destroyed a potion of frost.

**Comment by 00-Evan** [comment] 2022-11-04 05:04
duplicate of #1049

**Closed by 00-Evan** 2022-11-04 05:04 UTC
