### ISSUE TITLE
Leather armor in Dwarven City

### ISSUE THREAD

**Issue by Block-Vader** [00-Evan/shattered-pixel-dungeon#361] opened 2019-12-02 19:40 UTC
According to the changelog, there shouldn't be T2 gear in caves+ anymore. However, I was able to find leather armor in the crypt room in dwarven city. As far as I know, armor found in the crypt room should have better average tier then armor normally generated in the same chapter. You probably forgot to apply the minimum tier rule to it.

**Comment by 00-Evan** [comment] 2019-12-02 19:41
beta issues shouldn't be posted here as there isn't a related source release, so there's no commits for me to reference when the issue is fixed. 

I am aware of this though (the new rules aren't applying in lots of cases actually), and it will be fixed in the next beta release.

**Closed by 00-Evan** 2019-12-02 19:41 UTC
