### ISSUE TITLE
music keeps playing after the game has been exited

### ISSUE THREAD

**Issue by yepyepyep4711** [00-Evan/shattered-pixel-dungeon#356] opened 2019-11-09 22:34 UTC
I experience the following phenomenon:
- after exiting the game (not swiping it away, just hitting the home button), the music will stop. So far this is the expected behaviour.
- after an undefined amount of time, the music will start playing again, although the game is still in the background.
- today, I found out this could even happen when the game was not among the list of open windows.
- the only way to stop the music is then to reopen the game and close it through swiping it away.

Phone is a OnePlus 5 on android 9.0.8

**Comment by 00-Evan** [comment] 2019-11-10 17:56
Are you making or receiving any phone calls before this happens? The game has some logic to pause/unpause music when calls are in progress, but otherwise uses the standard pause/unpause behavior when it is minimized.

**Comment by yepyepyep4711** [comment] 2019-11-11 12:35
Nope, I can't link this to any calls. It could be notifications from messaging apps, I guess, but not calls, unless I'm missing something. I've tried to provoke the behaviour, without luck so far.

**Comment by 00-Evan** [comment] 2019-11-11 17:19
Hmm, that's consistent with reports a few other people have also given me over the last while regarding continuing audio. It's always a recent android version, and always goes away once the user attempts to reproduce it again, generally after a device restart. I strongly suspect this is an Android issue so i'm closing this for now, but feel free to comment if you encounter the issue again.

**Comment by yepyepyep4711** [comment] 2019-11-11 21:41
Hmmm, sorry, but yes, I encounter it *all the time*. It's just happened again. I don't have a way to pinpoint it unless you have so debug version I should run, but this is in no way "solved". This is the only app that does this.

**Comment by 00-Evan** [comment] 2019-11-12 15:09
There is no need to be rude. I never stated that the issue was "solved", I merely closed it as there was nothing further to do with the information provided.

If you're able to consistently see the problem, then there are some things to try. Here is a link to an APK that's identical to the google play version of 0.7.5e but has the call state listener disabled. https://drive.google.com/file/d/1POV2CaKAhpr6BOlguH7UqdzBH_QAs3ma/view?usp=sharing

**Comment by yepyepyep4711** [comment] 2019-11-12 17:45
I under no circumstance intended to be rude. Sorry if it came across wrong. It might stem from the fact  that, in my experience, closing a ticket without further debugging means "this will not be considered a problem unless you the user prove otherwise", which I in turn found a surprising and premature course of action.

Be what may, thank you for the alternative apk, I've installed it and will report if anything happens. So far I can say that hitting the home button correctly silences the app, which was not always the case in the other. Now is probably a good time to add that I'm running the F-droid release, not the play store's.

**Comment by yepyepyep4711** [comment] 2019-11-13 18:04
24 hours of intensive use, and the music hasn't misbehaved once. As soon as the app is not full-screen anymore, the music stops. Perfect.

**Comment by 00-Evan** [comment] 2019-11-13 19:26
No worries about the miscommunication, I figured it was something like that. I don't like leaving issues danging but closing them isn't meant as a challenge to the reporter.

Glad to hear that APK is working better. Just to be sure (because this issue was inconsistent for some other reporters), could you download this 0.7.5e APK as well? This is regular 0.7.5e, with the call listener enabled: https://drive.google.com/file/d/1mrd4Nr4FP1adyYl9SiXZAZDl4gFVSrIW/view?usp=sharing

**Comment by yepyepyep4711** [comment] 2019-11-13 22:48
done. I'll let you know. Is there any difference between this one and the F-Droid one?

**Comment by yepyepyep4711** [comment] 2019-11-13 23:22
well, that was fast. First run. Left it alone for some time. Came back. Now the app is in the background, my screen is off, and the music is still playing. I'll revert back to the previous version

**Comment by 00-Evan** [comment] 2019-11-13 23:51
I'm actually trying to test the phone state listener and can't even get it to trigger correctly on an emulator or my test device. It seems like the call state listener is triggered too often on some devices and never on others. It's probably just not worth the bother, so I'll remove the functionality it in the next update.

As for F-droid vs. the APKs I've been providing (which are the Google Play edition), there are no gameplay differences but the Google Play edition has a few extra closed source features such as ingame supporter IAP (unlocked benefits are only cosmetic), and Google Play Games functionality.

**Comment by yepyepyep4711** [comment] 2019-11-14 06:59
"Quirk", nice :)

Yes, as far as I can see, the one without enabled state listener works as intended.

**Comment by 00-Evan** [comment] 2020-04-16 17:51
Fixed in commit b6b3c107f9e65b60386ccc83211802f705515a6f

**Closed by 00-Evan** 2020-04-16 17:51 UTC
Labels: Fixed Indev, Quirk
