### ISSUE TITLE
Steam cloud not working on Flatpak distribution of steam

### ISSUE THREAD

**Issue by YoriMirus** [00-Evan/shattered-pixel-dungeon#962] opened 2022-04-22 17:18 UTC
Hello. This is a follow-up to an issue I created recently (#959).

When you have a Linux system with steam installed using flatpak. The game is unable to read data from steam cloud. By default, the game saves data in the `~/.local/share/` directory. Which is where steam cloud also loads the data under normal circumstances.
However, when steam is installed via flatpak, flatpak uses sandboxing which causes some issues for this game.

According to: https://docs.flatpak.org/en/latest/sandbox-permissions.html
The steam application only has access to `$XDG_RUNTIME_DIR/app/$FLATPAK_ID` and its own data directory `~/.var/app/$FLATPAK_ID`.

This is confirmed by my problem in the previous issue. Steam saved the game data in `~/.var/app/com.valvesoftware.Steam/.local/share/.shatteredpixel`
Since it has no access to `~/.local/share/` it probably created its own `.local/share/` directory and saved the data there. However the game looks for the real `~/.local/share/`,or at least it's trying to, I can't find a where the flatpak version of the game stores its data.

Is there a way to make the game work with the flatpak version of steam? I don't have experience with java so I can't suggest a fix and I couldn't find the data location for the game when it is run via the flatpak version of steam. Searching for .shatteredpixel using nautilus didn't find anything besides the steam data location, so I'm not sure if the game can even read the true `~/.local/share/` directory (the game might be sandboxed too).

I was able to reproduce this on POP!_OS on a laptop, in a VM and on a Linux Mint VM, so I assume this happens on all flatpak distributions of steam regardless of linux distribution.

I apologize if this isn't enough information, I don't know much about linux, java or flatpak so I'm not quite sure what else to provide here. I hope this helps.

**Comment by 00-Evan** [comment] 2022-04-23 05:41
I'm going to try and reproduce this on my Ubuntu VM, but I'm not sure if there's much that can be done about this.

**Comment by 00-Evan** [comment] 2022-06-10 23:27
I see, that explains the discrepancy, or at the very least points to a related problem.

Your link won't work in this case as those are Android docs, and the problem is in the Desktop backend (which uses plain java). Will adjust this to assume there isn't a slash at the end of XDG_HOME

**Comment by santiagocezar** [comment] 2022-07-01 12:04
I haven't tried the beta in Steam, but I think it isn't fixed yet. $XDG_DATA_HOME is an absolute path, but in many parts of the code it's opening the files using Files.FileType.External, which adds $HOME at the start of the path.

Because of this the game ends up writing the files at /home/$USER/home/$USER/.var/app/com.valvesoftware.Steam/data/.shatteredpixel/shattered-pixel-dungeon/. You aren't accepting pull requests, so instead I explained below what I did to fix it:

> https://github.com/00-Evan/shattered-pixel-dungeon/blob/9eb2855d1be651164c3b16ef3106a4479e8e75a4/desktop/src/main/java/com/shatteredpixel/shatteredpixeldungeon/desktop/DesktopLauncher.java#L146
Replace Files.FileType.External with Files.FileType.Absolute

> https://github.com/00-Evan/shattered-pixel-dungeon/blob/9eb2855d1be651164c3b16ef3106a4479e8e75a4/desktop/src/main/java/com/shatteredpixel/shatteredpixeldungeon/desktop/DesktopLauncher.java#L156-L158
Same here, but with a condition to do that only on Linux. Also, you'll need to pass a Lwjgl3FileHandle to Lwjgl3Preferences to do that.

> https://github.com/00-Evan/shattered-pixel-dungeon/blob/9eb2855d1be651164c3b16ef3106a4479e8e75a4/desktop/src/main/java/com/shatteredpixel/shatteredpixeldungeon/desktop/DesktopLauncher.java#L141
And here the default value should be $HOME/.local/share

I hope that helps!

**Comment by Summertime** [comment] 2022-07-01 12:11
>  and the problem is in the Desktop backend (which uses plain java). 

I should have been clearer, java.nio is of the Java SE APIs, so it should work for both desktop and android

https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/nio/file/Path.html

**Comment by santiagocezar** [comment] 2022-07-01 20:04
> I don't accept code contributions though so I've removed your suggestions from your comment.

Ah, those code snippets were just quoting code from the master branch, completely unmodified.

**Comment by 00-Evan** [comment] 2022-07-02 20:20
> > I don't accept code contributions though so I've removed your suggestions from your comment.
> 
> Ah, those code snippets were just quoting code from the master branch, completely unmodified.

Sorry, but I couldn't really know that without reading over the code, which is what I was trying to avoid doing.

**Comment by 00-Evan** [comment] 2022-07-05 20:29
This should actually be fixed in the beta now, I expect v1.3.0 to release fully tomorrow.

**Comment by santiagocezar** [comment] 2022-07-05 23:43
Thank you! Can confirm saves are stored in the correct place inside and outside Flatpak.

**Comment by 00-Evan** [comment] 2022-07-06 17:29
fixed in commit dba3c7d49d2370d23aeea5fddb53ade710341656

**Closed by 00-Evan** 2022-07-06 17:29 UTC
Labels: Major Bug, Fixed in BETA
