### ISSUE TITLE
Throwing hammer does not show as stacked in quickslot after upgrading

### ISSUE THREAD

**Issue by vxiiduu** [00-Evan/shattered-pixel-dungeon#454] opened 2020-08-07 04:46 UTC
1. I had two non-upgraded throwing hammers, which were too heavy for me to use.
2. I upgraded the stack using a scroll of upgrade so that I could use them properly.
3. Only one of the throwing hammers was upgraded, and I quickslotted it.
4. I upgraded the second one, and the quickslot did not show the number 2 which usually is there to indicate a stack of more than 1 item.
5. In the inventory, it shows up as stacked, like normal.
6. I had to re-quickslot the stack of throwing hammers by long pressing for them to show up properly.

Not sure if it is supposed to only upgrade one of them, maybe it is intentional because throwing hammers don't break with use. But I think the quickslot not showing the full stack is a bug. This is in v0.8.2-beta-3. I know v0.8.2 was already released but this issue is probably still relevant because there is nothing in the issue tracker about it.

**Comment by 00-Evan** [comment] 2020-08-07 14:52
Hmm, I'm not able to reproduce this. Following your steps updates the quickslot as normal for me. Is there anything else that may have been at play here?

**Comment by vxiiduu** [comment] 2020-08-08 03:58
I'll try again and let you know what happens, next time I find throwing hammers. Is there a debugging cheat or something that I can use to quickly reproduce the situation without having to actually play the game?

**Comment by 00-Evan** [comment] 2020-08-08 14:56
Afraid there's no debug/cheat mode. I don't want to put something like that in because it'll lessen the achievement of winning legitimately.

**Comment by 00-Evan** [comment] 2020-08-17 03:40
Going to close this one as cannot reproduce for now. Feel free to comment if you can get consistent reproduction steps and I'll re-open it.

**Closed by 00-Evan** 2020-08-17 03:40 UTC
