### ISSUE TITLE
 "Level completed without killing any monsters" triggers in cases where it shouldn't

### ISSUE THREAD

**Issue by cgnj512** [00-Evan/shattered-pixel-dungeon#615] opened 2021-02-15 05:09 UTC
- Magical Holster
In BETA version `0.9.2`, every role start with their own small bag and **an extra Magical Holster**.
It wasn't like this in version `0.9.1`.
This feature is not mentioned in the offical blog "Coming Soon to Shattered: Tier Three Talents!".
(I just searched the word  "magical" in the passage and got no results.)

- Badge "Level completed without killing any monsters" bug
(After a second test, this "bug" is found in version `0.9.1` ,too.)
I started a new warrior game, killed a monster, and found the staircase down. Then I quit and start a new huntress game. I quit again and opened the saved warrior game. The player went down the stair and got the **"Level completed without killing any monsters" badge**. I think this is not a serious "bug" but it can be fixed.
As the video size is 38MB I cannot upload it.

**Comment by cgnj512** [comment] 2021-02-15 12:47
The "shop" sells the small bag that contain the most items occupy the player's bag, so the player will get a magical holster at the start of a new game?

**Comment by 00-Evan** [comment] 2021-02-15 19:49
I'm not able to reproduce the holster issue, all runs correctly start with just their standard bag for me.

Regarding the badge, that's a long-standing issue that I haven't addressed yet. I'll put that on the list to address.

**Comment by 00-Evan** [comment] 2021-02-21 00:13
I'm editing this issue based on the actionable content (point 2), will try to fix this for 0.9.2 full release.

**Comment by 00-Evan** [comment] 2021-02-26 17:26
fixed in commit 868b6d69953cfff5a2f356a9682fc46eb8c32ccd

**Closed by 00-Evan** 2021-02-26 17:26 UTC
Labels: Fixed Indev, Quirk
