### ISSUE TITLE
champion and crossbow

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1232] opened 2023-02-16 10:49 UTC
If the primary weapon of the champion is a crossbow, the power of dartst will not be change. If the secondary weapon is a crossbow, darts will deal more damage

**Comment by 00-Evan** [comment] 2023-02-16 16:41
I'm not able to reproduce this. Darts benefit from the crossbow regardless of the slot it is in.

**Comment by Lyx0527** [comment] 2023-02-16 21:40
@00-Evan Let me explain this bug again. If the primary weapon is +20crossbow，darts will deal only 4-12 damage

**Comment by 00-Evan** [comment] 2023-02-17 17:10
Judging from the video you sent over email, you neglected to mention that the crossbow is +0 and benefiting from the twin upgrades talent. I am able to reproduce this issue from the video under those circumstances.

https://user-images.githubusercontent.com/2347603/219718625-6bc83970-59f2-4911-ad32-28494b7a2242.png

**Comment by spixi** [comment] 2023-02-21 18:49
Doing it the other way around works for me. I currently have a Crossbow +9 as secondary weapon.

**Comment by 00-Evan** [comment] 2023-02-28 20:29
fixed in BETA-6

**Closed by 00-Evan** 2023-02-28 20:29 UTC
Labels: Minor Bug, Fixed in development, Caused by BETA
