### ISSUE TITLE
Sound glitch

### ISSUE THREAD

**Issue by built2spill69** [00-Evan/shattered-pixel-dungeon#811] opened 2021-09-11 13:21 UTC
Sound gets cut when disconnecting your bluetooth headphones.
I mean that, if, for instance, you want to play without headphones and you disable Bluetooth mid-play, the game won’t play any sound using your iPad’s speakers. You then have to hard restart the game to play any sound. As far as I know the issue is reproductible on Android 

**Warning : reproducting this glitch may force you to uninstall your game and reinstall it to have any sound unmuted. At the moment I can’t play the game with any sound.**
- Launch the game while being connected to any Bluetooth audio device
- While playing, turn Bluetooth off
- Check your iPad’s speakers volume : adding more or less won’t change anything as the audio is totally muted until you restart the game by removing it from your cached applications

iPad Pro 12 inches, iPadOS 14.7.1

**Comment by 00-Evan** [comment] 2021-09-11 16:53
Hmm, I imagine this might be some kind of built-in feature to prevent music accidentally playing publicly when bluetooth headphones disconnect. I'll look into this for the next update but it might be tricky for me to reproduce as I don't have the hardware to test this. Just for the sake of it, can you give a little more info:

- does the music resume if you reconnect your bluetooth headphones?
- does muting / unmuting music from the game's menu cause it to work?

**Comment by built2spill69** [comment] 2021-09-13 17:30
Yes, the music resumes when you reconnect your Bluetooth headphones;
No, muting or unmuting music/sounds won’t change anything;
Thank you

**Comment by SomeTroglodyte** [comment] 2022-04-06 09:26
You know, Gdx Music's OpenAL _desktop_ backend is a singleton that instantiates/opens underlying devices when it is created. So I would expect desktop to also _not_ follow changes in the system's devices or "default output" settings.

For desktop / Gdx / lwjgl3 backend, I know of only two ways to re-open devices, both tricky. Recreate the whole app, or instantiate a new Audio matching the backend and overwrite Gdx.audio and Gdx.app.audio (the latter possible via reflection - and 'we don't want reflection' is moot as Gdx does reflection for Music each end every newMusic call)... Though I admit I haven't looked at the API looking specifically for this usecase, nor have I inspected the corresponding mobile backend sources.

**Comment by 00-Evan** [comment] 2022-08-21 23:49
Hey, I've finally gotten around to testing this (sorry for the delay), but can't reproduce it. Starting the game with bluetooth earbuds, then turning of bluetooth, correctly switches the music to the regular speakers on my iPhone SE.

Closing this for now, let me know if you're still running into the issue.

**Closed by 00-Evan** 2022-08-21 23:49 UTC
Labels: Quirk
