### ISSUE TITLE
(beta) odd freeze when DM300 swiftthistle

### ISSUE THREAD

**Issue by MrCocoNuat** [00-Evan/shattered-pixel-dungeon#548] opened 2020-12-03 01:45 UTC
I was fighting DM300, got poisoned by gas, then it supercharged. Then I planted swiftthistle, stepped on it, walked towards pylon until time bubble expired, and then no controls responded. I could still exit the game to menu, but it was very slow to do so

After restarting game was normal again

I do not think this is a repeatable issue, but who knows?

V0.9.1 beta1

**Comment by 00-Evan** [comment] 2020-12-03 01:46
duplicate of https://github.com/00-Evan/shattered-pixel-dungeon/issues/546

**Comment by MrCocoNuat** [comment] 2020-12-03 01:47
Yeah I was wrong about nonrepeatable,
The same thing happened again immediately on the second supercharge

So I do not think this is "cosmic ray bit flip" type of glitch

**Closed by 00-Evan** 2020-12-03 01:46 UTC
