### ISSUE TITLE
Gateway trap ignores darkness level feeling

### ISSUE THREAD

**Issue by fregkos** [00-Evan/shattered-pixel-dungeon#971] opened 2022-05-03 22:30 UTC
While the darkness level feeling modifier is active, stepping on a gateway trap would keep the visibility of the previous cells after teleportation. The effect remains active until the level is reloaded by ascending/descending levels. I don't remember if reloading by quitting works. In the screenshot, I was just teleported.

![Screenshot_2022-04-30-12-22-47-68_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/1816060/166579075-73594b14-cf47-4348-b413-4a3b958e2c3b.jpg)

**Comment by 00-Evan** [comment] 2022-05-04 16:11
I'm not ale to reproduce this. Stepping on a gateway trap correctly darkens the cells outside of the vision range for me. I can see that the old vision there is quite small, were you blinded, or was there an item at that location which your talisman revealed?

**Comment by fregkos** [comment] 2022-05-11 22:41
No, I was not blinded and I didn't interact with talisman for the tiles near the trap. I only threw a steak.

**Comment by 00-Evan** [comment] 2022-05-12 15:17
Hmm, then I don't have an explanation for why only that 3x3 area is visible. Also, I just noticed that you state the bug occurs when visibility is reduced, but in your screenshot the level is regular (not a dark level) and the darkness challenge is not enabled either.

**Comment by 00-Evan** [comment] 2022-06-05 20:42
Closing this issue due to a lack of reproduction steps or furher reply. Feel free to comment and i'll re-open if you encounter this again and have more info.

**Closed by 00-Evan** 2022-06-05 20:42 UTC
