### ISSUE TITLE
Flathub SPD creating incorrect folder structure to place config files in.

### ISSUE THREAD

**Issue by stpnwf** [00-Evan/shattered-pixel-dungeon#1006] opened 2022-07-03 02:27 UTC
SPD will create the folder structure below instead of using the `~/.var` folder to save configs in.

`/home/User/`**home/User**`/.var/app/com.shatteredpixel.shatteredpixeldungeon/...`
Instead of here:
`/home/User/.var/app/com.shatteredpixel.shatteredpixeldungeon/...`

It creates `/home/User/` inside my user directory, like so:
```
home/User (my home folder)
├── home
│   └── User
│       └── .var (creates this entire structure and places config files here)
│          └── ... 
└── .var (instead of here)
    └── ...

```

If I delete this folder, it will just recreate it...

I could be wrong but I think this happened around the 1.2 update, I only noticed it later.

OS: Zorin OS 16.1 (Ubuntu 20.04 LTS based)
SPD: Installed via Flathub.

**Comment by 00-Evan** [comment] 2022-07-03 15:23
Duplicate of #962 , I aim to fix this in v1.3

**Closed by 00-Evan** 2022-07-03 15:23 UTC
