### ISSUE TITLE
More Quickslots

### ISSUE THREAD

**Issue by XiangRongLin** [00-Evan/shattered-pixel-dungeon#610] opened 2021-02-11 16:28 UTC
As a player i want to have more quickslots to have an easier access to all my wands, thrown weapons and artifacts.
So when the phone is in landscape mode or running on PC more quickslots could be added so the full width of the screen is utilized.

I just made the changes in my own fork, so i can have it for myself.
There are also some places where the constant `QuickSlot.SIZE` is not used. If you want to fix that you can take a look at my branch
https://github.com/XiangRongLin/shattered-pixel-dungeon/commit/55b0706ae69f5612dac54fa27e3dc6ad6abcc46f

**Comment by 00-Evan** [comment] 2021-02-11 17:09
duplicate of #413 and #299

**Closed by 00-Evan** 2021-02-11 17:09 UTC
