### ISSUE TITLE
Cosmetic: tapping repeatedly on an item with a full inventory makes the item fly upwards

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#640] opened 2021-03-03 19:52 UTC
With a full inventory, if you tap on an item you're standing on to pick it up, it bounces. If you tap repeatedly, it'll fly upwards. This appears to be entirely cosmetic, but it seemed worth reporting.

**Comment by 00-Evan** [comment] 2021-03-03 19:56
Duplicate of #40, #203 , and some others probably. Basically I'm aware of it but I'm keeping it in the game as it's very specific and fun.

**Closed by 00-Evan** 2021-03-03 19:56 UTC

**Comment by joshtriplett** [comment] 2021-03-03 21:03
Alright, no problem. :)
