### ISSUE TITLE
Shattered 1.3.1 Magical Fire Bugs

### ISSUE THREAD

**Issue by gigalh128** [00-Evan/shattered-pixel-dungeon#1048] opened 2022-07-26 22:36 UTC
Seems like the magical fire can't wall everyone out of the loot behind it! Seed is `SYZ-KSN-YVY`

Mage can enter it via warp beacon
https://user-images.githubusercontent.com/90579944/181123655-d9d05f25-ec69-4429-882f-2c6e1648a8b9.mov

The swarm/sheep take no issue with its existence (I spawned in a swam with the scroll of debug beforehand to have it be on floor 1)
https://user-images.githubusercontent.com/90579944/181123664-a2b3b9cb-d0be-4f05-9b75-55daa08cfb48.mov

Thanks to @zrp200's scroll of debug for helping me set up these scenarios. All of these scenarios should be possible in a normal game, and if you don't think they are, please let me know.

**Comment by 00-Evan** [comment] 2022-07-27 15:56
Looks like these are missing a checks for terrain that is impassable but not solid, should be an easy fix.

Also, while I'm fine with people using unofficial versions to find bugs that clearly exist in regular Shattered, please be careful while doing so and be sure to explain how anything you find relates to regular Shattered. In this case it's quite easy as you're just spawning items or enemies that exist in the regular game. I have nothing against scroll of debug but I have already gotten a few reports from users who find 'Bugs' by using scroll of debug to create situations that obviously cannot happen normally.

**Comment by Zrp200** [comment] 2022-07-27 22:22
> Also, while I'm fine with people using unofficial versions to find bugs that clearly exist in regular Shattered, please be careful while doing so and be sure to explain how anything you find relates to regular Shattered. In this case it's quite easy as you're just spawning items or enemies that exist in the regular game. I have nothing against scroll of debug but I have already gotten a few reports from users who have found 'bugs' by using scroll of debug to create situations that obviously cannot happen normally.

@00-Evan 

Anything found with scroll of debug is almost certainly going to be reproducible with standard debug code (excluding some cases of the use command). I would ignore anyone who tries to pass off a class cast exception as a bug though. _Scroll of Debug does not change anything at all about Shattered_ aside from adding the code needed to add scroll of debug to GameScene.java

If I were the one accepting bug reports found via Scroll of Debug, I would request a list of all commands actually put into scroll of debug to create the situation. This will allow you understand the debug code that would be entered for you yourself to reproduce it:
* `give` is reproducible by just giving yourself items when spawning in
* `spawn` is basically no different than changing Bestiary.java for the floor
* `set` just adds the trap to the floor
* `affect` is just calling Buff.affect on a desired character. 
* `use` is calling a specific method by a specific class, which is often not possible to do outside of scroll of debug without creating temporary items or bindings.

`affect` and `use` are the two that it is most important to know that were used, since it is possible to create impossible states with them (e.g. `use tengusmask choose gladiator` gives access to the gladiator subclass even on classes without access to them).

**Comment by 00-Evan** [comment] 2022-07-28 00:59
@Zrp200 

I'm not interested in coming up with a guideline for how to make reports based on any forks of Shattered, I was merely acknowledging that scroll of debug is a case where I'll allow them if they can be reproduced normally. If they can be reproduced then complex instructions that don't involve regular game actions shouldn't be necessary.

An example of what I mean: I got a report a few days ago where Goo did not behave as expected when spawned on floor 15. That's obviously not a bug that would occur in actual Shattered Pixel Dungeon.

**Comment by gigalh128** [comment] 2022-07-28 15:15
> If they can be reproduced then complex instructions that don't involve regular game actions shouldn't be necessary.

Can != likely (or easy). The reason why @Zrp200 mentioned a way to report stuff from the scroll of debug is because some things like cursed wand effects may *technically* be possible, but they are so unlikely that it would be difficult (but not impossible) to reproduce them in game. Another example could be trying to get a specific item through the hero's remains, which is pretty easy to do consistently with the scroll of debug, but a huge pain to do in normal circumstances.

**Comment by 00-Evan** [comment] 2022-07-28 15:40
I'm fine with instructions being specific, e.g. "get this item through remains" or "get this specific cursed wand effect in this situation", just as long as they're possible with regular game actions.

**Comment by 00-Evan** [comment] 2022-10-04 19:53
Fixed in commit 401411d16f5be7b87a9de37f75b1be8b6211ebc7

**Closed by 00-Evan** 2022-10-04 19:53 UTC
Labels: Quirk, Fixed in BETA
