### ISSUE TITLE
Inventory below an item after being revived through an unblessed ankh

### ISSUE THREAD

**Issue by Kurt0524301** [00-Evan/shattered-pixel-dungeon#1726] opened 2024-06-04 07:23 UTC
I was playing with the Mage when I accidentally died in the prison region. Fortunately, I had an Ankh but not blessed which meant I had to go to the spot where I died to retrieve my inventory. The problem is when I went back there was only a longsword in the ground (which wasn't there before I died) and I couldn't find my inventory even after searching the whole floor. I don't know if it's relevant, but when I was asked to choose what to keep when reviving, I choose a wand (not the staff).
(Edited)

**Comment by Kurt0524301** [comment] 2024-06-06 10:11
![Screenshot_2024-06-04-15-10-36-87_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/86095846/1f13e9c0-c082-45d1-a156-82d70e56543b)

![Screenshot_2024-06-04-15-10-08-65_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/86095846/e4cd8f29-d364-447a-bb86-ea5ff4f799a9)

Here are some screenshots after my run.

So basically, even if a mob died and dropped an item where my inventory should have been, the inventory (or bag) would still appear on top then? If so, then I'm not sure what happened as well.

**Comment by 00-Evan** [comment] 2024-06-06 15:22
Thanks for the dungeon screenshot, do you recall where you died initially and were revived by the ankh? I'll do a little test to confirm but I'm pretty sure that what you're describing is accurate, that a monster drop would not appear above the lost inventory.

**Comment by Kurt0524301** [comment] 2024-06-08 08:12
![IMG_20240608_160916](https://github.com/00-Evan/shattered-pixel-dungeon/assets/86095846/b39fcf2e-2ca8-4b28-8b3e-c2e14e8ffe7a)

Here, I died on the spot where the longsword was located and revived on the room full of traps (didn't remember the specific tile where I revived).

**Comment by Kurt0524301** [comment] 2024-06-08 08:21
![IMG_20240608_161810](https://github.com/00-Evan/shattered-pixel-dungeon/assets/86095846/05c03078-6697-4e33-8713-12cf0ab3985f)
![Screenshot_2024-06-08-16-16-08-44_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/86095846/6bfe21cf-2987-4e95-84b4-45e9f580c4c8)
![Screenshot_2024-06-08-16-15-28-78_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/86095846/ef5297cd-0f03-45d6-b985-a4201ad6be74)

Here are some additional data that might ~~or might not~~ help. It only happened once anyway, but just posted it here in case it might happen again.

**Comment by 00-Evan** [comment] 2024-06-15 16:03
I've tried testing this in a couple ways and unfortunately can't reproduce it. The dropped inventory correctly appears above other items in the cases i've tested, and is immune to effects like explosions.

I'm going to close this for now, but please feel free to comment if you encounter this again.

**Closed by 00-Evan** 2024-06-15 16:03 UTC
