### ISSUE TITLE
Pitfall Trap bug

### ISSUE THREAD

**Issue by mheder** [00-Evan/shattered-pixel-dungeon#144] opened 2016-11-21 10:53 UTC
With 0.4.2b I experienced a game crash during gameplay. I was stepping on a tile with a scroll on it while burning (I was a user of brimstone glyph and fireblast in that run) . The game stopped. I was able to restart the app and load the run. I found myself on the level below. When I made my way back up I figured that I stepped on a pitfall trap. 

In order to reproduce the problem I got the latest code (assuming that the bug might still be there with 0.4.3c) and compiled a version with very high trap numbers (nTraps = validCells.size()/2;) and every trap is a PitfallTrap (Trap trap = new PitfallTrap(); instead of the random pick from Trap Classes). All these changes are in RegularLevel class. 

In-game, when I discover a trap with search and step on it, I fall trough just fine. However, if I step on an undiscovered trap I get the following each time:

 java.lang.NullPointerException: Attempt to invoke virtual method 'int com.shatteredpixel.shatteredpixeldungeon.levels.Level.height()' on a null object reference
                      at com.shatteredpixel.shatteredpixeldungeon.mechanics.ShadowCaster.scanSector(ShadowCaster.java:79)
                      at com.shatteredpixel.shatteredpixeldungeon.mechanics.ShadowCaster.castShadow(ShadowCaster.java:55)
                      at com.shatteredpixel.shatteredpixeldungeon.levels.Level.updateFieldOfView(Level.java:886)
                      at com.shatteredpixel.shatteredpixeldungeon.actors.Char.act(Char.java:83)
                      at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob.act(Mob.java:156)
                      at com.shatteredpixel.shatteredpixeldungeon.actors.Actor.process(Actor.java:216)
                      at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene$2.run(GameScene.java:409)

I suspect that my tinkering with RegularLevel does not infer with this, so we might have an actual bug here.

**Comment by mheder** [comment] 2016-11-21 21:57
Actually, I cannot reproduce the bug every time. After more testing it seems to me that the issue occurs about 30% of the time. I cannot see a pattern yet.

**Comment by 00-Evan** [comment] 2016-11-21 22:15
This looks like it is a race condition, probably introduced in 0.4.2.

Will fix, thanks.

**Comment by 00-Evan** [comment] 2017-01-29 04:08
I 'think' i've got this fixed indev, let me know if you can still reproduce it after the release of 0.5.0

**Comment by 00-Evan** [comment] 2017-02-14 19:19
fixed (albeit sloppily) in commit 9dd910de02facc176df95ba34b0e1e20e7338f8a

**Closed by 00-Evan** 2017-02-14 19:19 UTC
Labels: Fixed Indev, Minor

**Comment by mheder** [comment] 2017-04-14 11:11
I confirm that it is fixed. I tweaked the latest version the same way (all traps are pitfalls, there is a lot of them), fell through 100s of traps, no crash.
