### ISSUE TITLE
Falling rock warning particles sometimes fail to appear

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1182] opened 2022-11-27 08:07 UTC
There are falling rocks in the upper left corner, but they are not shown
![Screenshot_20221127_124604_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/118305192/204125238-113bde46-58fe-48f7-9832-d4fd693d0ceb.jpg)
![Videoshot_20221127_124938](https://user-images.githubusercontent.com/118305192/204125244-f3853e64-2513-4a8e-9ae2-7ba7eeaabc08.jpg)

**Comment by 00-Evan** [comment] 2022-11-27 16:51
This is odd, because the game does try to garuntee that an adjacent tile is safe, which means that the top-left tile should have been safe. It's a bit tricky to see exactly what's going on here because it's just a screenshot, and particle effects aren't precise so a screenshot can sometimes be misleading when it comes to which tile it is affecting. Let me know if you run into this again.

**Comment by 00-Evan** [comment] 2022-11-30 16:41
Reopening based on this video, which was incorrectly sent in a new issue:

https://user-images.githubusercontent.com/118305192/204788934-3fb65655-e606-4439-aafd-6a7d931b1641.mp4

This might be a part of the bigger 'particle effects sometimes fail to appear' error which has been around for a while. Unfortunately I don't have a consistent method for reproducing that, but I will try to investigate it again.

**Comment by 00-Evan** [comment] 2022-12-05 20:04
I can't reproduce this exactly, so we'll have to wait to be sure, but I think I've fixed this in development.

**Comment by Lyx0527** [comment] 2023-02-12 14:42
https://user-images.githubusercontent.com/118305192/218317704-f559f3eb-ef76-43f4-8015-89af38d16405.mp4

It seems that this bug has not been fixed @00-Evan

**Comment by 00-Evan** [comment] 2023-02-12 23:57
Hmm, darn, I have seen some other particle error reports so I suspect this wasn't fixed. Will look at this again and see if I missed anything for BETA-3.

**Comment by 00-Evan** [comment] 2023-02-13 21:28
After doing more testing I have found another potential cause for this issue. Please test again when I release BETA-3 soon. It might actually be fixed this time.

**Comment by 00-Evan** [comment] 2023-03-13 17:27
fixed in commits 03bc987ec33418a0b63a826110c3b78f36cf5905 and 853e6050b162dadb1ea0157cde28349ad4d25ad9

**Closed by 00-Evan** 2023-03-13 17:27 UTC
Labels: Minor Bug, Fixed in BETA
