### ISSUE TITLE
Can attack with glaive through wall next to open doorway, despite no line of sight

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#538] opened 2020-11-19 17:02 UTC
If you're standing next to an open doorway, and you have some ability (such as the huntress's innate ability) to see nearby enemies through walls, you can attack with a reaching weapon like the glaive through the wall, despite having no line of sight.
![Screenshot_20201119-085654](https://user-images.githubusercontent.com/162737/99698357-88bb0500-2a45-11eb-9ce9-4528ea7cb54e.png)

**Comment by 00-Evan** [comment] 2020-11-19 17:04
Duplicate of #388

**Closed by 00-Evan** 2020-11-19 17:04 UTC

**Comment by joshtriplett** [comment] 2020-11-19 17:07
Ah, thank you.
