### ISSUE TITLE
Black screen on start

### ISSUE THREAD

**Issue by drizt** [00-Evan/shattered-pixel-dungeon#1546] opened 2023-11-25 16:48 UTC
I again get black screen on start. Problem probably related with my device it happens sometimes. I can't start Camera, 
Firefox and Shattered Pixel Dungeon. Camera has black screen too. Firefox show interface but can't open any page. Any other application works as regular. It's real big trouble to each time restore my twrp backup and restore data after last backup. So I here ask how to get reason why SPD can't start? I'm a programmer but haven't experience with Android. But I can do all requireded actions to get all logs and obtain a problems. Please help me.

**Comment by 00-Evan** [comment] 2023-11-25 18:20
If Shattered isn't the only app that has these problem then it is likely an issue with your device. Unfortunately there's not much I can do to help with device-specific issues. The game isn't even managing to launch, so there likely aren't any log entries that would be useful here.

You mention backups though, so is the black screen somewhat dependant on your save data? Does the game start working again if you do things like clear its app data and cache?

**Comment by drizt** [comment] 2023-11-25 18:33
Clean cache or reinstall app can't help. Problem persistent. I think SPD actually started but hangs somewhere before first screen.

**Comment by drizt** [comment] 2023-11-25 18:35
I tried too google something about my problem. But can't find anything, Atm I want to compare my current /data with older /data. I mean compare all files on devices and maybe I can find who breaks my system.

**Comment by 00-Evan** [comment] 2023-11-25 19:23
hm, unfortunately the issue is related to your device then. Perhaps Shattered is trying to load some assets and the file operations are hanging. I'm going to close this as there's nothing to be done from my end I'm afraid.

**Closed by 00-Evan** 2023-11-25 19:23 UTC
