### ISSUE TITLE
Shard of oblivion don't prevent items from being identified 

### ISSUE THREAD

**Issue by Titanic472** [00-Evan/shattered-pixel-dungeon#1943] opened 2024-12-25 21:40 UTC
Shard of oblivion should prevent equipment from being identified, but after quitting and loading game again all items that should be prevented from being identified and were ready to be identified are automatically identified. 

Version V3.0.0-BETA-1.1

Upd: only equipment that was equipped before quit

**Comment by 00-Evan** [comment] 2024-12-26 20:02
I'm not able to reproduce this. Saving/loading a game with an item ready to ID doesn't ID it for me. Can you give more information about your run? There is probably something more specific about it that is triggering this.

**Comment by Titanic472** [comment] 2024-12-27 09:15
I was using Cleric, maybe it can be helpful

Seed FWG-XWL-GTK

I will try to figure out what is triggering this or when it happens

**Comment by Titanic472** [comment] 2024-12-27 21:23
I replayed this run and nothing happened so I think it might have happened because of missclicking scroll of identity when using unstable spellbook. I will pay attention on this in my next runs and if it happens I will try to figure out how it happened.

**Comment by 00-Evan** [comment] 2024-12-30 18:23
Going to close this for now as it seems like it was a false report. Feel free to comment if you encounter this again and I'll re-open.

**Closed by 00-Evan** 2024-12-30 18:23 UTC
