### ISSUE TITLE
Seeded runs not always identical

### ISSUE THREAD

**Issue by dplynx** [00-Evan/shattered-pixel-dungeon#1039] opened 2022-07-20 18:45 UTC
A couple of times now I’ve started a seeded run looking for a specific piece of loot that was either on the ground or part of a quest reward, only to have a different item generate. The last time this happened I got suspicious and ran the seeded run again, and this time I did get the same quest rewards as the original run.

On the run that was different, everything was identical up to floor 3. Floor 3 generated with the same map layout but with different items on the ground, including an artifact where there was none before. The quest reward from the ghost was a different weapon, but it was still +2 as it was before. I deleted the run, started again, deleted the run again, started again and this time it was identical to the first run (at least as far as floor 3 where I am now). Unfortunately I don’t have many more details or insights into what is throwing off the seed. I’m playing on iPad.

**Comment by dplynx** [comment] 2022-07-20 19:26
FWS-JNN-LZP. Played as a rogue. In the original run, the ghost’s weapon reward was a glaive +2. In the run that was different, the reward was a battle axe +2. In the different run, a timekeeper’s hourglass was sitting on the ground on floor 3, and in a different room a wand of warding was on the ground, neither of which were there in the original run. In playing it again, on the seeded run that matched the original, I’ve now encountered differences on floor 6. In the original run, I (rather stupidly) died to an explosive trap while stepping around a mimic at the bottom of the map on floor 6. This time, the mimic isn’t there (although the explosive trap is).

**Comment by 00-Evan** [comment] 2022-07-21 17:03
I've gone though that seed a couple of times, and here's what I found:
- ghost has a battleaxe and leather from their quest, both +2
- An hourglass and wand of warding appear on floor 3
- There is a secret food room (with blandfruit) on floor 2, and a secret summoning room on floor 6.
- There is no mimic that spawns on floor 6, but there is an explosive trap room toward the bottom.

Seeing as most of these noticed differences occur around floor 3, when items are generated, but after the layout is generated, that means that either enemy spawning or item spawning itself are the likely culprits. When you first played this run, was it a bit ago during the 1.3.0 beta? There was an inconsistency there which was fixed during the beta.

**Comment by dplynx** [comment] 2022-07-22 03:41
Yeah your results mostly match my second (different) run. The first run definitely had a mimic in that explosive trap room, in the top left corner. The explosive trap one down fro the top left corner is the one I died on as I stepped around the mimic, so I remember that clearly.

No betas; I posted the day I played it, when I had the up-to-date version from the App Store. Could it have to do with mimic spawning (or not)? Wasn’t there a mimic on floor 3 too? I somewhat remember shooting one on the left side of that + overhang bridge thing.

**Comment by 00-Evan** [comment] 2022-07-22 16:40
Thanks for the video. I've reviewed it a bit, did some testing, and have actually found two bugs causing inconsistency!

One of them is caused by that 1.3.0 beta fix being applied incorrectly, the number of enemies spawned so far can affect item generation on future floors.
The other is an inconsistency with the colors/glyphs/gems that go on potions/scrolls/rings, the internal list used to map these things did not have a predetermined order every time the game was run.

Will get both of them fixed for 1.3.2

**Comment by dplynx** [comment] 2022-07-24 00:17
I’m glad I could help! Seeded runs may be exceedingly tricky to develop, but they are a blast. I got the chance to redo that run with what became a massively upgraded vampiric glaive, whereas before I would only have had tears and regret 😂 Thanks!

**Comment by 00-Evan** [comment] 2022-07-27 16:32
fixed in commits 345cb9baa535745f349b2dbe7a1c290f2a88b95c and 4f800f4ebcf3965a80a25068fb3763d9026bf415

**Closed by 00-Evan** 2022-07-27 16:32 UTC
Labels: Major Bug, Fixed in BETA
