### ISSUE TITLE
Badge for fourth boss (King) did not process victory

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#1012] opened 2022-07-06 10:09 UTC
I carefully defeated the fourth boss without ever once using a weapon or wand on him, and the badge for doing that did not get granted.

I used a combination of his lifeline, a scroll, and a potion.

Happy to provide additional information.

**Comment by 00-Evan** [comment] 2022-07-06 17:25
What did you use to attack his minions? It would be helpful to know everything you used to help pinpoint whether this is a bug or not.

**Comment by joshtriplett** [comment] 2022-07-06 23:28
@00-Evan Mostly melee with the wizard's staff.

I very rarely used it as a wand, and only when I could be absolutely sure I wouldn't hit the boss. It's a staff of blast wave, and I never targeted the boss or any square adjacent to him. I never bounced a minion *into* him either because I didn't remember if that did damage and I wasn't sure if the "directly" in the badge description would permit that.

I also used a scroll of retribution once when there were a few dozen minions around. And I threw a potion of liquid fire at the boss (from adjacent to him) towards the end. In both cases, I was assuming the badge description of "without ever directly attacking him with weapons or wands" was literal: I never used a weapon or a wand on him.

**Comment by joshtriplett** [comment] 2022-07-08 06:50
I'm sure, yes; I was specifically aiming for the new badge and paid close attention to wand usage.

**Comment by 00-Evan** [comment] 2022-07-08 17:08
Hmm, I'm not sure what the cause is then. For reference here are all the cases that set the player to be ineligible for the badge during the DK fight:
- DK takes physical damage from the hero, and they either have a weapon or a ring of force.
- DK takes damage from any wand (including wards from wand of warding, excluding chaining from wand of lightning)
- DK is directly targeted by wand of Corrosion or wand of Corruption
- DK is within the AOE of wand of regrowth

The flag is set to true when the player initially descends down to the boss depth, did you perhaps do anything in particular after descending but before fighting DK?

**Comment by joshtriplett** [comment] 2022-07-10 11:04
What counts as "physical damage" here? Because I was wearing a ring of force at the time; could that have affected anything other than a melee strike?

**Comment by joshtriplett** [comment] 2022-07-10 11:06
Also, I descended to that level a long time before starting the battle; I went back up for a while and returned much later. Would that make a difference?

**Comment by 00-Evan** [comment] 2022-07-11 16:11
Ring of force should only matter if you're making an attack that would otherwise have just used your fists.

Descending and then leaving the depth for a while might make a difference though, I'll look into making the logic more resilient in 1.3.2 by having the flag set itself to true when the boss fight actually starts.

**Comment by 00-Evan** [comment] 2022-07-27 16:31
fixed in commit 40b16154dc0c32190cd957ebdfae7398fb4258d8

**Closed by 00-Evan** 2022-07-27 16:31 UTC
Labels: Minor Bug, Fixed in BETA
