### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [00-Evan/shattered-pixel-dungeon#798] opened 2021-08-31 03:30 UTC
https://monitor.f-droid.org/builds/log/com.shatteredpixel.shatteredpixeldungeon/570

```
Preparing "Install Android SDK Build-Tools 30.0.2 (revision: 30.0.2)".

FAILURE: Build failed with an exception.

* What went wrong:
'void org.apache.commons.compress.archivers.zip.ZipFile.<init>(java.nio.channels.SeekableByteChannel)'
```

Could you please take  look? We got the same error when building https://github.com/yairm210/Unciv so it may be related to libgdx. Thanks!

**Comment by 00-Evan** [comment] 2021-08-31 06:21
Shouldn't be libGDX, it looks like older versions of Unciv successfully built with the most recent version of libGDX. Android Gradle plugin 7.0.0+, or Gradle 7.0.0+ seem like likely culprits, as builds for both Unciv and Shattered look like they started failing after changing gradle versions.

I'm going to close this as this is not an issue with Shattered's code, but feel free to reply if you want to discuss further.

**Closed by 00-Evan** 2021-08-31 06:21 UTC

**Comment by mymedia2** [comment] 2021-09-07 19:56
I am not an Android developer and I have no idea what caused the error. But I personally applied the following workaround to Shattered Pixel Dungeon for fix build an APK. I hope this will help.

```diff
diff --git a/android/build.gradle b/android/build.gradle
index 2a3be2f16..65094d75a 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -2,6 +2,7 @@ apply plugin: 'com.android.application'
 
 android {
     compileSdkVersion appAndroidCompileSDK
+    buildToolsVersion "30.0.3"
     compileOptions.sourceCompatibility = compileOptions.targetCompatibility = appJavaCompatibility
 
     sourceSets.main.assets.srcDirs = [new File(project(':core').projectDir, "/src/main/assets")]
```

**Comment by supermamie** [comment] 2021-09-10 09:35
@mymedia2 as the issue is closed, maybe you should create a pull request for this ?

**Comment by linsui** [comment] 2021-09-10 10:10
According to https://github.com/yairm210/Unciv/issues/5036 that does not work. I still don't know how to fix it properly but I have push a workaround.

**Comment by 00-Evan** [comment] 2021-09-11 16:39
> 
> 
> Hi, is this the reason why the new version isn't yet on Android?
> 
> I saw on the announcement that F-Droid is no longer listed as "available on..."
> 
> Cheers

This shouldn't make any difference to whether F-Droid can build the game. After the last time there were major delays/issues with F-Droid (#459 and #479) I decided to drop them as an official distribution platform for Shattered. That's why they're not mentioning anywhere on the website or releases page anymore. Of course, I can't and don't want to stop F-droid from distributing the game, I just can't reasonably endorse a platform that sometimes has build issues that last for weeks.
