### ISSUE TITLE
Unspecific text “Killed by Something” when falling down

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#578] opened 2021-01-04 17:57 UTC
Yes, it was yet another stupid death. I trusted auto-pathfinding and Potion of Levitationʼs effect ended and I fell down. But i feel that “Killed by Something” is too unspecific. It should have a better description.
![Screenshot_2020-12-30-13-19-49-279_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/3192596/103564132-54e55300-4ebe-11eb-8c4e-e531a58b8384.jpg)
![Screenshot_2020-12-30-13-19-59-400_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/3192596/103564160-5c0c6100-4ebe-11eb-8305-1fbc882438de.jpg)

**Comment by 00-Evan** [comment] 2021-01-04 18:09
This message appears when the cause of death does not have any text associated with it by the game. Chasms obviously do have a message: "Died on Impact". I just tested this and dieing to a chasm does correctly show this message. Can you give any more info about how you died?

**Comment by antikovt** [comment] 2021-01-04 18:17
Maybe "Died on impact" only works if you get the "Are you sure you want to jump?" screen, but doesn't work if you fall in the middle of a chasm while using a flying potion? I'm not sure if these cases are any different in terms of code

**Comment by 00-Evan** [comment] 2021-01-04 18:21
They are different when it comes to how the chasm effect is triggered, but once it is triggered they are identical. I just tested this as well and falling after levitation also correctly shows "Died on Impact"

**Comment by spixi** [comment] 2021-01-04 21:35
This is weird. It did not happen for me. I tapped a point to move the character, but forgot that he was still under the impact of the Potion of Levitation.

**Comment by 00-Evan** [comment] 2021-01-04 22:24
Without any way to reproduce this issue, I'm going to close it for now. Please feel free to comment if this happens to you again and I'll re-open.

**Comment by spixi** [comment] 2021-01-04 22:59
I am sure that I said “no” to an unblessed ankh, but I really cannot reproduce the issue.

**Comment by 00-Evan** [comment] 2021-01-04 23:28
I see, that's a significant extra detail! I'll reopen and investigate that.

**Comment by 00-Evan** [comment] 2021-01-14 03:26
fixed in commit 5467883a695e78c3c8f658eb6b81503a49f6bc39

**Closed by 00-Evan** 2021-01-14 03:26 UTC
Labels: Fixed Indev, Quirk
