### ISSUE TITLE
Skeletons move in the turn where they are killed

### ISSUE THREAD

**Issue by Wilker-a** [00-Evan/shattered-pixel-dungeon#336] opened 2019-08-21 10:01 UTC
the bug is persistent (as in, happens every time).

whenever skeletons are killed, they play a turn without animation. if you are witin range of attack, you take damage upon death (apparently with a lower evasion chance than usual), otherwise, they move a tile before disappearing (item drops also appears in the new location).

this probably happens because the game does not check if the character is alive before making a turn (or at the end of the player's turn, but this logic would probably fail when actions takes less than a turn).

**Comment by 00-Evan** [comment] 2019-08-21 13:32
That damage-taking effect when you are within range is their on-death effect, named 'bone explosion'. The game is not processing an extra turn for them, they are dieing correctly and triggering that deathrattle effect. bone explosion is very accurate, but armor reduces it with double effectiveness.

If you see them walking before dieing, this is likely because a debuff effect (e.g. corrosion) is killing them. Debuffs generally act last in a turn (there are a couple exceptions) which means skeletons will get a chance to act before dieing.

If this isn't what you're trying to describe, could you please include a video?

**Comment by 00-Evan** [comment] 2019-08-23 19:06
Skeletons don't have any special logic for when they die, so there shouldn't be a difference here between them and other enemies. I'm going to close this issue for now, feel free to comment again if you can reproduce that behavior and I'l re-open it.

**Closed by 00-Evan** 2019-08-23 19:06 UTC
