### ISSUE TITLE
v0.6.0 starves player when changing floors

### ISSUE THREAD

**Issue by durbanfrazer** [00-Evan/shattered-pixel-dungeon#183] opened 2017-06-08 13:59 UTC
occasionally when entering a level  (new or previous) I will immediately starve to death even if I was at full health and not hungry.

a vertical stream of 1s appears above the character, suggesting that the game ran through time very quickly (without me moving) until I died

**Comment by 00-Evan** [comment] 2017-06-08 17:56
This is almost certainly due to a race condition, it happens very rarely overall, but some users are getting it semi-frequently.

**Comment by 00-Evan** [comment] 2017-06-08 19:48
I can't reproduce this bug, but i'm fairly confident I've identified the situations in which it can occur. I'm going to tentatively label this as fixed indev, and will release the attempted fix as part of 0.6.0a.

**Comment by durbanfrazer** [comment] 2017-06-09 05:20
Game duration when I die is 2147483647

**Comment by 00-Evan** [comment] 2017-06-12 00:13
hopefully fixed in commit db972107288a77d3747c7c9a0b8d7668eb3bd518

Will reopen if reported again

**Closed by 00-Evan** 2017-06-12 00:13 UTC
Labels: Fixed Indev, Major
