### ISSUE TITLE
Door Shuts on Enemy Duplicated by Cursed Armor of Multiplicity

### ISSUE THREAD

**Issue by egocarib** [00-Evan/shattered-pixel-dungeon#307] opened 2019-05-08 02:23 UTC
![Screenshot_20190507-211130](https://user-images.githubusercontent.com/3429497/57344720-ed399c00-710d-11e9-93d7-4afc211c8cd1.png)

This happened twice within a few minutes while I was being attacked by swarm of flies and wearing armor of Multiplicity. New fly appears next to me and the door shuts over the one I'm currently attacking.

P.S. - Was hilarious trying to escape alive from the flies in this armor! 😄

**Comment by 00-Evan** [comment] 2019-05-08 23:18
That's an interesting one. It's being caused by the duplicated enemy inheriting all the properties of the previous one, including position. This means that when the duplicate is actually placed into the game, it is technically moving from the position of the original enemy, which causes the door to close. I've got this corrected indev and will include it in the next update.

**Comment by 00-Evan** [comment] 2019-05-26 04:03
fixed in commit 133a39026e7119eb50960edd472a798baf4b3d9e

**Closed by 00-Evan** 2019-05-26 04:03 UTC
Labels: Fixed Indev, Minor
