### ISSUE TITLE
Oh or old music back please 😂🥺

### ISSUE THREAD

**Issue by MarshMeadow** [00-Evan/shattered-pixel-dungeon#1559] opened 2023-12-03 08:01 UTC
I would love to have the option of trun on old or new music in the game

**Comment by 00-Evan** [comment] 2023-12-03 16:40
Duplicate of #1437 and #763

In general I am not interested in adding toggles that revert feature updates.

**Closed by 00-Evan** 2023-12-03 16:40 UTC

**Comment by Shekel-JF** [comment] 2024-01-11 23:29
Well, why would you force it on people when a lot of community find it less fitting than the old one?

**Comment by Saquial-g** [comment] 2025-04-25 20:45
What a shame...
