### ISSUE TITLE
Stuck in shop

### ISSUE THREAD

**Issue by arboulton** [00-Evan/shattered-pixel-dungeon#116] opened 2016-09-28 11:01 UTC
Playing the current PC built, I keep getting stuck in the shop on floor 6. If after clicking one of the items on sale, moving to that item leaves me on top of another item, the entire interface becomes unresponsive after I dismiss the purchase window, unless I restart the game (first image).  Moving over a tile that doesn't contain an item allows me to continue.

Stuck:
![stuck](https://cloud.githubusercontent.com/assets/6050371/18911134/1c8185e2-8573-11e6-8ef0-27b9053bc157.PNG)

Not stuck:
![notstuck](https://cloud.githubusercontent.com/assets/6050371/18911136/22bbc4c2-8573-11e6-84e6-d957de60b71b.PNG)

**Comment by 00-Evan** [comment] 2016-09-28 17:39
There is a separate repo for the pc version, please post any pc-specific issues there: https://github.com/00-Evan/shattered-pixel-dungeon-gdx/issues

This also seems to be a duplicate of this existing issue: 
https://github.com/00-Evan/shattered-pixel-dungeon-gdx/issues/21

**Closed by 00-Evan** 2016-09-28 17:39 UTC
