### ISSUE TITLE
Game stuck at Tengu fight

### ISSUE THREAD

**Issue by pescepalla** [00-Evan/shattered-pixel-dungeon#588] opened 2021-01-10 19:31 UTC
The game becomes partially stuck during tengu fight. Tengu looks permanently turned into a steam cloud while the time wheel turns again and again. Exiting and reentering the game allows me one turn before getting stuck again. Winning the fight results in the game resuming normally.

![Screenshot_20210110-202348_Shattered_Pixel_Dungeon](https://user-images.githubusercontent.com/46329185/104133262-c02d9a00-5382-11eb-8279-24cbf7f9e8bf.png)

Version: 0.9.1b (504)
Seed: 762077771128
Challenge Mask: 145

**Comment by 00-Evan** [comment] 2021-01-10 20:04
I'm aware of this, it's caused by v0.9.1b and will be fixed soon in a followup patch.

**Comment by joshtriplett** [comment] 2021-01-10 21:58
I ran into this issue, and then I ran into a similar issue in the DM-300 fight that might have the same cause. I paralyzed it the same turn it tried to use the rock-fall special attack. Same symptom: frozen with spinning wheel.

**Comment by Leajian** [comment] 2021-01-12 14:51
I had the same with DM-300, I don't really know the cause, that's why I didn't post, but I have a video of it somewhere. The only difference from Tengu was that exiting and re-entering the game allowed me to continue normally the execution.

**Comment by 00-Evan** [comment] 2021-01-14 03:26
fixed in commits 6e760711136636386ec951c2f849552f06c33cad and ecd93baffd316556b6b82d4d12be1db4ac889703

**Closed by 00-Evan** 2021-01-14 03:26 UTC
Labels: Fixed Indev, Major
