### ISSUE TITLE
Throwing runestones on an enemy will trigger hidden traps below the enemy

### ISSUE THREAD

**Issue by ChuiyuWang1** [00-Evan/shattered-pixel-dungeon#1623] opened 2024-02-14 18:52 UTC
The stone first triggers hidden traps and then triggers the runestone's effect.

**Comment by 00-Evan** [comment] 2024-02-25 19:08
Closing this as it's effectively a duplicate of #1622

**Closed by 00-Evan** 2024-02-25 19:08 UTC
Labels: Minor Bug
