### ISSUE TITLE
Water/darkness redraw issues; affecting v0.6.2e.

### ISSUE THREAD

**Issue by B00daW** [00-Evan/shattered-pixel-dungeon#225] opened 2018-01-12 04:45 UTC
![2018-01-12_00 38 12](https://user-images.githubusercontent.com/18320731/34878606-bda27094-f778-11e7-955f-09ba3b8fa1ab.png)
Phone specs:
HTC PC36100 (EVO 4G/Supersonic)
CPU: Qualcomm Snapdragon S1 QSD8650
GPU: Adreno 200
Android Version: 2.3.7

Hey Evan,

I know my phone is "ancient"; but I don't believe in planned obsolescence.  Game works fast and great, except for a couple odd things with the graphics...  I've tried changing the graphics modes with the "power saver" option and that doesn't do anything.

When the "flowing water" is on screen sometimes, the water texture wrongly maps over walls, etc.  Seems to happen in between mapping of darkness and water.

Darkness also at times completely envelopes the screen at certain blocks the character stands on; likely in relation to map "lighting" mechanics.

Let me know if I can help you somehow to troubleshoot and debug.

**Comment by 00-Evan** [comment] 2018-01-13 07:50
Hey B00daW,

Firstly, don't worry about the age of your device. I'm very happy that shattered still runs on older hardware and I have no intention to drop support for it. While I can't guarantee as smooth a gameplay experience as on a modern device, I am definitely still willing to fix issues and make improvements for users on old hardware.

Regarding the water, what you're actually seeing here is the terrain failing to render, which exposes the water beneath it. The game does have some logic to selectively ignore rending tiles which are supposed to be off screen, but clearly it isn't working correctly here. Does zooming in/out or moving the camera correct this? Also, is there any consistency to when this happens?

Regarding lighting, this is an issue that I actually hope to have fixed in 0.6.3. I have completely rewritten the game's lighting logic, which should give a nice performance boost, and fix some issues.

**Comment by B00daW** [comment] 2018-01-13 22:25
Evan,

Wonderful that you do not intend on dropping support.  I'm pretty addicted
to this nice little game.

Zooming in and out does not seem to affect the issue.  Seems that when it
happens, plants do not get cut away as well.

There is a rather serious bug that also happens when there is a lot of fire
or spells going on while a Sad Ghost mini-boss is around.  Seems to happen
a lot with the Gnoll that shoots arrows.  At times the application crashes,
phone becomes unresponsive while the game screen is animating, etc.

- Sean

**Comment by 00-Evan** [comment] 2018-01-14 23:05
Regarding that freezing, there was previous a bug where some enemies with ranged attacks could freeze the game, but I think that's been fixed. Are you sure its happened to you with the other two bosses though? They don't do anything special when it comes to timing.

The tile grid bug is very odd then, if its not being caused by some weirdness to do with the camera and visibility culling.

As i've mentioned i'm making improvements to visibility and tile mapping logic in 0.6.3, as well as other general bugfixes so let me know if these issues persist for you after 0.6.3 is released. If you're opted-in to betas you'll get the first beta of 0.6.3 fairly soon.

**Comment by B00daW** [comment] 2018-01-15 05:45
So some weird stuff happened while I was playing with it at work today.
Been noticing a lot of softlocks happening with Gnolls; making the hardware
buttons and UI unresponsive.  The "working/timer" icon will animate and the
music still plays, but Android OS will lock up.  Eventually it soft
resetted itself, but did not boot up to a sane environment.  I had to hard
reset by yanking the battery out to continue.  Believe it or not, this is
not something I usually have to do with my phone.  Not certain when it's
really happening now.  Are there any logs in the /data/data/... section,
etc that I can look at?

I get Shattered Pixel Dungeon from F-Droid.  I don't use Google Play.  Is
the beta opt-in feature there?  I wouldn't mine picking it up from the
GitHub either.  I could check to get an ARM Android SDK environment set up
as well.

**Comment by 00-Evan** [comment] 2018-01-15 19:53
Hrm, that's troubling.

There should be no way for shattered to cause general device instability. It sounds like something else is causing this issue. You mention the music stopping, does turning music off help with this at all?

There may be some general device logs that could help identify this, I'd suggest recording your device's logcat, though sifting through it may be a pain.

Sadly, betas are only through google play. F-droid requires that source is released, and I do not release source for betas. I could give you an APK, but the signature would differ from the f-droid version so you'd have to reinstall. This isn't ideal, I know, but previously when releasing source with betas, other variants of the game would take features from shattered and release them before I had the opportunity to. This led to lots of confusion and people falsely accusing me of copying others work.

**Comment by B00daW** [comment] 2018-01-16 06:24
Reread about the music.  The music will still play.  The engine will still
be running; even the "working" icon will spin.  The general instability
with the OS and unresponsiveness of the buttons will happen during that
time.

I don't mind reinstalling to test out betas or give you logs.  It's a good
game and I'm willing to help you.

**Comment by 00-Evan** [comment] 2018-01-17 02:38
Okay, I am going to be releasing a beta for 0.6.3 very soon so I'll post again with a link to that. You seem to have root on your device, so you should be able to backup/restore shattered's app data to keep your progress intact. You could use an app like titanium backup, or just copy/paste from /data/data/com.shatteredpixel.shatteredpixeldungeon/files/

**Comment by B00daW** [comment] 2018-01-17 03:09
Right. Sounds good.

**Comment by 00-Evan** [comment] 2018-01-25 01:04
Sorry for the delay, here is the latest beta apk. We're on beta-0.6 currently.

[APK.zip](https://github.com/00-Evan/shattered-pixel-dungeon/files/1662205/APK.zip)

**Comment by B00daW** [comment] 2018-01-25 04:20
Thanks.  Currently my HTC Evo 4G (Supersonic) is out of commission.  One of
the USB pins is shorted; making it think bluetooth car mode is enabled;
breaking a lot of functionality.  When the microUSB female connectors come
in the mail I'll get it working again.  I have two HTC Supersonics with the
same issue (broken USB female connector).  I'll install the APK on both of
them when I fix them.

Currently my rig is an Alcatel 4060a.  I'll play with it for a bit.  I also
didn't experience the issue with LineageOS 14 (x86_64) installed in
VirtualBox.

**Comment by 00-Evan** [comment] 2018-02-17 21:20
I'm going to mark this one as resolved for now, feel free to comment if you encounter this again and I'll re-open.

**Closed by 00-Evan** 2018-02-17 21:20 UTC
Labels: Minor

**Comment by B00daW** [comment] 2018-02-17 21:43
Got you. Don't have a working device to replicate it yet.
