### ISSUE TITLE
Odd-dimension enemies have pixel positioning errors

### ISSUE THREAD

**Issue by jimbo1qaz** [00-Evan/shattered-pixel-dungeon#98] opened 2016-06-27 04:25 UTC
Nexus 5X, PureNexus 6.0.1, Shattered 0.4.0

<https://cloud.githubusercontent.com/assets/913957/16368340/3a7d94da-3be2-11e6-8e10-e81b507455bc.png>

There's a vertical line to the left of the bat. Also, vertical lines on the bat are a bit uneven. The lines do not shift while the enemy is frozen.

Let "pixel" = small pixel, and "square" = big colored square.

I think you're trying to center a 15-square-wide bat on a 16-square-grid level. And my zoom is currently 13, an odd number. To center the bat sprite, it's moved half a square off the pixel grid, or (13/2)=6.5 pixels. This causes per-pixel rounding variation and uneven vertical lines.

To fix this issue, all sprites should be aligned to the pixel grid.

**Comment by 00-Evan** [comment] 2016-06-27 05:49
You are correct this is an alignment issue.

The basic idea for the game's mapping of bloated displayed pixels and true pixels is weird, obviously at 13x scaling any xy value that can be expressed as N/13 would work, but sometimes the game doesn't do that and we get what's seen here. Originally the game always aligned to the display pixel(square as you refer to them), which was awful as it meant potentially large inaccuracies as everything was shifted up to zoom/2 pixels too far in one direction.

Amusingly character sprites were never aligned, presumably because this old align functionality caused large problems with them (e.g. bats would be either all the way to the left or right of a tile).

I have better support for aligning now (will force the coords to the nearest N/13 value in your case), so fixing this should be trivial.

**Comment by un-logic** [comment] 2016-06-27 22:38
I suppose that alignment feature is an overkill here, you see [bat sprite](https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/assets/bat.png) has 128×16 dimensions which gives us 8 frames of animation 16×16 each, meanwhile [bat animation](https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/src/com/shatteredpixel/shatteredpixeldungeon/sprites/BatSprite.java) defines frame size as 15×15 (as far as I understand). So it needs to be fixed either in sprite animation description or sprite itself should be edited to 120×50 pixels.
Same with other characters e.g. [monks animation](https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/src/com/shatteredpixel/shatteredpixeldungeon/sprites/MonkSprite.java) states that texture size is 15×14 whereas [sprite](https://raw.githubusercontent.com/00-Evan/shattered-pixel-dungeon/master/assets/monk.png) size is 256×32 that gives strictly 32 16×16 frames.
Of course I can be wrong and that not the cause.

**Comment by 00-Evan** [comment] 2016-07-29 21:19
fixed in commit 026a1a9e2efc54e899ac8f61b9a50990166bbadc

**Closed by 00-Evan** 2016-07-29 21:19 UTC
Labels: Fixed Indev, Quirk
