### ISSUE TITLE
Endless loading

### ISSUE THREAD

**Issue by Heavenly-Potato** [00-Evan/shattered-pixel-dungeon#377] opened 2020-03-26 10:28 UTC
I am on stage 8, whenever I try to decend to stage 9, it endlessly shows the "Decending" screen.
This also happens while trying to fall into floor nine, giving an endless "falling" screen.
This doesn't happen when ascending or decending on the above floors.

**Comment by 00-Evan** [comment] 2020-03-26 17:07
From taking a look at automated bug reports I'm pretty sure I know the cause of this.

The game is trying to place enemies in a room, but persists in trying even if there are no valid locations for the enemy to go. This should be very rare (the entire room would need to be filled with traps, items, and other enemies), but is possible.

I'll get this fixed in 0.8.0, which will go live in another week and a half of so. If you'd like to opt-in to betas, this will be fixed in 0.8.0-beta-5.1, which should release later today.

**Comment by 00-Evan** [comment] 2020-04-16 18:00
Fixed as a part of commit aa263b6f0a4b3884eef57f64d2000f76f6e26398

Relevant changes were in core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/levels/RegularLevel.java

**Closed by 00-Evan** 2020-04-16 18:00 UTC
Labels: Fixed Indev, Minor
