### ISSUE TITLE
Screen corrupted during gameplay

### ISSUE THREAD

**Issue by brarcher** [00-Evan/shattered-pixel-dungeon#208] opened 2017-10-29 17:52 UTC
During a play through some odd behavior was observed. I was playing a rogue on level, and when attacking an enemy the screen flashed, the character was teleported to a different part of the dungeon, and parts of the screen became corrupted. Screenshot:

![screenshot_20171029-133050](https://user-images.githubusercontent.com/5264535/32146560-992c864a-bcaf-11e7-9b35-724a75ae3b19.png)

Looking through the logs at the time nothing stands out to me. However, in case it is helpful, logs are attached: [pixel.log](https://github.com/00-Evan/shattered-pixel-dungeon/files/1425360/pixel.log)

After the screenshot none of the controls on the game worked. I was stuck with the menu loaded (in screenshot) which came on its own, and pressing anywhere was unresponsive. Force quitting the application and reloading it did allow me to continue gameplay from the point where it became corrupted.

Observed on v0.6.1b from F-Droid on a Galaxy S4, LineageOS v14.1 (Android 7.1.2). Have only observed it once.

**Comment by 00-Evan** [comment] 2017-10-29 19:18
Hrm, so before looking into the graphics issue, which could possibly be due to your ROM, let me just determine what was happening in gameplay.

So you attacked an enemy, and that caused you to teleport? Do you think that was part of gameplay, or part of the graphical issue?

**Comment by brarcher** [comment] 2017-10-29 21:42
The sequence of events was:
1) Attacking an enemy
2) Performed an additional strike
3) Screen 'flashed' (not sure what I saw); it looked like the character was somewhere else, but the colors on the screen were distorted.
4) A moment later I was on the home screen; a message was displayed from Android saying that the application had terminated
5) Went through recents to get back to the application
6) The application was in the state as seen in the screenshot
7) Force terminated application and relaunched
8) Character was in the same position in the dungeon as before, and the enemy was dead. In its place was loot that it dropped.

I think that the 'teleporting' and 'screen issue' are related. I do not think the character actually went anywhere (as the resumed game showed the character in the same place).

**Comment by 00-Evan** [comment] 2017-10-29 21:44
hrm, did you have a ring of wealth on you? Just trying to determine if a specific visual effect may have prompted this.

**Comment by brarcher** [comment] 2017-10-29 21:50
The character was a rogue, but I do not recall that I was carrying any special items. The enemy dropped a scroll (maybe it was a thief). Besides that, I'm not sure I recall much more which may be of help. Sorry.

If I see it again, I'll try to report additional details.

**Comment by erikhuizinga** [comment] 2017-11-07 15:50
I've encountered the same issue some time ago on a custom ROM (Paranoid Android v6.0.2) on a previous phone (OnePlus One). Not sure if that was the cause, though. This issue has existed at least for a year and the last time it happened could be about a month ago. Maybe this info helps to find an incompatibility? In the time that I've played SPD (since about when it was released), it has occurred to me about 5 times, so it's very rare.

**Comment by 00-Evan** [comment] 2017-11-07 21:23
Hunting down this issue is tricky as there isn't really much to go on, I do have a hunch though.

Back in version 0.6.0 (the first time this bug was reported) I made a change to Shattered's proguard config, specifically to include optimizations to increase the game's speed and reduce the app size. The gains that making this change provided seem to be minimal (no appreciable change in speed, 10kb smaller APK), but the timing of this error suggests to me that this change may be what has prompted it. Google also specifically warns in this optimized proguard config that it may be unstable and thorough testing is necessary in order to use it.

Given the minimal gain for the potential instability, I'm going to disable these optimizations in 0.6.2b, and we'll see if that improves things.

**Comment by 00-Evan** [comment] 2017-11-18 00:02
I'm calling this one tentatively fixed in commit 41685ce45c16e875155099c205294db0dea44bac, feel free to comment if you experience this again and I'll reopen.

**Closed by 00-Evan** 2017-11-18 00:02 UTC
Labels: Fixed Indev, Minor
