### ISSUE TITLE
feint doesn't always work well

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1360] opened 2023-05-22 02:27 UTC
I wait until the evil eye is charged two turns, then feint.  Sometimes I feint and then still get blasted by the evil eye.  It seems like the evil eye has time to retarget and shoot after I feint but before I get to go again.  Also, if I am hasted, the timing of feint becomes difficult because of the fractional turns.

**Comment by 00-Evan** [comment] 2023-05-22 15:08
I had a few cases of this reported during v2.0's beta, but haven't heard anything from it since. It is intended that eyes can change their target position while charging, but feint should redirect their aggro onto the afterimage. Please send a screenshot or similar if you're able to reproduce this.

As for fractional turns, feint is not affected by haste effects, and will take 1 turn regardless.

**Comment by protective1** [comment] 2023-05-23 23:44
One case when feint fails is when I'm slowed by scorpion stings.  Is that suppose to cause feint to fail (i.e. hero seems to feint but then evil eye retargets me)?

The other case is when there's not enough power left in the armor.  When there's not enough power, the hero instead steps without feinting.  That usually turns out pretty deadly, because it basically guarantees that you'll get hit.  I think that's the most punitive thing in the game that can happen when an item runs out of charge and you try to use it.  Compare this to wands being out of charge, or warrior armor not having enough charge to heroic leap - nothing happens, but you don't lose a turn either. When feint fails, you have no opportunity to try an alternative.
I'll keep watching to see if feint fails for any other reasons.

**Comment by 00-Evan** [comment] 2023-05-24 21:05
If the armor is out of charge it does not attempt to be used, it cancels the action entirely and puts a message in the game log. What's happening is that after that you're tapping a location as if the targeting prompt showed up, which causes you to start walking there normally.

feint's duration is not affected by movement speed either. I did a quick test and am not able to reproduce feint failing to cause eyes to re-target when the hero is crippled. Keep in mind that you have to feint such that the eye attacks within the 1-turn window that you are feinting.

Closing this for now, will be happy to re-open if reproduction steps can be given.

**Closed by 00-Evan** 2023-05-24 21:05 UTC
