### ISSUE TITLE
Better controller support

### ISSUE THREAD

**Issue by GrantMoyer** [00-Evan/shattered-pixel-dungeon#913] opened 2022-02-19 17:27 UTC
Controllers input is somewhat supported, but leaves a lot to be desired. The D-Pad and left analog stick move the character, but only in the cardinal directions, not diagonally. Most buttons do nothing, but there are a few that do something. Using a PS4 controller for reference, □ and ○ both open and close the pause menu, △ waits, and SHARE opens the inventory (although it cannot be interacted with except closed by □ or ○). The touch pad does function as a mouse, but it's not very wieldy, and most controllers don't have a touch pad. The rest of the buttons do nothing. Some useful controls would include:

- Ability to navigating menus
- Ability to switch between inventory pages
- Ability to move diagonally
- Panning camera with right analog stick
- Button mappings for on screen action buttons like pick up item, attack enemy, and continue interrupted movement
- Button mapping for search and inspect
- Button mappings for quickslot items
- Button to open journal

One potential controller scheme might be:

- D-Pad: quick slots
- Left analog stick: move player
- Right analog stick: pan camera
- ⨯: pick up item, confirm in menu or dialog box
- ○: search/inspect, cancel in menu or dialog box
- □: open/close inventory
- △: wait
- SHARE/select: open/close journal
- OPTIONS/start: open/close pause menu
- L1: switch inventory/journal page left
- R1: switch inventory/journal page right
- L2: continue movement action
- R2: attack action
- L3 (left stick click): start selecting a tile to pathfind to
- R3 (right stick click): change zoom level

**Comment by 00-Evan** [comment] 2022-02-19 17:31
You might be interested in the latest demo version of the game on steam, which includes the first attempt at real controller support. The game has not had any proper controller support before this demo version which was just released. In the future I'll likely improve controller support with things such as radial menus for quickslots.

The improvements in that dmeo update will be includes in open source versions once 1.2.0 releases.

**Comment by GrantMoyer** [comment] 2022-02-19 17:35
I should have mentioned I was talking about Android. Hopefully it's somewhat trivial to adapt desktop controller support to also Android's controller API.

**Comment by 00-Evan** [comment] 2022-02-19 17:37
I haven't actually tested these improvements on other platforms yet, but I do intend to have this new controller support work on all platforms. The only functionality that might need significant adaptation is the demo's "move mouse pointer with right stick" functionality, which will likely need a custom virtual pointer to work on iOS/Android.

**Comment by GrantMoyer** [comment] 2022-02-19 18:02
Android does natively support mice, but I'm not sure if the cursor can be controlled by an app.

I tried the controller scheme in the stea demo and have some feedback:

- Using both the D-Pad and analog stick for movement eats up valuable button mappings. I think the analog stick is the better option here, since moving diagonally with the D-Pad felt pretty unreliable.
- Waiting with L3 (left stick click) seems like it might be too easy to accidentally move, although i didn't play long enough to see if this is a problem in practice. It's also more strenuous than a normal button press to wait multiple times.
- Having to hold R3 (right stick click) to pan the camera make precise movements difficult. Also the inverted panning controls feel wrong to me, but that's personal preference.
- I wasn't able to move the cursor with the right stick controller under wayland on linux. I'll try on windows and see if I have more feedback.

**Comment by 00-Evan** [comment] 2022-02-19 18:08
Thanks for the feedback, but right now I'd prefer if it was concentrated on the Steam forums as the Steam demo is only released there. Most of your points can be addressed simply by saying the game does support custom button mappings from the settings menu. I wasn't too concerned about buttom economy for now as handling that properly is going to need a few radial menus for things like quickslots, which was out of the scope of this initial basic controller support implementation.

**Comment by 00-Evan** [comment] 2022-02-22 19:50
Closing this as a duplicate of #571

**Closed by 00-Evan** 2022-02-22 19:50 UTC
