### ISSUE TITLE
Swift Equipped Weapons Don't Upgrade

### ISSUE THREAD

**Issue by ReallyBasicGames** [00-Evan/shattered-pixel-dungeon#1226] opened 2023-02-09 18:43 UTC
When attempting to use the Swift Equip (+1) it allows the user to switch to a weapon, but when I attempt to upgrade it it consumes the scroll but doesn't upgrade the weapon.  I was not currently the Champion yet, but the inventory behaved like I was, where the primary weapon automatically became my secondary, and I could still use it's ability. After the Swift Equip cooldown, the next time I used my original weapon auto-switched it back to my primary.  It should also be noted that while the swift-equipped weapon was equipped, I was unable to open it's description window. 

However, later in the game when I had become the subclass Champion, the game worked as expected and scrolls of upgrade worked on both.

2.0.0-BETA-V1 through desktop jar

**Comment by 00-Evan** [comment] 2023-02-09 22:18
I'm not able to reproduce either scrolls of upgrade not working, or swift equip placing items in the secondary slot without the champion subclass. Is there any more info you can provide?

Was the weapon you were trying to equip unidentified? That would explain why upgrades were not appearing on it when the scroll was used.

**Comment by ReallyBasicGames** [comment] 2023-02-10 00:12
The weapon I tried to equip was unidentified, though upon being equipped the tier 1 identify talent immediately identified it.

**Comment by 00-Evan** [comment] 2023-02-10 18:30
Found the source of this, it's unrelated to swift equip. Will be fixed soon in beta-2

**Comment by 00-Evan** [comment] 2023-02-10 19:34
Fixed in BETA-2

**Closed by 00-Evan** 2023-02-10 19:34 UTC
