### ISSUE TITLE
Sad Ghost ignoring enemy

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#691] opened 2021-05-09 04:09 UTC
Directed the sad ghost to stand next to a door that an enemy (mimic) was coming through.  After the mimic came through the door, the ghost ignored us while I fought the enemy.  Why didn't the ghost automatically start attacking the mimic?
![Screenshot_20210508-190612](https://user-images.githubusercontent.com/8593007/117560300-a06d6080-b05a-11eb-8e23-3dd20c90b305.jpg)

**Comment by 00-Evan** [comment] 2021-05-09 04:29
Looks like this is caused by the sad ghost being asked to move to a location they cannot reach. In this case you probably tapped on a wall tile adjacent to the floor. This causes the ghost to be stuck in a 'moving to defend' AI state, where they don't attack enemies. I'll add a check to prevent this.

**Comment by 00-Evan** [comment] 2021-06-07 17:03
fixed in commit 2f69b7b51b246ffc7bef0b3c2dbbed559f5f3368

**Closed by 00-Evan** 2021-06-07 17:03 UTC
Labels: Fixed in BETA, Minor Bug
