### ISSUE TITLE
Corrupted pirania swaps place with player on land and dies

### ISSUE THREAD

**Issue by Kaligule** [00-Evan/shattered-pixel-dungeon#522] opened 2020-10-16 09:03 UTC
Given a plazer on land and a corrupted pirania in the water. If the player clicks on the pirania, it will swap places with the player (as any friendly npc will). This leads to the fish beinging on land and dieing.

I think would make more sense for the fish to swimm away instead of dying.

**Comment by 00-Evan** [comment] 2020-10-17 17:05
Partial duplicate of #374

**Closed by 00-Evan** 2020-10-17 17:05 UTC
