### ISSUE TITLE
Pathing bug with fire trap rooms

### ISSUE THREAD

**Issue by muleyryan** [00-Evan/shattered-pixel-dungeon#141] opened 2016-11-12 01:41 UTC
In 0.4.3c, setting a waypoint through a fire-trapped room with an identified safe path does not guarantee that character will take it; my character just took the wrong path twice!

**Comment by 00-Evan** [comment] 2016-11-12 02:04
hmm, can you give some more details please, I'm not able to reproduce this. Screen shots or a mockup of the layout of fire traps would be very helpful.

**Comment by 00-Evan** [comment] 2016-11-21 20:51
I've closed this issue as there has been no reply. If you want to pursue this further feel free to comment and i'll re-open.

**Closed by 00-Evan** 2016-11-21 20:51 UTC
