### ISSUE TITLE
crashed 

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1141] opened 2022-10-30 22:17 UTC
The screen suddenly froze when shooting a wraith that appeared  (bone dust curse).
![Screenshot_20221030-181327](https://user-images.githubusercontent.com/8593007/198904111-e232aa09-4eb9-4c16-8acd-bedb09508f47.png)

I reopened the app and I'm back to level start:
![Screenshot_20221030-181639](https://user-images.githubusercontent.com/8593007/198904208-ccbc715d-d536-44df-b9d3-0e3208bd9488.png)

Also, the wraiths seen to appear really frequently with this curse.  Was it always that way?  That part is not a bug, just an observation.

**Comment by LeahLuong** [comment] 2022-10-31 01:36
I believe that's typical behavior unless the app is able to see the close coming (e.g., running low on battery & shutting down to conserve power). Saving game state happens during depth changes or when manually closing the app & it looks like you experienced an unforeseen crash. I doubt it was the wraith's fault but I don't think there's enough info here to determine the cause. I experienced a crash earlier today simply walking to the corner of a room w/ no mobs around. It's rare the game fails like that (for me) but seems to happen randomly from time to time. I, too, lost some progress on that depth as a result.

As for bone piles, I welcome the wraiths. It's free info on whether the item is cursed or not. Bone piles are just random containers like chests & can contain most of the items placed by levelgen.

**Comment by protective1** [comment] 2022-10-31 02:18
Usually when apps crash, they exit.  In this case, the game just froze with the above image on the screen.
So maybe crash is not the right description - maybe it was an infinite loop?

@LeahLuong  - Just to be clear in case there's any ambiguity in my description, the wraiths were not from bone piles.

**Comment by 00-Evan** [comment] 2022-10-31 18:25
This does sound like a freeze more than a crash. Unfortunately as mentioned there's nothing for me to really go on here. The issue is also likely a once-off. I'm closing this for now, but if you run into this with any consistency please reply and I'll re-open the issue.

**Closed by 00-Evan** 2022-10-31 18:25 UTC
