### ISSUE TITLE
Enemies can't trigger hidden traps and when spawned on them don't trigger them.

### ISSUE THREAD

**Issue by Howdidibreakit** [00-Evan/shattered-pixel-dungeon#1319] opened 2023-04-19 15:57 UTC
![image](https://user-images.githubusercontent.com/118551559/233132482-df13c316-d338-451b-a93a-55f597f9ef7e.png)
Here, a gnoll brute is sleeping on a gripping trap, and, in those explosive rooms, enemies will often walk right through a trapped tile. The only way an enemy can trigger a trap is if they have vertigo, or you knock them back into one.

**Comment by 00-Evan** [comment] 2023-04-19 16:24
This is intended, also a duplicate of #1143, #1027, and several other reports.

**Closed by 00-Evan** 2023-04-19 16:24 UTC
