### ISSUE TITLE
v0.2.4 breaks back button

### ISSUE THREAD

**Issue by squigish** [00-Evan/shattered-pixel-dungeon#27] opened 2015-02-24 20:57 UTC
The back button no longer does anything after updating to 0.2.4. The hardware menu button (which is on some older devices, like the galaxy S3) may also be affected. I'm not sure because I haven't updated my phone yet, only my tablet (Experia Z2 Tablet).

I was hoping that your source release would happen at the same time as the play store update, (if not before), so that I could see what exactly changed. Why not push commits to github as you make them?

**Comment by 00-Evan** [comment] 2015-02-24 21:02
Part of adding donation features meant moving to private VCS, as they won't be included in the open source. In addition to that, it was also a protective measure, as some derivative projects (who did not ask permission) were implementing new shattered features as they hit VCS, but before they actually made it to an update. I have every intention of releasing the source, but want to move to a slightly more delayed schedule. I do intend to bring the changes in commit - by - commit though, so a full history will still be available.

I'm not able to reproduce your issue though, both hardware, software, and ingame buttons are working fine. Does restarting your device help at all?

**Comment by squigish** [comment] 2015-02-24 22:43
Rebooting the device fixed the issue. Weird.

**Comment by 00-Evan** [comment] 2015-02-25 14:23
I am actually able to reproduce this issue, rapidly tapping to enter and leave the app from the title menu can cause this unresponsive button behaviour, and may also cause a crash with a NullPointerException. This seems to also happen without rapid tapping, but much less frequently. This seems to be a source issue, I'll investigate

**Comment by 00-Evan** [comment] 2015-03-10 00:21
I've not been able to reproduce this further so i'm going to mark this as fixed, some changes made to pd-classes back in 0.2.4a likely corrected this issue indirectly.

**Closed by 00-Evan** 2015-03-10 00:21 UTC
Labels: Minor
