### ISSUE TITLE
X-ray Vision

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1132] opened 2022-10-26 23:41 UTC
![Screenshot_20221026-100806](https://user-images.githubusercontent.com/91638992/198158342-21512adc-f6d6-451c-b5b9-88fc43756592.png)

This is similar to #168 but seems deserving of its own bug report. As shown above, the room south of the 1 the hero is in is detectable once the bookshelves have burned away.

Ordinarily, only a small portion of a corner tile would be visible when the unexplored room is south of the hero; not sure if that's intended behavior & I can try finding an example if you'd like.

**Comment by 00-Evan** [comment] 2022-10-27 05:59
That's unrelated to #168 and definitely unintended. Best thing would be for me to reproduce the run and test this, which daily was this seen on?

**Comment by 00-Evan** [comment] 2022-10-27 17:01
Nevermind, found a seed to reproduce on my own.

**Comment by 00-Evan** [comment] 2022-10-28 18:24
fixed in commit e4bb55791161e3490a490a690a7f414edf798670

**Closed by 00-Evan** 2022-10-28 18:24 UTC
Labels: Quirk, Fixed in development
