### ISSUE TITLE
Enhancement: integration with Google Play Game Services

### ISSUE THREAD

**Issue by anddgn** [00-Evan/shattered-pixel-dungeon#61] opened 2015-09-04 10:36 UTC
Any plan on doing that? It's in Pixel Dungeon: https://github.com/watabou/pixel-dungeon/issues/9

It would be nice to be able to sync saves, badges, have achievements for badges, be able to compete with friends, get play games xp, get it to show up in the Google Play Games app, etc.

Many people would enjoy it and it also helps other people discovering the game and getting more involved...

**Comment by 00-Evan** [comment] 2015-09-05 23:44
This is definitely something I want to do at some point but there are lots of questions and dangling details that need to be addressed.

Some simple like syncing badge completion will likely be easy, and probably where it'll start with this though.

**Comment by 00-Evan** [comment] 2015-10-30 21:55
This is now planned to be implemented in 0.3.3

**Comment by 00-Evan** [comment] 2015-12-01 23:13
Good news! This feature is now working in the latest shattered beta. You can sign up for shattered betas here: https://play.google.com/apps/testing/com.shatteredpixel.shatteredpixeldungeon

The update should fully distribute on the beta channel over the next hour or two.

Let me know what you think.

**Comment by ndossougbete** [comment] 2015-12-02 08:59
Hello! I just tried quickly, here is what I noticed :

- I get prompted to select an account every time I get to the main menu. This might be related to the fact that I have 2 google accounts on my phone. 

- Shattered Pixel Dungeon doesn't show up in my list of recently played games in the Google Play Games app. 

- I didn't get any achievement based on the badges I already have. The description in app mentions them, and but maybe they are not in this update. 

- I like that what you are doing with the data is explained, and that we can review it beforehand. I'll have to check out the code. 

- I didn't try on another device to see what data is restored. I will do later today. 

It looks good, thanks for working on that!

**Comment by ndossougbete** [comment] 2015-12-02 15:20
After checking on my tablet:

- The first point, being prompted every time, is very annoying. I also don't know what account I'm signed in with. Maybe it should be displayed somewhere that I'm signed in with a given username?

- My badges didn't get restored on my second device

- I was intrigued by the permission asking access to my Drive to store data. I suppose it is related to saving badge data. I tried to locate this data in my Drive but didn't find anything. Maybe this is hidden, or data upload failed.

- Wouldn't it be possible to map badges to achievements and use that data to restore badges, instead of getting some Drive storage? Subclass unlock could be done that way too. But if you want to save the complete leaderboards that probably won't work. I don't know if Play Games supports leaderboards as detailed as the ones in PD.

**Comment by 00-Evan** [comment] 2015-12-02 19:52
@ndossougbete Hmm, let me go over your points here.

Firstly, the app should only ever annoy you when it encounters a problem with connecting that requires your help to resolve, after you have already told it you want to be connected. I you ever cancel one of those dialogues, Shattered 'should' recognize that and stop bothering you until you manually try to connect again, though as far as I'm aware that's a bit buggy atm.

You'll know you're connected properly once the controller icon turns green, it seems like you're encountering some connection issues as your badges aren't syncing and achievements aren't unlocking. I'll look into getting two accounts on one of my devices and test based on that.

You may not see some info relating to Shattered yet in google play games, this could be caused by it not connecting properly, or be due to these features still being in beta.

Shattered uses your drive data space to store its sync data, this is a very small amount of space and (as far as I know) isn't visible from your google drive page, you can manage this space through google play games. Google is pretty rigid about achievements (once one is made it can never be deleted) and I would rather have more control than that, so for now I am not mapping badges to achievements 1:1. Even in the future I'll probably only have achievements for the more significant badges which i'm certain I won't change.

Rankings sync is definitely going to happen in the future, likely based on your drive data (again, if you're concerned about storage space I doubt this will ever exceed a couple of megs). However google play leaderboards might be more complicated, especially given that I have no way to preventing users from cheating, and the current way runs are scored isn't very conducive to competition.

**Comment by ndossougbete** [comment] 2015-12-02 20:33
Ah thanks, this explains a lot. I never got the green icon. Looking at logcat:

```
E/GameAgent: Unable to retrieve application 162079574763 from network
E/GameAgent: Application ID 162079574763 is not associated with package com.shatteredpixel.shatteredpixeldungeon. Check the application ID in your manifest.
E/CheckGameplayAcl: Unable to load metadata for game
W/SignInActivity: onSignInFailed()...
W/SignInActivity: ==> Returning non-OK result: 10002
```

**Comment by 00-Evan** [comment] 2015-12-02 20:36
Hmm, that is very interesting, that ID is correct. Are you signed up for shattered betas on the same account you're trying to connect to google play games on?

**Comment by ndossougbete** [comment] 2015-12-02 20:50
/facepalm that's what was missing, thanks.

Most of my issues are then addressed.

- The icon color expresses the sign in status 
- I could see my existing badges transferred
- My class mastery info has been transferred
- I retroactively unlocked achievements
- Shattered is shown in "Recently played" in the Games app, but it doesn't list achievements. So aside from when I get the "Achievement unlocked" popup, I don't know how to list them. Maybe another thing related to the Beta state?

Looks awesome overall, thanks a lot!

**Comment by 00-Evan** [comment] 2015-12-02 20:51
Glad it's working for you now!

Achievements not showing is directly related to the beta status, once all of this moves to live achievements and your save data (don't mess with that if you want to keep your badges =P) should display properly.

**Comment by 00-Evan** [comment] 2015-12-18 19:12
0.3.3 is about to go live. As there will be no source release relating to these features, I'm closing this ticket now. Feel free to comment if you run into any issues.

Google Play Games integration will not be part of the source as it adds extra permissions, significantly complicates the build process, increases the install size, and is ultimately useless for most fork projects anyway. I really like that Shattered's open-source code can just be dropped into a folder and built with almost no configuration needed, I want to preserve that.

If anyone wants to implement these features in their fork they're welcome to contact me for advice.

**Closed by 00-Evan** 2015-12-18 19:12 UTC
Labels: Enhancement

**Comment by SecT0uch** [comment] 2019-02-19 13:56
Pages of the book, recipes aren't synchronize. Is it the normal behaviour?
