### ISSUE TITLE
graphical glitches with the perspective update

### ISSUE THREAD

**Issue by brunal** [00-Evan/shattered-pixel-dungeon#161] opened 2017-02-26 15:41 UTC
1. Head cut when going up to a boss floor, or levitating in certain conditions

![screenshot_20170109-004400](https://cloud.githubusercontent.com/assets/921168/23341081/2c6713ea-fc39-11e6-9ab2-a4643eae56c9.png)
![screenshot_20170222-184804](https://cloud.githubusercontent.com/assets/921168/23341080/2c66e19a-fc39-11e6-8d46-3b6b74874f6d.png)

2. Unclear pathing

![screenshot_20170219-195311](https://cloud.githubusercontent.com/assets/921168/23341079/2c657e7c-fc39-11e6-8d10-db28c843a105.png)

It's not obvious the trap will be avoided.

3. invisible things

Put lots of meat on a tile and throw a seed on it; the plant won't be visible

4. Bonus: inivisible, clickable status modifiers with incorrect values
![screenshot_20170126-132244](https://cloud.githubusercontent.com/assets/921168/23341078/2c65783c-fc39-11e6-98bb-9e2e7c878670.png)

**Comment by benzarr410** [comment] 2017-02-28 12:12
Can Repro all 4 on mobile, and the first 3 on desktop

**Comment by 00-Evan** [comment] 2017-03-01 11:09
1: this is a known issue and not something I intend to fix directly. I'm going to be moving away from this sort of boss exit visual soon so that will incidentally correct it.

2: The current coding for grass is.. not great, that's how things look when they're inside of grass and haven't trampled it. In the short term I've made grass trample in most cases, more long term I want to make it look less awful, but that also requires more work to the rendering code.

3: I'm not able to reproduce this. The plant is being most obscured by the item, but it is still rendering.

4: I thought I had fixed in 0.5.0, I'm not currently able to reproduce it, can you give steps?

**Comment by benzarr410** [comment] 2017-03-01 13:21
Repro Steps for 4

1. Have a status effect, and not be hungry/starving.
2. Lose said effect.
3. Tap/Click where the status effect icon *was*.
4. It should reopen the effect dialog with a negative number for the turns left value.

**Comment by 00-Evan** [comment] 2017-03-01 18:44
Those are the exact steps I've attempted, both on desktop and mobile. Those are also the steps I used when I attempted a fix for this in 0.5.0.

Could you let me know what version of the game you're running, and what device you're using?

**Comment by benzarr410** [comment] 2017-03-02 13:57
I'm running 0.5.0b, on an RCA Voyager 2 tablet

**Comment by 00-Evan** [comment] 2017-03-05 01:54
hmm, I'm really not sure how this is able to still happen. I'm not able to reproduce it and the logic change I made forces the touch listener to be destroyed when the buff icon is removed.

**Comment by brunal** [comment] 2017-03-10 17:58
4th may have been taken before 0.50 (or during 0.50 beta)

For (2) I'm not sure how diagonal movement is absurd....

**Comment by 00-Evan** [comment] 2017-03-13 22:22
Diagonal movement is absurd when there are walls present because the character is technically moving through an impossibly tight space between two wall tiles. Nevertheless it is possible.

I'm closing this as I've addressed all the points presented, if you want to pursue any of these points further please feel free to make a new issue for that point.

**Closed by 00-Evan** 2017-03-13 22:22 UTC
