### ISSUE TITLE
Throwing earthroot infused blandfruit throws potion of paralysis instead

### ISSUE THREAD

**Issue by Draika** [00-Evan/shattered-pixel-dungeon#268] opened 2018-10-10 13:21 UTC
v0.6.5c

I've had this bug happen twice to me now, while trying to toss this item for space to pick another up. The thrown item visually is the same as the paralysis potion and behaves the same, shattering and filling the room with paralytic gas.

Whenever this happens I always happen to have a potion bandolier with a paralysis potion in it, which possibly seems to get identified after the bug occurs because I normally try to not mess with potions I don't need after discovering the healing and strength ones.

(Probably completely unrelated but in both instances I was on floor 14 with velvet pouch. Maybe I should just pick up a merchant beacon in my runs so I don't have to do as much inventory management haha)

**Comment by 00-Evan** [comment] 2018-10-12 20:16
the breaking as if it were a paralysis potion is correct functionality for earthfruit, though the other bits are of course unintended.

Blandfruit is actually getting significantly redesigned in the next update, so this will likely be fixed incidentally.

**Comment by 00-Evan** [comment] 2018-10-24 07:45
closing this as 0.7.0 has been released. Let me know if you're still able to reproduce it.

**Closed by 00-Evan** 2018-10-24 07:45 UTC
Labels: Fixed Indev, Quirk
