### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1162] opened 2022-11-15 19:22 UTC
I cast to gnoll shaman with +0 wand of fireblast ,in the sametime，the spell kill shopkeeper 
the red line is the track of fire 
I dont good at english,sorry
![IMG_20221116_023822](https://user-images.githubusercontent.com/118305192/202005598-5330d006-25df-4828-9fec-4d381fda4549.jpg)
![Screenshot_20221116_032100_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/118305192/202007064-946e1825-dac5-4226-bdf6-1ae16cfab83a.jpg)

**Comment by 00-Evan** [comment] 2022-11-15 19:48
It seems more likely to me that some other effect caused the shop keeper to run away. Where did you shoot that wand of corrosion? If it was in the doorway, then the gas probably reached the shopkeeper.

**Comment by LeahLuong** [comment] 2022-11-15 19:53
Your English is good enough but more impressive is beating Tengu in a 9-challenge run. Are you playing a known good seed for huntress??

I think fireblast was changed in a semi-recent patch. I've noticed it now projects a missile which goes past the initial cone of fire until it collides w/ a wall. This missile doesn't start fires but is capable of burning plants & grass it crosses & is, apparently, capable of dmg'ing entities in its path.

**Comment by 00-Evan** [comment] 2022-11-15 19:59
Those screenshots are not from Shattered Pixel Dungeon. Please don't report bugs which appear in other versions of Pixel Dungeon.

I tested this in Shattered Pixel Dungeon and was able to reproduce the problem when shooting fireblast through a closed door.

**Comment by Lyx0527** [comment] 2022-11-15 20:51
I barely communicate with translation software
This is a random seed, but I'm lucky
This module version made by a Chinese player.It only adds a few test functions，I'm just trying to get feedback as soon as possible
Many Chinese players love SPD very much. We try to challenge more possibilities.Some players can even pass 9 challanges without using strength potion or upgrade scroll.
I'm glad to help improve this game
![Screenshot_20221116_040045_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/118305192/202022813-5099280f-e4b4-4c0f-8122-3cf751ddd040.jpg)

**Comment by 1015561267** [comment] 2022-11-16 02:51
I think I may save you some time though.
![image](https://user-images.githubusercontent.com/52144800/202070646-814e2131-bcbe-43e1-a29a-25e582ec14bf.png)
Here,Ballistica,I noticed that you add so-called ignoreSoftSolid,and you use if-else instead of || in old versions.
Let's assume a condition:one cell on the path meet both "cell is a closed door" and "cell == to",and you can see what happened.For fire wand it would see if it meets terrain feature first,and if it meets,dismiss target judgement.And for other cells,now that they are not target cell and dismiss chars,they could only stop because of true solid terrain(Wall)
That explains why you use it four tiles away from a closed door would cause this bug,as door is the 5th block and fire wand happen to have 5 dist when uses one charge.
Althogh I'm still thinking about why it could also happen when 3 tiles away from a door,may be later I could come up a idea,or you could find it out

**Comment by 1015561267** [comment] 2022-11-16 06:07
> I think I may save you some time though. ![image](https://user-images.githubusercontent.com/52144800/202070646-814e2131-bcbe-43e1-a29a-25e582ec14bf.png) Here,Ballistica,I noticed that you add so-called ignoreSoftSolid,and you use if-else instead of || in old versions. Let's assume a condition:one cell on the path meet both "cell is a closed door" and "cell == to",and you can see what happened.For fire wand it would see if it meets terrain feature first,and if it meets,dismiss target judgement.And for other cells,now that they are not target cell and dismiss chars,they could only stop because of true solid terrain(Wall) That explains why you use it four tiles away from a closed door would cause this bug,as door is the 5th block and fire wand happen to have 5 dist when uses one charge. Althogh I'm still thinking about why it could also happen when 3 tiles away from a door,may be later I could come up a idea,or you could find it out
@00-Evan

**Comment by 00-Evan** [comment] 2022-11-16 14:57
@1015561267 the bug has already been fixed in development, and I don't accept code contributions.

**Comment by 00-Evan** [comment] 2023-03-13 17:22
fixed in commit 56f34f9c760205575e7444f9f1936b150025a7c1

**Closed by 00-Evan** 2023-03-13 17:22 UTC
Labels: Minor Bug, Fixed in BETA
