### ISSUE TITLE
ambitious imp doesn't appear in journal if you're fast

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#559] opened 2020-12-11 04:02 UTC
I defeated the dwarf king and the ambitious imp disappeared from my journal, when though I could go back and complete the quest.

**Comment by joshtriplett** [comment] 2020-12-11 08:59
By design, the ambitious imp's quest must be completed before you reach where his shop would be; that isn't a bug.

**Comment by protective1** [comment] 2020-12-11 13:21
According to the changelog, that limitation was removed in 0.60:  "Visiting floor 21 before completing the imp quest no longer prevents his shop from spawning".  Also I didn't go to floor 21 - I went back to do the imp quest when I saw that the shop was missing.
Either way I was still able to do the quest.  It was just harder because I couldn't remember what floor the imp was on and it was no longer in the notes.

**Comment by 00-Evan** [comment] 2020-12-11 16:31
There is no code that affect's the presence of the imp's quest in the journal outside of the imp itself. When the player first sees the imp, they are added to the journal, and they are removed when the quest is completed. Dwarf king has no affect on this.

**Comment by protective1** [comment] 2020-12-11 16:35
I'm not sure that it was in the log before the dwarf king.  I just went to look for it after the dwarf king and it wasn't in the log.  However, I had already spoken to the imp and was already collecting dwarf tokens.  I wish I had taken a screenshot of the log but didn't think of it at the time.

**Comment by protective1** [comment] 2020-12-11 16:43
Is it possible that somehow "Imp.interact" got triggered but "Imp.act" did not?

**Comment by 00-Evan** [comment] 2020-12-11 17:18
> 
> 
> Is it possible that somehow "Imp.interact" got triggered but "Imp.act" did not?

This would only be possible if the hero was moving at high speed, such that the imp didn't have a chance to act in the time that they entered its view, interacted with it, and left.

**Comment by protective1** [comment] 2020-12-11 18:06
Will the imp act if you are invisible?

**Comment by 00-Evan** [comment] 2020-12-11 20:10
The imp checks if he is within your field of vision, not the other way around, so no.

**Comment by protective1** [comment] 2020-12-11 21:54
I was using "Into darkness" challenge, so I was probably in the dark when I first spoke to him.  I think I was also running (freerunner) from monsters.  So I supposed it is possible I spoke to him without him having a chance to act.

**Comment by protective1** [comment] 2020-12-14 07:49
I did it again as a confirmation - spoke to imp without him appearing in the log.  Again I'm playing a freerunner, this time with ring of haste.

**Comment by 00-Evan** [comment] 2020-12-14 18:57
Yep, I was planning on correcting this in v0.9.1a anyway, but I'll keep the issue open to track it now that the actual problem is identified.

**Comment by 00-Evan** [comment] 2020-12-17 17:32
Fixed in commit 6ca2d6bc6b79ea5e0b84e7b915a9b24975e1508c

**Closed by 00-Evan** 2020-12-17 17:32 UTC
Labels: Fixed Indev, Quirk
