### ISSUE TITLE
Initial graphic bug

### ISSUE THREAD

**Issue by fapkamaster** [00-Evan/shattered-pixel-dungeon#324] opened 2019-06-08 12:37 UTC
Version: 0.7.5.
I saw updated wanted to read changes and weird graphics happened when I opened game 2nd time.

Check this screenshot from my phone.
This could be related to Google Play Games (lack of them on Android Phone). ![Screenshot_20190602-053332](https://user-images.githubusercontent.com/31676418/59147358-a84da180-89fa-11e9-8c9c-cc46c3625a7b.png)

**Comment by 00-Evan** [comment] 2019-06-08 17:44
Currently the latest version of shattered is v0.7.3b

This is likely a device-specific issue, as it looks like your texture mapping is all screwy. It is unlikely to be caused by a lack of play games. Unless you can provide more specific info there isn't really much I can do about this.

**Comment by fapkamaster** [comment] 2019-06-09 20:17
Oh yeah, my mistake about version.
So, I think I reminded myself how it happened.
There was a game launch, then popup appeared with "Install Google Play Games" (and that it is "needed" for the game).
Popup got closed and then the graphics got "distorted" like you can see here. 

I highly doubt it is specific for device - it never happened for me before, but only variable that I got recently is that Google Play Games popup...

**Comment by 00-Evan** [comment] 2019-06-11 17:53
Hmm, might be something relating to part of the app being pushed out of memory because of that notification. Either way the game shouldn't be nagging you about google play games in the title screen like that unless you enabled it previously, the game very specifically never tries to invoke play games logic unless you tell it to first.

**Comment by 00-Evan** [comment] 2019-08-23 19:07
I'm closing this issue as the error can't be reproduced. Additionally I made some tweaks to google play games logic recently which should significantly reduce the number of times it nags the user if it was previously enabled and then the app was uninstalled.

**Closed by 00-Evan** 2019-08-23 19:07 UTC
