### ISSUE TITLE
Go-to-tile doesn't stop while gnoll shaman is out of sight

### ISSUE THREAD

**Issue by BerberBerthold** [00-Evan/shattered-pixel-dungeon#272] opened 2018-10-24 08:52 UTC
I tapped on a tile of a room that I wasn't inside of.  The game made me go towards that tile, and then I got hit by a lightning bolt of a gnoll shaman (presumably) that was out of sight.  My character didn't stop moving towards the tile, though (probably because the enemy was out of sight), and I got hit about two more times and it was too late for me to stop the character from moving.  Usually stuff like this only happens when I tap on a (non-adjacent) tile while the enemy is on screen.

I assume this is not intended, as a lot of other (more minor) things stop the character from moving.  The game also stops the character from moving when a not-in-sight enemy becomes in sight.

**Comment by TheYsconator** [comment] 2018-10-24 12:54
Has this issue been resolved? Can you explain why you closed it?

**Comment by BerberBerthold** [comment] 2018-10-24 13:01
sorry maybe i shouldn't have closed it.  i felt that i should have first asked on reddit or so before posting here.  usually minor things like this don't feel like they deserve an issue, i planned on reopening if i can reproduce it or if the community on reddit say have experienced this as well.

**Comment by 00-Evan** [comment] 2018-12-16 14:52
I just ran a few tests and am not able to reproduce this. When walking with a ranged enemy out of vision, taking a hit from them stops hero motion, as intended.

Did you use the 'continue moving' indicator to initiate the walking action? If so then that is also working as intended, as tapping that indicator causes the game the assume you want to override interruptions and keep moving.

**Comment by BerberBerthold** [comment] 2018-12-16 15:01
I have had others on reddit also confirm this behaviour, but we all recalled such instances from memory, not by testing.  In hindsight, you are probably right, it was due to pressing the keep moving button, I haven't thought of that.

But it still doesn't seem quite right:  I might press the keep moving button because an enemy is on screen sleeping, but not in my way.  Then, in a new room, "keep moving" shouldn't override interruptions from new enemies, right?  When I press the keep moving button, it also stops me from moving when there are new enemies on screen (or even when the same enemy reappears, IIRC).  Apparently, it didn't do this with damage dealt from an enemy off-screen.

**Comment by 00-Evan** [comment] 2018-12-16 15:03
Keep moving essentially means "ignore any possible interrupts (except for me giving new input) until your reach your original destination". That does mean that if you are moving a long distance, that going through into another room and getting attacked will not interrupt you.

**Comment by BerberBerthold** [comment] 2018-12-16 15:15
> Keep moving essentially means "ignore any possible interrupts (except for me giving new input) until your reach your original destination"
I just tested this (in 0.7.0, though), the behaviour is not quite as you describe it.

When I press "continue moving" while an enemy is on screen, if it gets out of sight, and then reappears, it _will_ interrupt the movement.

I would like the behaviour to stay this way, but also have it interrupt if a not-in-sight enemy attacks you.

**Comment by 00-Evan** [comment] 2018-12-16 15:19
Just checked the code, yeah I was slightly wrong, foggy memory of older functionality.

Damage will no longer interrupt you if you choose to continue moving. The primary reason for this is so that you can keep moving through DOT effects. Other interrupt sources (enemies coming into view primarily) will still interrupt you.

**Comment by 00-Evan** [comment] 2018-12-16 15:30
I agree that the 'continue moving' button isn't really very useful. As far as I'm aware the primary case where people use it is when moving between floors, so that they don't have to move the camera around back to the stairs again.

I think it makes most sense to re-evaluate its functionality and existence in general, but that's something I may save for a larger UI change (which is something I'm considering given the possibility of a desktop release, and phones shifting to 18:9 aspect ratios).

I'm going to close this, as I don't intend to spend time evaluating the continue indicator on its own, given that (as I said) I'm planning on considering larger UI changes regardless.

**Closed by 00-Evan** 2018-12-16 15:30 UTC
