### ISSUE TITLE
vertical line video glitch

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#485] opened 2020-08-29 13:12 UTC
Sometimes when I'm walking in the last levels of the game a vertical line will briefly appear across the screen.  This seems most likely to happen between steps when I'm moving right on the final boss stage.  The glitch appears and then immediately disappears.

**Comment by 00-Evan** [comment] 2020-08-29 14:45
This is likely due to graphical alignment issues. Can you tell me your device model (or screen resolution if you're on a computer) and what zoom you usually play at? A screenshot would be most helpful.

**Comment by protective1** [comment] 2020-08-29 16:49
Pixel 3a, default zoom.  This glitch never happened until recently, but I also just got the screen replaced.  However I have not seen glitches in any other program.  I can't take a screenshot because the glitch only happens between steps - it doesn't stay on the screen.

**Comment by 00-Evan** [comment] 2020-08-30 16:01
Just a regular gameplay screenshot at the display scale and zoom level you were using when you encountered the bug would be helpful.

**Comment by protective1** [comment] 2020-08-30 18:27
![Screenshot_20200830-142353](https://user-images.githubusercontent.com/8593007/91666692-c6eefb00-eacc-11ea-9dd5-202416971267.png)

I was moving down and to the left when a gray vertical line appeared mid-step

**Comment by 00-Evan** [comment] 2020-08-31 18:53
I've run some tests on an Android emulator with your exact device specs and I'm not able to reproduce the issue. The problem may be device specific, and there's not much I can do without being able to see it for myself.

**Comment by protective1** [comment] 2020-09-04 00:42
Here is a video of the vertical bar video glitch recorded using Google Play.
![ShatteredPixel_VerticalBarVideoGlitch](https://user-images.githubusercontent.com/8593007/92186777-ddc38380-ee25-11ea-80fe-a6666aafd188.gif)

**Comment by 00-Evan** [comment] 2020-09-04 00:51
Thanks, that's extremely helpful. It looks like this is a problem with buff icons and their fading behavior. For just a frame of animation the lightness buff is shooting way down when it definitely shouldn't be. That buff updates constantly as the hero is walking, which probably exposes this issue.

**Comment by 00-Evan** [comment] 2020-10-05 20:18
Fixed in commit fe23143d0ea1b48cf7b9dde8b7b7ab03c63ccd75

**Closed by 00-Evan** 2020-10-05 20:18 UTC
Labels: Fixed Indev, Quirk
