### ISSUE TITLE
Reflected hostile entities with charm buff stay untargetable

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#572] opened 2021-01-02 07:04 UTC
I have an enchanted armor with multiplication curse on it. Also, I have a cursed Friendly Sai. My weapon has managed to charm a hostile entity, whose charmed debuff is visible when inspected. Afterwards, my armor's curse activated for that entity and multiplied it. This entity, when inspected, has no charm debuff on it, yet I cannot target it, but I sure can other hostile entities that I am currently fighting adjacent to me. I suspect that this incident was unintentional. If it wasn't, cloned entities should have inherited (de)buffs in their respective descriptions, to avoid any confusion as such. That means in Multiplicity.java curse, attacker mob's buffs should be iterated and copied over to the newly created job object. I am not really sure how this problem occurs, but I'm quite sure it's done when using the Reflection class when calling newInstance(). I guess it creates an instance with the same id, therefore when the Hero actor does an actAttack, the isCharmedBy check reads the attacker's id to determine if it can be targeted in canAttack function. Since the "cloned" mob is a reflected entity, I believe it has the same id, thus it cannot be targeted as well. I couldn't find the source code of the ClassReflection.java file. I didn't search that must either. Correct me if I'm wrong, but this behavior is reproducible on my end.

**Comment by 00-Evan** [comment] 2021-01-02 17:48
It looks like this is caused by the freshly cloned mob sharing an actor ID with the existing one, that definitely shouldn't happen. Conveniently I am about to release a new patch, and so will address this in that.

(for licensing reasons I do not accept code contributions, and so I stopped reading your message after you described the issue)

**Comment by 00-Evan** [comment] 2021-01-05 20:06
fixed in commit b41c403deabcd49e80e243ac627c2d1ae536d50e

**Closed by 00-Evan** 2021-01-05 20:06 UTC
Labels: Fixed Indev, Minor
