### ISSUE TITLE
[Bug] Not being able to move after being resurrected

### ISSUE THREAD

**Issue by megz15** [00-Evan/shattered-pixel-dungeon#1432] opened 2023-06-30 08:22 UTC
After being killed by a Gnoll Brute and getting resurrected with an Ankh, I was unable to move and right-clicking on tiles didn't bring up a menu either. A loading icon was being displayed at the bottom beside the experience bar.

It's not an issue, I was able to continue by going to the main menu and reloading the game, but still, it froze.

![image](https://i.imgur.com/V94eGCO.gif)

PS I love the updates you've been adding, the duelist character is awesome

**Comment by 00-Evan** [comment] 2023-06-30 16:02
I'm not able to reproduce this, dieing as the monk to a gnoll brute correctly gives the player back control after resurrection.

It's possible something more it at play here, did you use a monk or weapon ability right before dieing? If there isn't a specific trigger then this is likely a very rare race condition.

**Comment by 00-Evan** [comment] 2023-07-09 15:58
Closing this for now as I cannot reproduce the issue.

**Closed by 00-Evan** 2023-07-09 15:58 UTC

**Comment by megz15** [comment] 2023-07-10 09:49
Apologies for the late reply, I had my exams this week

I'm sure I didn't use a monk or weapon ability
It did seem to be an edge case trivial issue, but I thought I should report it anyway

**Comment by 00-Evan** [comment] 2023-07-10 16:07
No worries, I'm mainly closing this as there's no action I can perform relating to it at this time. I'll keep your report in mind if others experience this issue though.
