### ISSUE TITLE
Tome of dungeon mastery

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1582] opened 2024-01-01 08:47 UTC
After the warrior picks up the book, instead of clicking on the blinking journal button, open the settings, the game will freeze.

**Comment by 00-Evan** [comment] 2024-01-03 00:35
I'm not able to reproduce this. It does result in odd functionality (the tutorial seems to get stuck), but opening the settings menu does not cause the game to crash or freeze.

**Comment by Lyx0527** [comment] 2024-01-03 02:47
Yes, that's exactly what I want to say. I seem to have used inappropriate words

**Comment by 00-Evan** [comment] 2024-01-18 18:12
Fixed in commit da1e844e03eaf499205ec43b415e0b3fc1639dad

**Closed by 00-Evan** 2024-01-18 18:12 UTC
Labels: Major Bug, Fixed in BETA
