### ISSUE TITLE
Boomerang thrown into chasm lost?

### ISSUE THREAD

**Issue by nyuszika7h** [00-Evan/shattered-pixel-dungeon#67] opened 2015-11-09 09:42 UTC
I threw my boomerang into the chasm out of curiosity, and now it seems to be gone, I can't find it anywhere.

Using 0.3.2b.

**Comment by 00-Evan** [comment] 2015-11-09 18:07
Items appear on the floor below when thrown into a chasm. You should be able to find it somewhere there.

**Comment by nyuszika7h** [comment] 2015-11-09 20:15
Yes, I went down to that floor, but I haven't found it anywhere, and I've died since then. I'll try this again later.

**Comment by 00-Evan** [comment] 2015-11-09 20:17
Sure. There haven't been any changes in this logic though, it should be working as it did before. keep in mind it could have been in a hidden room, it's hard to be sure without a scroll of magic mapping.

**Comment by 00-Evan** [comment] 2015-11-13 16:32
closing, can't reproduce this, items seems to be falling down into the next floor normally.

Feel free to re-open this is you can reproduce the issue.

**Closed by 00-Evan** 2015-11-13 16:32 UTC
