### ISSUE TITLE
Suggestion: support playing with keyboard only and some ideas for that

### ISSUE THREAD

**Issue by Ciliane** [00-Evan/shattered-pixel-dungeon#894] opened 2022-01-04 08:30 UTC
I want to suggest adding features that make it possible to play the game with keyboard only without a mouse. I don't know if it's worth the time but I think it would be generally a pretty comfortable way to play, I really like the keybinds that are already in the game and with some extension it may be possible to make the game playable KB only and still be pretty comfortable

I don't know if you ever wanted to do this or not, but I also have ideas for KB only support. I think the weirdest parts of making keyboard only possible are inventory, throwing/using items at an empty tile and, though trivial, moving the screen to look at the entire dungeon floor. I think they all are solvable quite easily but "fixing" all the trivial things in the game may be annoying. 

It would be pretty convenient to move the screen with CTRL + move north/west/NE/etc and one more keybind to move the screen back so the character is in the center as normal, not sure what else to way

Inventory is trickier, you can use the clever approach of a chrome extension called Vimium (https://youtu.be/t67Sn0RGK54), one of the things it allows is to click any link or button on the page with keyboard and basically what it does is assign a character or two to each link/button on screen and what you have to do is type in these characters to select what link you want to click. I think you can do the same for selecting items in inventory like this: press another new keybind and type in the position of the item in inventory, for example 34 if the item is on third row and fourth column, and then it's as if you clicked on the item with mouse

Probably the least comfortable thing to do without a mouse is going to be using items at empty tiles or anything that is not an enemy. I can't think of a very good way to do it while also letting you throw items at long distances, but it may be best to simply draw the target cursor that is already used for enemy selection and use the directional binds (north, west NE, etc) to move it, and when you move it to the desired position you can use the item with attack keybind. I know it seems pretty dirty, can't think of a better way

There are more trivial things that are impossible (or I don't know how) without a mouse but they should be simple to fix I think.

**Comment by Ciliane** [comment] 2022-01-04 08:34
Apparently there is an issue about the same thing to make the game playable without a mouse (https://github.com/00-Evan/shattered-pixel-dungeon/issues/351), this issue is different just because of some ideas

**Comment by 00-Evan** [comment] 2022-01-04 15:59
Duplicate of #351 

full keyboard support is likely something I'll start work on as a part of full desktop support and Steam release.

**Closed by 00-Evan** 2022-01-04 15:59 UTC
