### ISSUE TITLE
Scroll of transmutation abuse

### ISSUE THREAD

**Issue by Halifay** [00-Evan/shattered-pixel-dungeon#1250] opened 2023-03-01 19:08 UTC
Scroll of transmutation fails to change artifact if all artifacts were discovered and remains unused. However it is considered as a scroll use by empowered scrolls tier 3 mage talent. Therefore it is possible to get infinite +3 levels for wands spending just one turn per talent use which doesn't seem intentional.

**Comment by 00-Evan** [comment] 2023-03-01 19:32
Fixing this by having transmutation turn the artifact into a ring if artifact spawning pool is empty, which is the intended behavior in cases like this.

**Comment by 00-Evan** [comment] 2023-03-13 17:34
fixed in commit 299b36d59466c61efb51bc19126249b7a351fb51

**Closed by 00-Evan** 2023-03-13 17:34 UTC
Labels: Minor Bug, Fixed in BETA
