### ISSUE TITLE
Choose which item to interact with on tile

### ISSUE THREAD

**Issue by cantarini** [00-Evan/shattered-pixel-dungeon#1612] opened 2024-01-30 10:09 UTC
if I need to activate a plant, say to escape if low HP, and there is for example money on the ground, it picks up money as a priority, and I lose my turn, which may be deadly in some circumstances.
It would be nice to choose which item to interact with, if more than one present on the hero tile.

**Comment by 00-Evan** [comment] 2024-01-30 16:10
Duplicate of #1599

**Closed by 00-Evan** 2024-01-30 16:10 UTC
