### ISSUE TITLE
Weapons with enchantments may also be cursed

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1376] opened 2023-05-24 22:19 UTC
Sai dropped from skeleton
Is this intentional?
![Screenshot_20230525_020441_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/a9625b68-6781-4dbd-9cbf-07dae07f15fc)

**Comment by 00-Evan** [comment] 2023-05-24 23:58
This should be impossible, can you provide any other information? It would also be helpful to see more game info in English, it takes me a very long time to translate screenshots in Chinese.

**Comment by Lyx0527** [comment] 2023-05-25 00:18
I have removed the curse, otherwise it will kill me. I forgot to use English instead

There is no yellow font between the enchantment statement and the weapon ability statement, which means that the weapon has a curse, which is the same format as in English.

I used my armband to steal the skeleton, but did not steal any items. I shot it with a crossbow and it dropped the weapon. Not related to sacrificial flames

**Comment by 00-Evan** [comment] 2023-05-25 00:54
Do you have a ring of wealth? It is possible for the ring to generate a weapon that has a curse, but then override it to give you an enchantment instead.

**Comment by Lyx0527** [comment] 2023-05-25 01:08
No, The Wealth Ring is very powerful, and if I had it, I would definitely replace it with the Furor Ring.
The background color of SAI is purple, not blue or red. Turn red after equipping
![Uploading Screenshot_20230525_090013_6f3fe77889fbecf862f7061166760abf.jpg…]()

**Comment by Lyx0527** [comment] 2023-05-25 01:08
No, The Wealth Ring is very powerful, and if I had it, I would definitely replace it with the Furor Ring.
The background color of SAI is purple, not blue or red. Turn red after equipping
![Screenshot_20230525_090013_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/7e4a9e56-9b8e-4115-97c9-c6c5440b8ff8)

**Comment by Lyx0527** [comment] 2023-05-25 01:08
No, The Wealth Ring is very powerful, and if I had it, I would definitely replace it with the Furor Ring.
The background color of SAI is purple, not blue or red. Turn red after equipping
![Screenshot_20230525_090013_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/7e4a9e56-9b8e-4115-97c9-c6c5440b8ff8)

**Comment by 00-Evan** [comment] 2023-05-25 03:26
It is possible for enchanted items to also be cursed, but not from regular item drops. I'm going to close this for now as I can't reproduce the issue, but feel free to comment if you encounter it again.

**Comment by Lyx0527** [comment] 2023-05-25 04:39
I know this, but I won't joke about it, you know. 
seed：RQNNXYLCQ
I often play huntress and carry 8 upgrade scrolls to win, so I am impressed with each enchantment stone.
In the picture, the four chinese sentences in the bottom left corner are：
you pick up：dart
you pick up：elastic sai
your grip involulntary tightens around the weapon
you swiftly equip your weapon
There is no green text inserted between these, such as“你的武器在暗中微微发光”means  "your weapon glows in the darkness" 
I gave all my three upgrade scrolls to the +1 crossbow, which comes from the  piranha room, two enchantment stones are still lying in my package.
![Screenshot_20230519_212909_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/66f4d431-b640-4ef6-bde1-e702eaea4cf6)
![Screenshot_20230525_115045_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/e29e56d2-b9ae-4859-9b9a-c5e81c9e2dd0)
![Screenshot_20230525_121027_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/ee858595-9fa1-4819-ad97-813a245953bc)

**Comment by Lyx0527** [comment] 2023-05-25 04:43
I have come up with another possibility, which may be related to the red spirits. 

I saved a red spirits with a scroll at 6th floor, it came from the tomb in the locked room. The tomb gave me +3 brimstone mail armor, the spirits gave me +1 leather armor. 
And the bug occurred on the loot of the 6th floor skeleton.

**Comment by Lyx0527** [comment] 2023-05-25 06:22
I received pictures from other players,
It is also a cursed weapon with elastic enchantment
![790eaa9c0d9caea3](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/e6e60509-c45b-4af1-aae6-1075e37df1f7)

**Comment by 00-Evan** [comment] 2023-05-25 16:03
Fixed in BETA-3

**Closed by 00-Evan** 2023-05-25 16:03 UTC
Labels: Quirk, Fixed in development, Caused by BETA
