### ISSUE TITLE
Stone of intuition sometimes vanish in the first use even if you get it right...

### ISSUE THREAD

**Issue by Mellotic** [00-Evan/shattered-pixel-dungeon#861] opened 2021-11-12 17:23 UTC
Ya it's is... I used my stone to discover the identity of Healing potion after that it vanished....

**Comment by Mellotic** [comment] 2021-11-12 17:25
![Uploading Screenshot_2021-11-12-22-53-55-22_6f3fe77889fbecf862f7061166760abf.png…]()

**Comment by Mellotic** [comment] 2021-11-12 17:25
Wait the pic is not getting posted

**Comment by Mellotic** [comment] 2021-11-12 17:28
I will right my actions

You picked up: stone of intuition
You are hunger
You picked up: stone of aggression
Correct: item's type has been identified!

**Comment by 00-Evan** [comment] 2021-11-12 17:30
Had you used a stone of intuition previously in this run? The second use is not stored per-stone, so you will still lose one if you use your second correct guess later.

**Comment by Mellotic** [comment] 2021-11-12 17:36
No it's the first one in whole run

**Comment by 00-Evan** [comment] 2021-11-12 17:42
It really would be helpful to see that screenshot. From the code there doesn't seem to be any way for this to happen.

**Comment by Mellotic** [comment] 2021-11-12 17:42
Let me try

**Comment by Mellotic** [comment] 2021-11-12 17:43
![Uploading Screenshot_2021-11-12-22-53-55-22_6f3fe77889fbecf862f7061166760abf.png…]()

**Comment by Mellotic** [comment] 2021-11-12 17:44
Do you have some where else to post Photos?

**Comment by Mellotic** [comment] 2021-11-12 17:45
> I will write my actions
> 
> You picked up: stone of intuition You are hunger You picked up: stone of aggression Correct: item's type has been identified!

But this is true

**Comment by Mellotic** [comment] 2021-11-12 17:49
It was the first time when I picked up the stone of intuition in the whole run just to identify the healing potion because I had it 10 of them

**Comment by 00-Evan** [comment] 2021-11-12 17:51
You could try using a service like imgur https://imgur.com/

**Comment by Mellotic** [comment] 2021-11-12 17:52
If I'm sure you have a face book account right as Shattered Pixel dungeon

**Comment by Mellotic** [comment] 2021-11-12 18:08
@00-Evan I have changed my profile pic
 so you can check from there

**Comment by 00-Evan** [comment] 2021-11-12 18:10
That's not a complete screenshot, but regardless there is some important info there. By the caves you must have found a stone of intuition previously, one is guaranteed to drop somewhere on floors 1-3. Are you absolutely sure that is the first time you've used a stone of intuition on that run?

**Comment by Mellotic** [comment] 2021-11-12 18:12
Ya very much sure that's the First time

**Comment by Mellotic** [comment] 2021-11-12 18:15
Let me Read my Journal

**Comment by Mellotic** [comment] 2021-11-12 18:18
Don't we have Journals?

**Comment by 00-Evan** [comment] 2021-11-12 18:21
The journal wouldn't contain information in that much detail, it mostly just shows landmarks.

I'm not able to reproduce the error, stones are correctly preserved for me every time upon the first correct guess, and there should be no way for this preservation to not happen. The game uses an invisible buff to track when the player has made a correct guess already, and that buff is only every applied when a correct guess is made. Making a second correct guess, or an incorrect guess, removes that invisible buff.

I'm closing this as forgetting you used a stone previously is the only reasonable explanation, sorry. Please feel free to comment if you run into the issue again.

**Closed by 00-Evan** 2021-11-12 18:21 UTC

**Comment by Mellotic** [comment] 2021-11-12 18:39
Hey what!

**Comment by Mellotic** [comment] 2021-11-12 18:42
The dialogue says u picked up: stone of intuition
Your Guess is correct so it should be preserved 
But I don't have it and even it's not written what else do you need

**Comment by Mellotic** [comment] 2021-11-12 18:43
Na I'm not happy with that answer of yours

**Comment by Mellotic** [comment] 2021-11-12 18:45
What happened to the stone of intuition which I just picked up then

**Comment by Mellotic** [comment] 2021-11-12 18:47
Now I feel very sad about it
My heart will never forget that
You just ignored the fact of that bug 😢

**Comment by 00-Evan** [comment] 2021-11-12 18:50
I'm sorry, but I've tested this locally and it works perfectly, so there's nothing more I can do. If there is a genuine problem with stones of intuition then more people will report it, and I'll eventually be able to hone in on the issue by cross-referencing those reports. At the moment though you are the only person to report this issue to me, which means it is either extremely rare or you are forgetting a previous use of an intuition stone.

**Comment by Mellotic** [comment] 2021-11-12 18:56
I had only go myself into two rooms of stone one in 1-3 as you mentioned but only got stone of flock and shock but not intuition the second time I got the room was in caves in it found stones of intuition and aggression as so as I found intuition I used it to identify the healing potion I saw that there was no stone of intuition and also there was no text of being preserved so as soon as possible I mention it as an issue... Plus I never forget Game related stuffs
