### ISSUE TITLE
(visual bug) Monk+disintegration trap = glitched monk? (v0.6.1)

### ISSUE THREAD

**Issue by draco123456ftw** [00-Evan/shattered-pixel-dungeon#188] opened 2017-08-17 07:15 UTC
Pushed a monk into a disintegration trap using a blast wand and it glitched out. It just froze there, it doesn't move or attack and I can't interact with it.

I'm pretty sure the damage from the trap was enough to reduce its health to 0, as it was already pretty low. Not sure if I received xp for it.

When I quit to menu and went back to my game it dissapeared

Image: (note that there's no attack indicator even though I'm next to it)
https://ibb.co/i1DWEv

**Comment by 00-Evan** [comment] 2017-08-17 08:35
Hrm, I'm not able to reproduce this indev. It may have been incidentally fixed by other fixes I'm making in 0.6.1a (coming very soon, tomorrow probably). Let me know if you're still running into this after that update.

**Closed** 2017-08-17 18:18 UTC
