### ISSUE TITLE
Lags on iPhone

### ISSUE THREAD

**Issue by Diomos** [00-Evan/shattered-pixel-dungeon#1215] opened 2023-01-18 22:39 UTC
v1.4.3
iPhone 12
Often when some action is about to be taken like attacking enemy or picking up item game briefly lags. Immediate action than takes sometimes 2 or more seconds to complete, degrading whole experience. Problem is it's hard to replicate as it appears randomly. I stopped playing the game on iPhone for this reason.

**Comment by 00-Evan** [comment] 2023-01-18 22:52
That definitely shouldn't happen. The game plays perfectly smoothly on my 1st gen iPhone SE tester device, so it's definitely not an issue with processing power.

I also haven't received any other reports relating to this, which makes me suspect it's a device-specific issue. Do you get hitches or slowdowns in any other apps, and do you have anything running on your device which might hog system resources?

**Comment by Diomos** [comment] 2023-01-19 22:05
I found something interesting today. Normally I have my iPhone in silent mode by default and I play with it as well. This evening I turned it off just to have a sound after a while in the game and so far I haven't experience any lag. I was unable to test this much however. I'll try more tomorrow, also combine settings (music and sound muted, ignore silent mode etc.) and let you know.

**Comment by TextualMold9830** [comment] 2023-02-01 22:59
I have a similar issue on iPad Air 1, after having the game opened for a long period of time I started to experience lagg when descending. I was using silent mode then, with default settings.

**Comment by 00-Evan** [comment] 2023-02-02 18:28
Hm, well if the issue appears on an older device too it's likely not caused by the latest iOS version. The next Shattered update is including some improvements to the cross-compiling tool that the game uses, which may incidentally fix this (especially if it's related to memory management). Let me know if you still encounter this on v2.0

**Comment by 00-Evan** [comment] 2023-02-14 20:24
I have made some changes to how the game handles system gestures on iOS in v2.0.0-BETA-3. This should notably improve cases were touches were being delayed on more modern iOS devices.

Going to tentatively mark this as fixed in beta, let me know if BETA-3 gives you an improvement.

**Comment by 00-Evan** [comment] 2023-03-13 17:33
fixed in commit 73dcf5e7009982be7fbc0ed08b6b118b55e4af4d

**Closed by 00-Evan** 2023-03-13 17:33 UTC
Labels: Minor Bug, Fixed in BETA

**Comment by Diomos** [comment] 2023-11-09 12:30
@00-Evan After latest update to 2.2.1 lags came back...

**Comment by 00-Evan** [comment] 2023-11-09 16:51
@Diomos I'm aware of this. I made a change in v2.1.1 as some users were getting the opposite problem: system gestures registering as inputs in the game. I'll see if there's a way to get the best of both worlds.
