### ISSUE TITLE
Infinite bug happened while fighting Tengu

### ISSUE THREAD

**Issue by jagibson** [00-Evan/shattered-pixel-dungeon#979] opened 2022-05-11 04:53 UTC
While fighting Tengu, I used the spell book and it cast Sleep. Tengu goes to sleep and I get paralyzed at the same time. Game gets stuck in a loop. Force-closing the app let me resume the battle with Tengu.

![6BEF0687-C871-41FD-B5B1-54C8D73E1028](https://user-images.githubusercontent.com/5667478/167771475-923124bf-9c13-44ba-8053-20e262e7af68.png)

V1.2.3 iOS 15.4.1 on an iPhone 8 Plus

**Comment by 00-Evan** [comment] 2022-07-07 16:29
Unfortunately I'm not able to reproduce this. May be an extremely rare race condition (a once-off, basically). Please feel free to comment if you encounter this again and I'll re-open.

**Comment by 00-Evan** [comment] 2022-07-12 14:12
I've gotten another report about this, going to try and reproduce again and see if I can fix for 1.3.2

**Comment by jagibson** [comment] 2022-07-12 18:29
Yeah it hasn't happened to me since.  Thanks for looking!

**Comment by 00-Evan** [comment] 2022-07-27 16:31
fixed in commit 783dab6fc11855c54e579e8ac1f9a2ae28fe752a

**Closed by 00-Evan** 2022-07-27 16:31 UTC
Labels: Quirk, Fixed in BETA
