### ISSUE TITLE
[Bug] Sad Ghost announces wrong boss

### ISSUE THREAD

**Issue by derei** [00-Evan/shattered-pixel-dungeon#1866] opened 2024-10-05 20:48 UTC
Sometimes, the Sad Ghost announces the blue crab, but the stinky rat appears instead. I couldn't find out a pattern for when this happens, but I encountered it 2 or 3 times so far.

**Comment by 00-Evan** [comment] 2024-10-06 16:33
I'm not able to reproduce this. The ghost's logic for which boss to annoucne and the actual boss spawning are both tied to the same data, which is determined based on the dungeon floor (2 for rat, 3 for gnoll, 4 for crab).

There should be no way for one boss to be announced and another to spawn.

**Comment by derei** [comment] 2024-10-06 21:04
Well, that's strange. Is there any way to enable a log, so when that happens again, I can provide some useful data?

**Comment by 00-Evan** [comment] 2024-10-07 15:19
I'm afraid there isn't, please do let me know if you encounter it again, a screenshot might he helpful. I'm closing this for now though.

**Closed by 00-Evan** 2024-10-07 15:19 UTC
