### ISSUE TITLE
Visual bug when transferring heroic armor power

### ISSUE THREAD

**Issue by wknoben** [00-Evan/shattered-pixel-dungeon#1541] opened 2023-11-19 17:21 UTC
I don't exactly know what caused this so I'll try to describe the situation as best I can.

Situation:
- Applied the Dwarf king's crown to +3 (scale?) armor (huntress, sniper, nature's power)
- Equipped an unidentified, non-cursed plate armor
- Tried to transfer heroic power from the scale armor to the plate armor
- In-game message states properties have been transferred

Outcome:
- Heroic power is still on the +3 armor
- Plate armor has disappeared

Screenshot shows the game state immediately after. Text implies everything worked OK, the huntress is still in plate armor on the playing field but not wearing armor in the character icon. Plate armor has disappeared from inventory.

![Screenshot_20231118-225614](https://github.com/00-Evan/shattered-pixel-dungeon/assets/45757529/1e479625-56c7-44a3-8fd3-8bba5930aa6a)

![Screenshot_20231118-225620](https://github.com/00-Evan/shattered-pixel-dungeon/assets/45757529/d48912dd-2794-4dd9-a981-0dfa8dc686f0)

**Comment by 00-Evan** [comment] 2023-11-19 17:38
I've done a test or two and can't reproduce this. I can see the visual bug on the character's sprite, that can definitely be fixed, but the properties otherwise seem to transfer correctly. It is possible that the plate armor was also +3, how much defense is the hero armor currently granting?

**Comment by wknoben** [comment] 2023-11-19 18:49
I checked the armor and you're right, the power did transfer correctly to the plate. What threw me off is the strangeness of the sprite, the fact that the plate armor got unequipped and put in place of the original scale armor, and that the plate turned out to have +3 too (it's on +4 in the ss because I put another upgrade on later).

![Screenshot_20231119-114518](https://github.com/00-Evan/shattered-pixel-dungeon/assets/45757529/1221a4b6-4141-41be-8d12-60d3f742c8dd)

**Comment by 00-Evan** [comment] 2023-11-20 16:52
@wknoben When you are transferring, the candidate armor is deleted and absorbed into the hero armor, so in this case it is correct that you end up with no armor equipped.

@SomeTroglodyte it is intended in this case that the transfer works on any armor. In general there are some consistency issues when it comes to usable when IDed or cursed, but that's a separate concern entirely.

**Comment by 00-Evan** [comment] 2024-01-18 18:09
Fixed in commit 9127dfff9b7e49e5612c58cb58c7d70fec810768

**Closed by 00-Evan** 2024-01-18 18:09 UTC
Labels: Quirk, Fixed in BETA
