### ISSUE TITLE
Feature Request: Long-press to move

### ISSUE THREAD

**Issue by ManaUser** [00-Evan/shattered-pixel-dungeon#24] opened 2015-02-15 22:24 UTC
For the most part, (Shattered) Pixel Dungeon has a very good interface. But one of its few shortcomings is that there's no way to move to a space without interacting with it (e.g. picking up an item, entering a staircase), unless that space is next to a wall. I propose that this could be accomplished with a long press.

**Comment by 00-Evan** [comment] 2015-02-17 16:47
This should be fairly possible from a technical perspective, and it does fill in a gap in functionality. I'll see about doing this or something similar in a future release.

**Comment by joshtriplett** [comment] 2015-02-25 18:24
For that matter, since there's a button to pick up an item you're standing on, if you frequently find yourself wanting to move onto a location but not pick up the items on it, perhaps there could be an option to not pick up items on movement by default.

**Comment by 00-Evan** [comment] 2015-02-27 22:11
@joshtriplett If long-press to move were implemented it would handle this case.

**Comment by joshtriplett** [comment] 2015-02-27 22:43
> If long-press to move were implemented it would handle this case.

I was suggesting an option to make this the *default* movement, without requiring a long press.  That would make it take a second step to pick up items, but would avoid ever doing so accidentally.

**Comment by 00-Evan** [comment] 2015-02-27 22:51
@joshtriplett That's a thought, not sure how useful it would be on mobile, given that people tend to really hate tapping more than they have to, but I could definitely see that as useful on desktop where people use the arrowkeys/controllers to move.

**Comment by joshtriplett** [comment] 2015-02-28 04:48
It's not something that you'd want as the default default movement, but as an option, I think it makes sense.  Personally, I'd probably leave it on all the time, not just because I frequently step on drops that I don't want to pick up (notably around a corner where they're not visible), but because I want to consciously think about taking the extra turn to pick up an item when there are enemies around.

**Comment by 00-Evan** [comment] 2015-12-04 16:10
Hey, So I wanted to start up a bit of discussion on this one again.

I'm curious, is the main reason why you would want this feature so that you wouldn't pick up an item accidentally during fights? I've been considering tweaking movement behavior to not automatically pick up items if enemies are near, which should alleviate this without requiring that the player knows they can long-press to move.

**Comment by ManaUser** [comment] 2015-12-04 16:47
Yes, that's the main thing. Though as I said in the initial request, it comes up with interactive dungeon tiles, like stairs or wells too. That's less common, but there have definitely been times where I wished I could step onto the stairs during a fight without leaving the level. I don't recall if it's ever come up with a well, but it could, e.g. you're fighting near a healing well and don't want to waste it.

**Comment by 00-Evan** [comment] 2015-12-04 16:53
The main issue I have with the long-press is that it's complicated to explain and doesn't translate well to non-touchscreen platforms. It also risks conflicting with the zoom and camera move functionalities. Image placing your finger for a moment, thinking about how to move the camera, then suddenly you're running to a location you didn't mean to run to.

I appreciate that leaving dungeon features like stairs out of it means the issue isn't perfectly solved, but I think disabling auto-pickup in combat should make things work much better for the vast majority of situations. I'll look to add it in 0.3.3

**Comment by ManaUser** [comment] 2015-12-04 17:06
I see what you're saying about long-press, but I don't really think it would be problem personally. However I do agree that the change you're planning instead will be an improvement over how it is now.

**Comment by joshtriplett** [comment] 2015-12-04 19:24
If automatic pickup did not occur with monsters around (or with monster fire around), that would completely solve the problem for me; I could move onto the space of an item without picking it up, and if I want to pick it up, I can use the button for that item.

**Comment by 00-Evan** [comment] 2015-12-04 19:30
@joshtriplett That's exactly what I plan on implementing. Basically, if you see monsters, and none of them are behind a wall (so mind vision doesn't mess with it) items won't automatically pick up.

**Comment by TheCanadianAlligator** [comment] 2015-12-04 19:35
But what about Huntress' passive? Will we still have to resort to tapping the wall there, if we know they're coming through a door soon?

**Comment by 00-Evan** [comment] 2015-12-04 19:38
Hmm, that's a decent point. Perhaps it's best to just have auto-pickup always be off even if you see enemies through walls. Slightly more awkward in some cases but will feel more consistent, and is more useful for huntress.

**Comment by joshtriplett** [comment] 2015-12-04 22:01
Will this also handle the case of a monster out of sight but firing a ranged attack?

**Comment by 00-Evan** [comment] 2015-12-04 22:53
@joshtriplett That somewhat complicates things. From a game logic perspective it would mean checking every mob, see if they see the player, then check if they are capable of making ranged attacks, which isn't something that's easy to check at the moment. This contrasts with mobs currently seen, which is already a tracked and reported numbers. Also, how would you classify mobs with limited ranged powers, like the new prison guards?

Yes there will be edge cases that this will miss, but I think the simple rule of seen mobs > 0 is the best here. It's also consistent with the current interrupt logic, that stops you once seen mobs first goes above 0.

**Comment by 00-Evan** [comment] 2015-12-18 19:14
this has been implemented indev and will go live with 0.3.3 shortly. Will close this ticket with a commit referenced once the source is released.

**Comment by 00-Evan** [comment] 2015-12-22 03:51
changelist here: 0c6837686342eb7bb86dab01c186d0ff06779432

Feel free to comment if there are any issues with this new functionality, ticket closed for now.

**Closed by 00-Evan** 2015-12-22 03:51 UTC
Labels: Enhancement, Fixed Indev
