### ISSUE TITLE
desktop jar wont load

### ISSUE THREAD

**Issue by CustomKKK** [00-Evan/shattered-pixel-dungeon#526] opened 2020-10-24 07:33 UTC
I have java but the .jar just wont load. its really pissing me off because my iphone doesnt support this amazing game, any help?

**Comment by 00-Evan** [comment] 2020-10-24 15:33
I'm afraid I'll need more information than just "the jar won't start". Java may be misconfigured on your computer. Please try running it from the command line as that will give an error print out.

**Comment by TheYsconator** [comment] 2020-10-28 14:41
May be related to the error I'm getting when trying to build:

```
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.shatteredpixel.shatteredpixeldungeon.desktop.DesktopLauncher.main(DesktopLauncher.java:105)

60:60: syntax error: Expected string but found end of script. (-2741)
sh: -c: line 2: syntax error near unexpected token `('
sh: -c: line 2: `If you could, please email this error message to the developer (Evan@ShatteredPixel.com):'

Process finished with exit code 0
```

**Comment by 00-Evan** [comment] 2020-10-28 15:43
@TheYsconator That's a compilation issue, totally separate from running the properly packaged JAR. You're not building the game correctly through gradle, and so important properties like the game's version number (which it's trying to parse here) aren't available.

**Comment by TheYsconator** [comment] 2020-10-28 15:55
Yes, that was the cause of the error I got indeed. (I knew that! I just, err, momentarily forgot. Thanks!)

**Comment by 00-Evan** [comment] 2020-10-31 17:44
Closing this due to lack of actionable information.

**Closed by 00-Evan** 2020-10-31 17:44 UTC
