### ISSUE TITLE
can't pick up gold this turn

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1714] opened 2024-05-22 12:59 UTC
I'm clicking on this gold and nothing happens.  I then take a step in another direction (I'm not frozen or paralyzed) and I can now click on the gold to pick it up.  A temporary bug but I'm not sure what's happening here.
![Screenshot_20240522-085248](https://github.com/00-Evan/shattered-pixel-dungeon/assets/8593007/a82ec971-d860-443b-9894-825767b688ad)
![Screenshot_20240522-085257](https://github.com/00-Evan/shattered-pixel-dungeon/assets/8593007/ca3dfc0d-ab66-4e35-b607-2b8d87fc4a04)
![Screenshot_20240522-085703](https://github.com/00-Evan/shattered-pixel-dungeon/assets/8593007/5c0a0f07-be73-4e12-9f00-59dcf79c887d)
![Screenshot_20240522-085750](https://github.com/00-Evan/shattered-pixel-dungeon/assets/8593007/6eeb7769-b164-4274-8a70-462dc41f9a67)
![Screenshot_20240522-085854](https://github.com/00-Evan/shattered-pixel-dungeon/assets/8593007/549d459c-acb0-42cc-92e5-5926f91e3daf)

**Comment by 00-Evan** [comment] 2024-05-22 15:05
Hm, that's odd, and will likely be impossible to reproduce I'm afraid =S.

Just to be clear, you were standing as you were in the first screenshot, attempting to tap on the gold to your right, and not moving. Tapping elsewhere (which tile?) let you move, and you could them move to and pick up the gold.

**Comment by protective1** [comment] 2024-05-24 06:34
That is correct.  To resolve it, I believe I tried one tile to the left, then tapped back on the gold.

**Comment by Palatis** [comment] 2024-06-02 21:14
usually when you're alone (no enemy spotted), you click on a tile with item, hero moves over and pick up the item.

however, if an enemy is in sight, the game pause between move+pick action.
because move takes one turn, and pick takes another, you might want to do something else other than picking the stuff and spend one turn.

maybe you spotted an enemy, so the game pauses before picking up the gold.
by moving away from the specific tile, the enemy also walks away, so you're all alone now and the hero picks up the gold.

**Comment by 00-Evan** [comment] 2024-06-04 17:18
Sorry for the delay in testing this, unfortunately as I thought I'm not able to reproduce this =S.

I'm closing this for now as there's nothing I can really do, feel free to comment again if you encounter this issue a second time.

**Closed by 00-Evan** 2024-06-04 17:18 UTC
