### ISSUE TITLE
Skip floors

### ISSUE THREAD

**Issue by tessmero** [00-Evan/shattered-pixel-dungeon#237] opened 2018-04-06 18:50 UTC
This happens consistently when I *removed*.

After *removed*, I still see the normal "descending" animation. But then I find myself two floors below where I started. This works for skipping any floor including boss fights.

Attempting to ascend after doing this will either put me on the previous floor (unexplored), or I get a message about my save being corrupted.

**Comment by 00-Evan** [comment] 2018-04-06 19:16
This will vary significantly by device, only some will trigger it, but regardless I am aware of this issue. It has existed since vanilla but the recent interlevelscene adjustments make it much easier to activate. Will be fixed in 0.6.4a

I have edited your comment to remove reproduction steps, as this bug can be used to cheat.

**Comment by 00-Evan** [comment] 2018-04-11 03:48
fixed in commit a7c442dde62c84ccbc344fbf4fc765bbe2204155

**Closed by 00-Evan** 2018-04-11 03:48 UTC
Labels: Fixed Indev, Major
