### ISSUE TITLE
(PC&Steam) Not able to put in seeds/daily runs and stuff

### ISSUE THREAD

**Issue by dc1wh** [00-Evan/shattered-pixel-dungeon#1098] opened 2022-10-02 09:59 UTC
Hello,

i finished the game with the mage few days ago. i play SPD for some time on Android, but got the game on steam too, so i wanted to put in seeds here too. after i finished the game (call it a day...), i checked if i can put in seeds, and i remember to be able to...

today, i wanted to give it another go with the same seed as my mage run, but i dont have the menu to do the optional stuff like seeds, daily run and such. 

![grafik](https://user-images.githubusercontent.com/18496163/193448561-e8157145-8e09-4688-9573-1e776c58e626.png)
![grafik](https://user-images.githubusercontent.com/18496163/193448494-10f0434a-4562-41db-822a-6aab2308ae27.png)

Version 1.3.2

**Comment by 00-Evan** [comment] 2022-10-02 15:45
Duplicate of #1058 

Try updating to the beta, which should fix this for you retroactively. Will also be fixe dwhen v1.4.0 releases early next week.

**Closed by 00-Evan** 2022-10-02 15:45 UTC

**Comment by dc1wh** [comment] 2022-10-02 15:52
thank you very much! I will just wait for the new version, im not in a hurry :)
(but i dont know, why you think this is a duplicate to a guy asking for different kind of cheats ^^ - anyway, no reply needed for that 👍 )

**Comment by 00-Evan** [comment] 2022-10-02 16:14
Whoops, linked the wrong issue, I meant #1056
