### ISSUE TITLE
Android app very slow + random crashes

### ISSUE THREAD

**Issue by 1BazBiz** [00-Evan/shattered-pixel-dungeon#1899] opened 2024-11-13 18:53 UTC
On my phone (LineageOS 20), the whole app (F-Droid version) is very slow if sfx and music are not disabled. 
At any moment after starting up the app, it crashes, sometimes in the main menu or in game.
Sorry, I don't know how I can get logs from the app, ask me if you need more details.

**Comment by 00-Evan** [comment] 2024-11-13 19:04
Likely duplicate of https://github.com/00-Evan/shattered-pixel-dungeon/issues/1889 , just to be sure though, are you sure its music or sound effects, and not just music?

I'd suggest chasing down if there are any issues with .OGG playback in lineageOS. Shattered uses .OGG on Android to save about 15 megs on download/install size.

**Comment by 1BazBiz** [comment] 2024-11-13 19:53
You're right, it's just music. 
I still don't know why the app is always crashing, but I will continue to search.

**Comment by 1BazBiz** [comment] 2024-11-15 05:41
I reproduced the crash with the Play Store version, so you can get the crash report

**Comment by 00-Evan** [comment] 2024-11-15 16:38
Can you let me know your device model please? I receive automated reports from all players on Google Play and so need a way to filter down to yours. More info about exactly what you were doing just before the crash could also be helpful.

**Comment by 1BazBiz** [comment] 2024-11-15 17:39
My device is a Realme 8i (RMX3151).
I was exploring the dungeon (in a new game)

**Comment by 00-Evan** [comment] 2024-11-15 23:32
Hm, odd, I'm not able to see any reports of crashes or errors from that device model. It's possible that your reports are antomatically getting filtered due to your custom ROM, or some other security setting.

I'm afraid that viewing the crash report yourself from logcat is probably the best way to be able to get the crash info to me.

**Comment by 1BazBiz** [comment] 2024-11-16 15:53
[pidcat.txt](https://github.com/user-attachments/files/17787080/pidcat.txt)
Here is the logcat of the app, from the start to the crash. I hope you'll find something.

**Comment by 00-Evan** [comment] 2024-11-16 19:19
Unfortunately I can't find any crash-related information in that logcat output. It looks like the game launches fairly normally, crashlytics (the crash reporting tool I use) even initialized properly, and then nothing.

Either the crash isn't in that particular part of the output you sent, or there is no crash report being logged, as if your device just decided to silently close the app. Sadly there's nothing I can really do without crash info, so I'm closing this issue. Feel free to send more info if you have any and I'll re-open if there's anything actionable.

**Closed by 00-Evan** 2024-11-16 19:19 UTC
