### ISSUE TITLE
Ring of Wealth drops from Piranhas don't show their animation when the Piranha dies from being on land.

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1255] opened 2023-03-07 01:45 UTC

**Comment by chorby-short** [comment] 2023-03-07 01:49
Not sure if it applies to those dragged or blasted into land (with chains or knockback, respectively), but I've had this happen when a piranha spawns on land and immediately dies, and the Wealth loot drop animation does not occur.

**Comment by 00-Evan** [comment] 2023-03-07 16:54
I've tested this and am not able to reproduce it. Piranhas correctly show the wealth VFX when they die on land either via spawning or pulling.

**Comment by chorby-short** [comment] 2023-03-07 18:36
https://user-images.githubusercontent.com/101913866/223517338-7aa6017a-64e7-4989-8b0e-4d02fe71387f.mp4

Attached is a clip farm my current loot farm. Looking at this again, it seems that this is a case where the VFX for multiplicity interfere with the VFX for wealth, as the former causes the latter not to trigger on the drop. Is there a way to either have both trigger at once, or else make the latter trigger instead of the former? The wealth VFX is more meaningful in farming runs than the multiplicity VFX, so I feel like it should have priority.

**Comment by 00-Evan** [comment] 2023-03-07 18:58
That information would have been helpful in your initial report. I can reproduce this with armor of multiplicity specifically.

**Comment by 00-Evan** [comment] 2023-03-13 17:34
fixed in commit 16d6b3f48491ec57bf2ec57bf35320867d7b4a2f

**Closed by 00-Evan** 2023-03-13 17:34 UTC
Labels: Quirk, Fixed in BETA
