### ISSUE TITLE
Game crashes when defeating third round of King of Dwarves enemies

### ISSUE THREAD

**Issue by JadElClemens** [00-Evan/shattered-pixel-dungeon#370] opened 2020-02-21 01:23 UTC
Just happened to me twice while fighting him, during the waves where the King is invincible and spawns minions from the four wells(?) in the corner of the room. I defeated two waves successfully, then after defeating a third, the game just crashed.

It was later that I noticed that the he became vincible again after two waves instead of three, and the game doesn't expect you to keep defeating the enemies before attacking the king. Or maybe I happened to successfully defeat three waves and lost count. 

I'm on v0.8.0-beta-4.2 on Android 9.

**Comment by 00-Evan** [comment] 2020-02-22 18:55
Various people have reported this and I haven't pinned down the cause yet. I suspect it is tied to ghouls but am not sure yet. Do you recall whether the minion that you killed before the crash was a ghoul?

**Comment by 00-Evan** [comment] 2020-02-27 15:30
This should now be fixed as of beta 4.3

**Closed** 2020-02-27 15:30 UTC
Labels: BETA, Major
