### ISSUE TITLE
Trigger of controller works strange. (L2, R2)

### ISSUE THREAD

**Issue by 54NG** [00-Evan/shattered-pixel-dungeon#1079] opened 2022-09-16 18:29 UTC
I'm playing shattered pixel dungeon on android 11 with thrid party controller, trigger (L2, R2) of controller works strange.
When I pull the trigger gently, I found that it sends other side of tigger value after threshold.
I can't explain exact value of threshold, it seems about 0.5 maybe.
So I changed some code of ControllerHandler.java and tested it on my phone.
From
		else if (axisCode == 4) {

			if (L2Trigger < 0.5f && value >= 0.5f){
				KeyEvent.addKeyEvent(new KeyEvent(Input.Keys.BUTTON_L2, true));
				controllerActive = true;
			} else if (L2Trigger >= 0.5f && value < 0.5f){
				KeyEvent.addKeyEvent(new KeyEvent(Input.Keys.BUTTON_L2, false));
				controllerActive = true;
			}
			L2Trigger = value;

		} else if (axisCode == 5){

			if (R2Trigger < 0.5f && value >= 0.5f){
				KeyEvent.addKeyEvent(new KeyEvent(Input.Keys.BUTTON_R2, true));
				controllerActive = true;
			} else if (R2Trigger >= 0.5f && value < 0.5f){
				KeyEvent.addKeyEvent(new KeyEvent(Input.Keys.BUTTON_R2, false));
				controllerActive = true;
			}
			R2Trigger = value;

to
		else if (axisCode == 5 {

			if (L2Trigger < 0.5f && value >= 0.5f){
				KeyEvent.addKeyEvent(new KeyEvent(Input.Keys.BUTTON_L2, true));
				controllerActive = true;
			} else if (L2Trigger >= 0.5f && value < 0.5f){
				KeyEvent.addKeyEvent(new KeyEvent(Input.Keys.BUTTON_L2, false));
				controllerActive = true;
			}
			L2Trigger = value;

		} else if (axisCode == 4){

			if (R2Trigger < 0.5f && value >= 0.5f){
				KeyEvent.addKeyEvent(new KeyEvent(Input.Keys.BUTTON_R2, true));
				controllerActive = true;
			} else if (R2Trigger >= 0.5f && value < 0.5f){
				KeyEvent.addKeyEvent(new KeyEvent(Input.Keys.BUTTON_R2, false));
				controllerActive = true;
			}
			R2Trigger = value;

I just change number behind 'axisCode =='.
Don't know how does it work, but the triggers doesn't work strange anymore!

**Comment by 00-Evan** [comment] 2022-09-16 18:33
Duplicate of #1034

Axis mappings (which can include triggers) should work correctly starting with the beta for 1.4.0, let me know if they aren't and post in that issue.

**Closed by 00-Evan** 2022-09-16 18:33 UTC
