### ISSUE TITLE
Ranged weapon targeting should be more user-friendly

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#10] opened 2015-01-25 22:49 UTC
Right now, targeting a ranged weapon or wand has a lot of problems.

If you aim for an enemy around a corner, you have to work out whether the number of squares between you, the corner, and the enemy will allow the weapon to pass the corner or hit the wall.

*However*, under some circumstances you can actually hit an enemy around a sharp corner by aiming for a point *past* that enemy instead.  (Particularly noticeable if you aim for an enemy further down and hit the closer one instead; that often happens with pirahnas.)

If you aim for an enemy down a straight corridor, and unintentionally touch the wall instead of the enemy, your weapon will hit a wall between you and the enemy and stop.  Particularly deadly if it's your boomerang and you're also using it as your primary melee weapon.

And worst of all, if you misjudge the ability to hit an enemy with a wand, and hit the wall instead, you'll typically hurt yourself with it.

I don't think it makes sense to introduce artificial difficulty through a difficult-to-use interface that makes it easy to shoot yourself in the foot.

A few possible improvements:

One possibility would be to say that you can always hit anything you have line-of-sight to.  At a minimum, if it's possible to hit an enemy at all, targeting that enemy directly should work, rather than aiming for a point past them.

Alternatively, if it remains possible to see something but not hit it, then if you attempt to throw something at a location, or fire a wand at a location, and your shot won't actually hit that location, don't do it; instead, produce a message "You can't hit (that location | the $enemy) from here.".  To hit a spot, you should actually aim at that spot, and if you can't hit it, the game should prevent you from trying.

Related to that, you should only be able to target yourself if you touch the actual square you're on.  And doing so should produce a warning message, similar to the one for attempting to throw a beneficial potion.

Finally, you might consider adding a "targeting" mode when aiming a weapon or wand, which dims squares you can't hit and puts a targeting reticle over enemies.

**Comment by 00-Evan** [comment] 2015-01-25 23:31
This is something I would like to address in some form or another, but I am unsure how difficult making it work correctly would be, both from a technical and design perspective.

I planned on investigating this during development of either the wand or thrown weapons rework, when it is relevant. Going to defer this for now, but I'm leaving it open as a reminder.

**Comment by squigish** [comment] 2015-01-29 02:20
I'd like to work on this. I have some time now, and will put some thought into how to improve it. It's something that has been bothering me as well.

**Comment by 00-Evan** [comment] 2015-03-25 17:34
I'm currently investigating this system as part of the 0.3.0 wand rework, will come with an answer regarding this inconsistency during the development of that update.

Note that an answer may involve tweaking one to be like the other, or leaving them unchanged, if there is reason for it.

**Comment by 00-Evan** [comment] 2015-06-09 15:36
So this is a little annoying.

it is possible to target every tile you can see, but the means of actually getting to it is unintuitive in most cases. Due to how the game will map your input location to a line of tiles, often times picking the right tile to target means firing significantly behind and slightly to the side of an enemy. In this sense vision and targeting are already consistent, but it doesn't really feel like it in many cases.

Probably the easiest way to deal with this is if the player specifically targets an enemy, the game automatically figures out which cell to 'actually' target in order to hit them. There may be edge cases where this creates unintended or unintuitive behaviour though, as the line to your target may actually be a line to somewhere behind them that collides with them.

**Comment by 00-Evan** [comment] 2015-07-15 13:30
Good news!

So I'm working on some changes that make the quickslot auto-target more intuitive and frequently used, part of the benefit of this is that it creates a clear place to try and handle some of this awkwardness. I'm going to try programming in a little bit of logic such that when quickslot auto-targeting is used, the game will be okay with trying out neighbouring cells to the location of your target in order to find a 'correct' path to the target, even if that means aiming a bit behind them.

Assuming this works as intended, it should massively reduce this as an issue without having to tear up the existing ballistica and targeting code.

**Comment by 00-Evan** [comment] 2015-07-17 18:43
This has been fixed indev.

The additional quickslot auto-target functionality has been implemented and allows the player to land awkward shots much more often. There are still some edge cases where the new auto-target won't connect a shot but these are pretty rare. You should actually be surprised at the number of ways you can hit enemies now.

Ticket will be closed and commit referenced once 0.3.1 source is released.

**Comment by joshtriplett** [comment] 2015-07-17 18:50
You mentioned quickslot auto-target; does this also apply if you select a ranged weapon from your inventory and target that?

**Comment by 00-Evan** [comment] 2015-07-17 18:53
Not presently, though I could look into that being implemented. Next update will have 4 quickslots anyway, so targeted effects will come from quickslots far more often.

**Comment by joshtriplett** [comment] 2015-07-17 19:13
I understand that, and that's extremely convenient, but it seems highly unintuitive for targeting behavior to differ based on whether you select an item from a quickslot or not.

**Comment by 00-Evan** [comment] 2015-07-18 23:12
I agree, but that's not quite how it works. 

Standard pressing of a tile isn't affected by this, whether from quickslots or inventory, but if you use auto-targeting (double tapping on the slot to let the game target an enemy for you, if one is available) is what this would be changed. It still does what it already did (target an enemy for you), its just that now the auto targeting will also compensate for awkward angles for you.

**Comment by joshtriplett** [comment] 2015-07-19 18:50
Oh. I don't typically use that auto-targeting, because I usually care which enemy I target, so I touch the quickslot and then the enemy.

Would it be excessively difficult to apply the same "find a way to target" logic to when you tap an enemy?

**Comment by 00-Evan** [comment] 2015-07-19 18:57
It hits up against the initial problem of not wanting to target a cell separate from the one the player actually presses. The auto-target conveniently works around that by making it obvious your targeting an enemy and not a cell. Part of 0.3.1 is going to be a tweak to auto-targeting to have it always immediately target a lone enemy if one exists, which should make it a much more common thing for people to use.

I'm running a beta for these changes btw (the more accurate auto-target is going to be in the next beta cycle tonight or tommorow), you can get more info about that here: https://www.reddit.com/r/PixelDungeon/comments/3dchy0/shattered_pixel_dungeon_beta_ui_improvements/

**Comment by joshtriplett** [comment] 2015-07-19 19:09
The problem is that if there are multiple enemies on the screen, you almost always care which one you target: the closer one, the one with ranged attacks to return fire with, the one closer to being dead...

So auto-target seems unlikely to be a good option *unless* there is only one enemy.

It's fairly uncommon to want to target a cell; even less so now if you don't need to do so to bend around a corner.  The only real remaining reason to do so is to "drop" something a distance away, such as holding open a door with an object.

So with that in mind, what if you just separated the concept of "toss" from "fire at", and made them two separate commands, with the former attached to anything you can drop and the latter only attached to throwable weapons?  The former lets you pick a cell, and you always throw it at that cell.  The latter lets you pick an enemy, and it always acts like auto-target.

**Comment by 00-Evan** [comment] 2015-07-21 14:27
In the case of multiple enemies you can still directly target from the quickslot, that is unchanged. We're now discussing the extremely rare case where you both have multiple enemies and one or more of those enemies are at an odd position to target manually.

Separating throwing functionality into two options adds unnecessary complexity to the game's interface, especially given that you would need to communicate to the player how these functions differ.

**Comment by joshtriplett** [comment] 2015-07-22 18:20
I'll definitely try them as soon as I update on my phone.

The multiple-enemy case comes up fairly often, though; for instance, it comes up every time I try to clear a piranha room via ranged weapons or wands, or use ranged weapons or wands on the dwarven halls levels (due to the fire-immune fireballs and the ranged attackers).

**Comment by 00-Evan** [comment] 2015-08-14 15:16
Though I don't like assuming the intention of the player, consistency is important too.

PD v1.9.0 has quickslot auto-targeting which picks the nearest enemy in multiple-enemy scenarios, so the Shattered auto-target will do the same.

**Comment by 00-Evan** [comment] 2015-08-24 22:48
source is now released.

Relevant commits (first to last, key changes in Hero.java and QuickslotButton.java):
3cd86934bd74508f0ac58562df51781851a7c66f
d99e206b0e97f7b4b965531182a79f00138b9954
d7e849b3abe435de16af8aa0bb1f9518068ac106
0416e7f16741628864aa920a00a04eb7c0ea247f
e853c8c6abb00a17760246ee3df7ed505dcb7170

**Closed by 00-Evan** 2015-08-24 22:48 UTC
Labels: Fixed In Beta, Quirk
