### ISSUE TITLE
Game crashing while moving between floors. 

### ISSUE THREAD

**Issue by psydvl** [00-Evan/shattered-pixel-dungeon#470] opened 2020-08-17 21:17 UTC
Face this only on 0.8.2 (not 0.8.2a) saving loaded with current 0.8.2a
![Screenshot_20200818-001149](https://user-images.githubusercontent.com/43755002/90445000-9af47280-e0e7-11ea-95e8-3586e04b3caa.jpg)
Game version 0.8.2a, saving files from 0.8.2
Android 9
Oneplus 5

**Comment by 00-Evan** [comment] 2020-08-17 21:19
duplicate of #462

**Closed by 00-Evan** 2020-08-17 21:19 UTC
