### ISSUE TITLE
Examining things doesn't update the journal

### ISSUE THREAD

**Issue by bluestmango** [00-Evan/shattered-pixel-dungeon#1804] opened 2024-09-03 20:46 UTC
Traps and plants aren't added to the journal upon examination, and instead have to be triggered before the journal is updated. (This applies to everything, but those are the two that explicitly mention examining)

**Comment by 00-Evan** [comment] 2024-09-03 21:17
Duplicate of #1795

**Closed by 00-Evan** 2024-09-03 21:17 UTC
