### ISSUE TITLE
equipping invisibility cloak ends invisibility

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#916] opened 2022-03-04 06:25 UTC
It seems like issue #719 has returned.
I have the light cloak talent. I'm invisible but the cloak is not equipped. Equipping invisibility cloak ends invisibility but it feels like that shouldn't happen.

**Comment by 00-Evan** [comment] 2022-03-04 16:52
I'm not able to reproduce this. Equipped and unequipping the clock while invisible does not break invisibility for me. Can you give me any other information such as which slot the cloak is equipped to?

**Comment by protective1** [comment] 2022-03-04 21:52
I have light cloak talent level 1.  I have the cloak in my pack but not equipped.  I use the quickslot to turn on invisibility.  I equip the cloak in place of the talisman. This causes me to become visible.   I also have three challenges on - hostile champions, badder bosses, and swarm intelligence. I hope that helps narrow it down.
![Screenshot_20220304-161948](https://user-images.githubusercontent.com/8593007/156845637-0daff273-7245-4762-80c9-82d2dbaf8f38.png)
![Screenshot_20220304-164005](https://user-images.githubusercontent.com/8593007/156845640-544b52e8-6bc9-4c88-be2b-6e079d945642.png)
![Screenshot_20220304-164021](https://user-images.githubusercontent.com/8593007/156845641-39ce60a0-d991-4b2d-abf6-ddf87a93745d.png)
![Screenshot_20220304-164036](https://user-images.githubusercontent.com/8593007/156845644-7871f52a-bca2-44b4-89bc-39530e177d40.png)
![Screenshot_20220304-164050](https://user-images.githubusercontent.com/8593007/156845649-d9b5373f-8b59-4713-9df4-736466b13cba.png)
![Screenshot_20220304-164103](https://user-images.githubusercontent.com/8593007/156845651-4c4b074c-30a0-42a1-99dd-fea06280a571.png)
![Screenshot_20220304-164522](https://user-images.githubusercontent.com/8593007/156846159-2ad51c9b-18d7-4b2f-9622-853b0f61bd47.png)

**Comment by protective1** [comment] 2022-03-04 22:00
And to show my game seed:
![Screenshot_20220304-165733](https://user-images.githubusercontent.com/8593007/156847472-31443830-6ce5-4419-bab6-ee4548c86440.png)

Another weird thing with this run is that I either can't find one of the strength potions (even though I believe I've used the talisman everywhere) or perhaps I destroyed a potion accidentally.  But that's a different issue.

**Comment by protective1** [comment] 2022-03-04 22:22
(somehow the missing strength potion appeared in my inventory even though I don't remember finding it)

**Comment by 00-Evan** [comment] 2022-03-06 16:40
Looks like it's caused by the swapping logic when you already have two artifacts (or an artifact and two rings) equipped.

**Comment by 00-Evan** [comment] 2022-03-23 16:27
fixed in commit 154d9256f4038faf96e8ea14d3857188cd7b65c7

**Closed by 00-Evan** 2022-03-23 16:27 UTC
Labels: Quirk, Fixed in BETA
