### ISSUE TITLE
The hero keeps running once hurt by unknown enemy from the undiscovered area

### ISSUE THREAD

**Issue by LyraLover228** [00-Evan/shattered-pixel-dungeon#308] opened 2019-05-10 13:17 UTC
It happened to me when I was on the night floor. I stepped into the darkened room and the shaman gnoll attacked me from undiscovered area three times, causing the hero to die. Hero kept going after being hurt, which may be a bug.

**Comment by LyraLover228** [comment] 2019-05-10 13:29
I've just read the pathing quirks issue and I recall I wasn't prompted to continue moving with the arrow button. I could have pressed it before entering the room, though.

**Comment by 00-Evan** [comment] 2019-05-10 17:02
This happens because the player pressed 'continue moving' previously. The button means the hero will continue walking even if something is causing them damage. I may adjust this functionality at some point in the future but for now I'd say this is a duplicate of #186

**Closed by 00-Evan** 2019-05-10 17:02 UTC
