### ISSUE TITLE
Stone of Intuition not being preserved

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#875] opened 2021-12-01 06:35 UTC
The same thing as #861, the stone is not being preserved after guessing correctly the first time. Although I have some info.
This seems to happen when you finish a run without using the second guess.

I guessed my last unidentified potion correctly, the stone was preserved. I won that game without using the second guess and started a new one. Once I got a stone of intuition and guessed correctly it didn't got preserved even when it was the first use.

**Comment by 00-Evan** [comment] 2021-12-01 18:37
Hmm, that shouldn't happen as the state is stored with the hero as a buff, not on something that would persist between runs. Will run some tests with that though.

**Comment by 00-Evan** [comment] 2021-12-03 17:07
I'm still not able to reproduce this. Using a stone correctly once preserves it regardless of how many runs are started/ended, or if games are switched between.

The only way one run would affect another like this is if the curUser variable wasn't correctly being set when the stone of intution is used, but it is being correctly set to the current hero when the stone is activated (same as with any other item).

**Comment by ShinKeyKai** [comment] 2021-12-03 19:30
How strange. After I submitted this issue it happened again but instead of winning I died and then started a new game. But now I'm trying to replicate it and it doesn't happen. The stone is preserved correctly.

**Comment by 00-Evan** [comment] 2021-12-10 22:03
Sorry but I'm closing this for now. I've tested this a fair bit and atm I can't see any way for stones of intuition to be lost on the first correct guess. Feel free to comment if you get reproduction steps for this or similar and I'll reopen.

**Closed by 00-Evan** 2021-12-10 22:03 UTC
