### ISSUE TITLE
Accessability: Some parts cannot be used with keyboard alone

### ISSUE THREAD

**Issue by gitter-me** [00-Evan/shattered-pixel-dungeon#923] opened 2022-03-19 08:41 UTC
This is a broad, general feature request.
I have a friend with limited physical abilities using a mouse, but she can use a PC fairly well controlling it via the keyboard. To enter a game you have to use a mouse to click "enter the dungeon" and then click to select a hero.
The same goes for almost all windows like inventory, no way tab and move focus here. Or the buttons on confirm dialogs (closing with escape works).

I know this a huge request, but perhaps you could keep it in mind and add some steps over time.

**Comment by 00-Evan** [comment] 2022-03-19 15:31
Duplicate of #351. I do plan on improving this though. I'll likely be making a comment in #351 with a status update once v1.2.0 releases.

**Closed by 00-Evan** 2022-03-19 15:31 UTC
