### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Svetov1d** [00-Evan/shattered-pixel-dungeon#1446] opened 2023-07-22 20:38 UTC
Device Info:
Redmi Note 9 (merlinnfc)
ArrowOS Vanilla 13.0
Android 13
Unlocked Bootloader
Rooted with Magisk 26.1 (hidden with zygisk)

Shattered Pixel Dungeon 2.1.4

When i start the game game crashes sometimes after few moments, sometimes it takes longer but keeps happening.
Tried clearing cache, completely deleted game and installed again, even factory reset my device (had some problemy with my banking app so I had to do it anyway).

**Comment by 00-Evan** [comment] 2023-07-22 21:10
There isn't really much I can do about this without a stack trace. I would suspect that it's caused by your custom ROM though. Do you have any custom security settings enabled, such as denying apps permission to write to their internal storage?

**Comment by Svetov1d** [comment] 2023-07-23 17:15
> There isn't really much I can do about this without a stack trace. I would suspect that it's caused by your custom ROM though. Do you have any custom security settings enabled, such as denying apps permission to write to their internal storage?

Nope, i granted SPD every possible permission and it's still happening.

**Comment by 00-Evan** [comment] 2023-08-06 14:46
Closing this due to lack of reply.

**Closed by 00-Evan** 2023-08-06 14:46 UTC
