### ISSUE TITLE
Hero doesn't look invisible after going downstairs

### ISSUE THREAD

**Issue by nyuszika7h** [00-Evan/shattered-pixel-dungeon#41] opened 2015-03-30 14:42 UTC
The buff was still there for one more round, though.

[![Screenshot](https://i.imgur.com/CyRbEJNl.jpg)](https://i.imgur.com/CyRbEJN.jpg)

**Comment by 00-Evan** [comment] 2015-03-30 17:29
This is a side effect of a change I made recently to prevent crash issues with loading games.

It's all caused by the way the game currently loads the hero, which makes doing things like specifying sprite changes on load very tricky. I plan to overhaul the way the hero is loaded at a later point, which will completely fix this, but in the meantime I'll look into a more temporary fix.

**Comment by 00-Evan** [comment] 2015-04-30 16:40
This has been fixed indev, will close this ticket with a commit reference once the source for 0.3.0 is available.

**Comment by 00-Evan** [comment] 2015-06-08 03:25
fixed in 0.3.0c source release

**Closed by 00-Evan** 2015-06-08 03:25 UTC
Labels: Fixed Indev, Quirk
