### ISSUE TITLE
Thieves "running away with item" in visual range

### ISSUE THREAD

**Issue by gASK13** [00-Evan/shattered-pixel-dungeon#292] opened 2019-03-05 13:01 UTC
I recently ran into this issue and managed to reproduce it for a total of three (annoying) times.

Location: Dark Prison level

- A thief stole an item and started running away. I zapped him with a wand, he ran three tiles from me in the same room (there were two empty tiles between us), I could still see him - however the "The thief gets away with your ..." message pops up anyway, I kill the thief on the same turn using my wand, get nothing back.
- A thief stole an item, started running away, had a one-tile-space headstart, ran through door, meaning I lost sight of him for a turn. Immidiately the "The thief gets away with your ..." message pops up, I kill the thief in the corridor behind the door, get nothing back
-A thief stole an item, started running away, got a two tile headstart, managed to run around a corner where I could still see him - once again, the "The thief gets away with your ...." message pops up. I did not catch up to him this time, but I guess the item was once again gone.

While I really like the "run away" feature that forces you to make tough decisions, I believe some small tweak would help to avoid these infuriating situations where you can see the thief or when you just lose him around corner or behind door and catch up to him immediately and your item is magically gone.

I would suggest either checking certain minimum straight distance from player or adding a minimum time limit after which the "run away" feature is triggered (or both).

Or alternatively add a well hidden secret prison "stash" room where the thieves run away with your stuff so you can get it back (if you search hard enough for it).

**Comment by 00-Evan** [comment] 2019-03-07 01:26
Hey, so firstly here's how that mechanic works: 
If a thief meets the following conditions when running, they get away:
- they cannot see the hero
- they are outside of the hero's FOV
- a random roll between 0 and distance (ignoring walls) from the hero is greater than 6

This seems to contradict what you've run into, as thieve's definitely can't get away when you can see them, or when they're just a couple tiles away. I just tested it to be sure and that seems to be working correctly. Aside from the obvious reduction in player visibility a dark floor shouldn't directly affect this logic either.

**Comment by gASK13** [comment] 2019-03-07 08:30
Thanks for looking into this!

I understand it is hard to verify this based on just my vague description and that the algorithm is supposed to be what you described, byt my experience differed from the description so one of the conditions must have been evaluated incorrectly or something else must have come to play.

Unfortunately I did not realize this was a bug until after I googled a bit about the thief behavior - I just thought it was a special "thief lair level" or something since I met like a dozen of them there and they were all very good at stealing my stuff.

I will be paying close attention to thieves from now on and if this happens to me again I will add a screenshot or something to help identify what might have happened.  But hopefully this will never ever happen to me again 👍

**Comment by 00-Evan** [comment] 2019-03-14 23:05
An update regarding this, I think I know what may be causing this. Essentially the minimum range is being checked in one part of the logic but not another. Hopeful fix for this will be released with 0.7.2 in a few days.

**Comment by gASK13** [comment] 2019-03-15 08:12
Thanks for the update & incoming fix! It did not happen to me ever since, so I probably got really unlucky RNG roll on that one,

**Comment by spixi** [comment] 2019-03-15 21:34
Also note, when you playing Huntress, there may be situations where you can see the thief, but the thief cannot see you. The thief can "run away", even if you see him. This is intended behaviour, though.

**Comment by 00-Evan** [comment] 2019-03-21 05:18
fixed (hopefully) in commit https://github.com/00-Evan/shattered-pixel-dungeon/commit/11ae9263413fd4c0584036ca3015fecb892d834d#diff-4e36dc646b81eab1b97ea6f5cd8ee5ea

**Closed by 00-Evan** 2019-03-21 05:18 UTC
Labels: Fixed Indev, Minor
