### ISSUE TITLE
Floating meat 🍖 

### ISSUE THREAD

**Issue by samcoupland** [00-Evan/shattered-pixel-dungeon#1468] opened 2023-08-24 20:04 UTC
Bug - floating items when picked up

Description:
When picking up an item with full inventory and a thrown weapon underneath, the object will start to drift up if pick up item/button has been continuly pressed

Visuals:
https://youtu.be/p-nea2UX0PE?feature=shared

Replication:
- Choose Huntress then Sniper (only character and class I have tried this with)
- Have full inventory
- drop ththrowing item
- drop another non-throwing item on top
- atempt to continuly pick up the item

Expected result:
When picked up item will jump a little up and land back in place every time clicked.

Actual result:
Item continues to travel up the screen when clicking multiple times, only reseting to the orginal place if sufficient time has passed for the animation to complete.

**Comment by TheYsconator** [comment] 2023-08-24 20:13
This is known and intended. Check out #689, #1150, #1355 and #1436 (and probably others as well).

It's always good to report bugs, but don't forget to first check if it hasn't been reported yet. ;-)

**Comment by 00-Evan** [comment] 2023-08-24 20:47
Thanks for the report, but as mentioned, this is a duplicate of prior issues.

**Closed by 00-Evan** 2023-08-24 20:47 UTC
