### ISSUE TITLE
Bug: when moving to a new square, the hero runs from another place

### ISSUE THREAD

**Issue by brunal** [00-Evan/shattered-pixel-dungeon#162] opened 2017-03-13 20:51 UTC
Instead of moving from where the hero is, he appears to run from another place on the screen to the designated target. That movement is uninterruptible. It also ignores the level (walls, fogs, mobs, traps, ...).
- it happens randomly
- it can happen zero to several times in a run
- I have seen a mob be affected by the bug
- I have had my boomerang appear briefly in another place than intended on throwing (hit still where expected).

The nature of the bug makes it hard to pinpoint. However,
- I play on Android. Could there be a link to battery status?
- It could be a graphical glitch, and not a logic one in pathing-related code.

I believe that bug has been mentioned on the subreddit and the IRC channel, but it could be good to has a long-standing placer to report, discuss and investigate it.

**Comment by 00-Evan** [comment] 2017-03-13 22:20
This has been an issue I have repeatedly had reported with no consistency or means to reproduce it.

I 'think' I know what's causing it, but I've never had an opportunity to properly test a fix. I'm planning on implementing this fix into 0.6.0 anyway and hopefully that will put this to rest.

Shattered currently performs all time-based calculations (including animation time) based on the system time. The problem with this is that it's sensitive to time synchronization. If you have a device with a system clock that's say, 0.1% fast, then roughly every 15 minutes the game would suddenly jump one second backwards in any animations it is currently performing.

In 0.6.0 I'm going to change this to be based on time since boot instead, which I don't believe is sensitive to any sync changes. Shattered's animation times would still be affected by an inaccurate system clock, but this would be unnoticeable unless it is grossly inaccurate, something like 5% or more.

If you're experiencing this issue frequently and are willing to download a custom APK to test, i'd be happy to send you one.

**Comment by brunal** [comment] 2017-03-14 12:35
I can definitely test a custom APK. I could also build from source.

**Comment by 00-Evan** [comment] 2017-03-14 17:08
APK Here: https://drive.google.com/open?id=0B1jhmo3hgqJtNnVDMS1NdF9jYW8

It is identical to v0.5.0b on google play, with the exception that this one fix has been made.

If you'd prefer to compile this yourself, simply replace this line: https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/SPD-classes/src/main/java/com/watabou/noosa/Game.java#L226
with:
 `long rightNow = SystemClock.elapsedRealtime();`

**Comment by brunal** [comment] 2017-03-14 23:40
By reading the doc at https://developer.android.com/reference/android/os/SystemClock.html I wonder if the correct function would be uptimeMillis(), so animations work as expected around deep sleep. I'm not sure it matter though.

I've played a bit witht the modified APK and the bug hasn't appeared so far.
How would I build from source? There's no Makefile for a "make apk"...

**Comment by 00-Evan** [comment] 2017-03-15 00:54
The game already prevents this by resetting the 'now' variable whenever the app resumes, the change in elapsed time in the first drawn frame is ignored, and then all time-based physics resume in subsequent frames.

Shattered uses the standard android studio project format, so the most convenient way to build is to use android studio. Otherwise you can invoke gradle from the command line. Regardless If you already have the play store version installed it's better to take an APK from me as that's the only way to make sure the build is signed with the same key as the play store version.

**Comment by 00-Evan** [comment] 2017-03-15 02:20
I'm going to tentatively label this as fixed indev, let me know if you run into it again with that fixed APK,

**Comment by brunal** [comment] 2017-03-15 18:46
Doesn't this mean by simply uptimeMillis() you could drop all that logic around deep sleep? Or they would still be gaps (e'g' does it still jump if time isn't spent in deep sleep but in another app?)?
One reason behind building an APK myself would be to introduce deliberate setbacks around time measurement to confirm it produces the bug :-)

**Comment by 00-Evan** [comment] 2017-03-15 19:07
Keep in mind that deep sleep is not the same thing as the app losing focus. The current logic is far better as it catches all circumstances that result in the app pausing, not just deep sleep. e.g. someone switching to a messaging app, then switching back, would not be caught by uptimeMillis().

I did actually put in some custom time silliness to reproduce initially, and it definitely causes the bug as described, but just because this can cause the bug doesn't mean it's the only thing that does.

**Comment by brunal** [comment] 2017-03-16 10:19
Sounds very good! I played on low battery and the games behaves incredibly better. Congrats, well played and thanks!

**Comment by 00-Evan** [comment] 2017-06-07 03:00
fixed in commit 2f18c7146befb22b23ce3ffddff5e6da33c810ea

**Closed by 00-Evan** 2017-06-07 03:00 UTC
Labels: Fixed Indev, Quirk
