### ISSUE TITLE
Visual bug where enemy drops can be seen for a frame while out of view.

### ISSUE THREAD

**Issue by Howdidibreakit** [00-Evan/shattered-pixel-dungeon#1353] opened 2023-05-17 15:29 UTC
Occasionally, if something dies while out of view, (Ex: behind a door, around a corner.) You can still see what they dropped for a split second, if they dropped anything. This happens more frequently with gnoll brutes
![image](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118551559/a8d36b0a-ad93-46b0-bc74-2e1f3a27b039)
It just happened right here, just behind the door.

**Comment by Howdidibreakit** [comment] 2023-05-17 15:35
![image](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118551559/1d85ea42-0440-47d8-9ac8-7ed4a3736639)
Sidenote, this deducts point for being "avoidable" It's not, not in any way avoidable.

**Comment by 00-Evan** [comment] 2023-05-18 03:31
I can reproduce the enemy drops bug. The second report is intended, you are standing next to walls, which means you risk the safe adjacent tile being unreachable.

**Comment by 00-Evan** [comment] 2023-06-02 15:19
Fixed in commit: 0bbd63be30accbea18860b96caed88444614c5b5

**Closed by 00-Evan** 2023-06-02 15:19 UTC
Labels: Quirk, Fixed in BETA
