### ISSUE TITLE
Headset button doesn't work

### ISSUE THREAD

**Issue by Cysioland** [00-Evan/shattered-pixel-dungeon#62] opened 2015-09-05 14:45 UTC
**Device:** Sony Xperia Z2

**Android version:** 5.1.1

**Headset button utilizing app:** Spotify

Headset button doesn't work when I'm in your app. In other apps it works fine.

**Comment by 00-Evan** [comment] 2015-09-05 23:40
Does this happen for you in the original pixel dungeon as well?

**Comment by 00-Evan** [comment] 2015-09-09 22:01
You're going to have to work with me on this as I am not able to reproduce the issue (no spotify account). Will close this ticket as won't fix if no response.

**Comment by Cysioland** [comment] 2015-09-09 23:18
I'll work with you on this.

**Comment by 00-Evan** [comment] 2015-09-11 15:18
Could you please let me know if this also happens for you in the original pixel dungeon game.

**Comment by Cysioland** [comment] 2015-09-14 13:33
It also happens in the regular Pixel Dungeon. As soon as I press Home soft
button, the play/pause works as usual.

**Comment by 00-Evan** [comment] 2015-09-24 20:19
Please be more descriptive in future, was not clear that you meant the physical headset play/pause button, I assumed there was some form of button provided by the spotify app.

This does not seem to be a spotify specific issue, occurs on any audio stream, will investigate and see if a fix is feasible.

**Comment by Cysioland** [comment] 2015-09-24 20:22
I told about headset button, but if it was ambiguous, then I'm sorry…
not sorry. If you had any problem with understanding my wording, you
could simply ask. I don't bite.

**Comment by 00-Evan** [comment] 2015-09-24 20:27
No worries, it just means it takes more time on my end to investigate. Regardless, I'll keep the status of a fix updated here, but assuming it's fixable (should be) fix will be in the next update.

**Comment by 00-Evan** [comment] 2015-10-01 17:04
This issue has been fixed in the latest beta for shattered. The fix will be released publicly as part of 0.3.2

You can opt-in to receive betas from google play here: https://play.google.com/apps/testing/com.shatteredpixel.shatteredpixeldungeon

This ticket will be closed with the commit referenced when the source for 0.3.2 is released

**Comment by Cysioland** [comment] 2015-10-01 17:05
I'm using F-Droid, will it be there?

**Comment by 00-Evan** [comment] 2015-10-01 17:06
F-Droid will get the latest update when the source is released, which is usually a few days after the google play release, depending on how many bugs I need to squish.

**Comment by Cysioland** [comment] 2015-10-01 17:09
Meh, open sourcers always have it hard.

**Comment by 00-Evan** [comment] 2015-11-08 22:08
Source for 0.3.2b has been released.

This was fixed in the following commit: https://github.com/00-Evan/PD-classes/commit/06f79e4a202653be715503604c7d5bbecdcd850b

**Closed by 00-Evan** 2015-11-08 22:08 UTC
Labels: Fixed Indev, Minor
