### ISSUE TITLE
Launching desktop version results in [LWJGL] GLFW_API_UNAVAILABLE error

### ISSUE THREAD

**Issue by cheshyrex** [00-Evan/shattered-pixel-dungeon#397] opened 2020-05-13 01:09 UTC
This is the first time I tried running SPD on my computer, and it simply errors out when I try to launch it:
* **OS:** Microsoft Windows [Version 10.0.18362.778]
* **Java -version:**
  * openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

**`>java -jar ShatteredPD-v0.8.0b-Desktop.jar`**
```
[LWJGL] GLFW_API_UNAVAILABLE error
        Description : WGL: The driver does not appear to support OpenGL
        Stacktrace  :
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1666)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1847)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:450)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:394)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:380)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:108)
                com.shatteredpixel.shatteredpixeldungeon.desktop.DesktopLauncher.main(DesktopLauncher.java:140)
[GAME] com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:453)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:394)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:380)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:108)
        at com.shatteredpixel.shatteredpixeldungeon.desktop.DesktopLauncher.main(DesktopLauncher.java:140)

AL lib: (EE) alc_cleanup: 1 device not closed
```
I tried downloading the previous version, and got a different message:

**`>java -jar ShatteredPD-v0.7.5f-Desktop.jar`**
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/C:/Users/Lis/Downloads/ShatteredPD-v0.7.5f-Desktop.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: OpenGL is not supported by the video driver.
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:356)
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:250)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:146)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
Caused by: org.lwjgl.LWJGLException: Pixel format not accelerated
        at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
        at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
        at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
        at org.lwjgl.opengl.Display.createWindow(Display.java:306)
        at org.lwjgl.opengl.Display.create(Display.java:848)
        at org.lwjgl.opengl.Display.create(Display.java:757)
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:348)
        ... 3 more
```
It's entirely possible that my configuration is the issue, and if OpenJDK isn't supported, that's fine.
But I wanted to let you know. If you have any questions about my system, I'll help in any way I can.

**Comment by 00-Evan** [comment] 2020-05-13 01:17
This is the important bit: `WGL: The driver does not appear to support OpenGL`

For some reason your computer is not reporting that it supports OpenGL 2.0+, which causes the game to immediately crash as that's a requirement. This is likely caused by outdated or incorrectly configured graphics drivers. It is also possible your computer doesn't support OpenGL 2.0, but that's very unlikely these days.

I'm closing this as it's not an issue with the game, but feel free to reply if you'd like more help with this.

**Closed by 00-Evan** 2020-05-13 01:17 UTC

**Comment by cheshyrex** [comment] 2020-05-13 23:17
All set now, thanks (I had been running thru a Remote Desktop connection; it's running fine on the PC itself)
BTW, are you open to enhancement suggestions, and if so, where should I submit them?
I see some in this issue list, but I wasn't sure if you'd rather reserve this site for actual defects.

**Comment by 00-Evan** [comment] 2020-05-13 23:22
If the enhancement is technical in nature it could fit here, if it's more design-related you should email me: Evan@ShatteredPixel.com
