### ISSUE TITLE
Watabou's website in "About"

### ISSUE THREAD

**Issue by naviact** [00-Evan/shattered-pixel-dungeon#387] opened 2020-04-21 03:48 UTC
The link to watabou's website on the "About" page in the app (https://pixeldungeon.watabou.ru/) is broken. I think his new page is https://watabou.itch.io/pixel-dungeon

**Comment by 00-Evan** [comment] 2020-04-21 04:16
pixeldungeon.watabou.ru is the main website for the game (vanilla PD also links to it), but it appears to be having an issue with HTTPS at the moment. I'll leave this open for now in case the HTTPS error is persistent, but I expect the site will be accessible again soon.

**Comment by 00-Evan** [comment] 2020-04-27 17:50
Looks like the issue is somewhat persistent. I'll switch to HTTP instead of HTTPS in 0.8.0a

**Comment by 00-Evan** [comment] 2020-04-28 18:56
fixed in commit 00eca29f3cbedaf0e316fc3e9abb61280d913ee5

**Closed by 00-Evan** 2020-04-28 18:56 UTC
Labels: Fixed Indev, Minor
