### ISSUE TITLE
Adventurers handbook readable before picking up

### ISSUE THREAD

**Issue by Krediman** [00-Evan/shattered-pixel-dungeon#932] opened 2022-03-23 00:04 UTC
As of 1.2.0 RC1 (or whatever I get downloading this file: https://github.com/00-Evan/shattered-pixel-dungeon/releases/download/1.2.0-beta/ShatteredPD-v1.2.0-RC-1-Android.apk (see #931))
I can read the first 6 chapters of the adventurers Handbook while it is still lying on the dungeon floor.

**Comment by 00-Evan** [comment] 2022-03-23 00:16
duplicate of #931

**Closed by 00-Evan** 2022-03-23 00:16 UTC
