### ISSUE TITLE
Temporary Telegraphs

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1152] opened 2022-11-10 01:29 UTC
Ripper demons & Yog-Dzewa telegraph their attacks briefly using red reticles. This is problematic for several reasons.

Every other telegraphed attack in the game is displayed permanently until the attack is made (e.g., Goo's burst, Tengu's poison dart traps & fire walls, DM-300's rockfalls). W/ Yog & its demons, glancing away from the screen @ the wrong time can make it so you miss seeing where the attacks are happening. Changing the position of the camera in the turn prior to the telegraphs can have the same result. In some cases, dropped frames because of hardware issues or background processes end up costing you this info. This seems contrary to the spirit of a turn-based game like SPD & feels like a dexterity-based mechanic in a game that prob shouldn't have those.

On top of this, the demon halls feature a lot of reddish colors as part of their terrain palette. There is an accessibility issue here for people who have color blindness because they may need more time to perceive the reticles before they pulse away. This can become an even more pronounced issue during the Yog fight where blobs can obscure the reticles. It seems the reticles occupy a low lvl in the display hierarchy, just above the dungeon floor. This makes it so the red marks can be hard to see even for people w/ full color perception when they only appear for a second beneath multiple area effects like toxic clouds & burning fire, & above the orange background of faux lava.

This is a feature request to make these indicators more permanent & perhaps more visible. In the case of ripper demons, those reticles should pulse continuously until the attack is made instead of once & only briefly. It would also be nice to have some indication of which demon is making which attack in the case of multiple demons leaping @ you.

In the case of Yog's lasers, I suggest reworking the telegraph. There is already a directionally-sensitive particle asset in the form of DM-300's electrically charged pools. I'd like to see that palette-shifted to match the laser's colors & applied instead of the reticles we have now. This would increase the visibility of the effect as well as look much cooler; it would be like the focusing energy of the attack is reflecting off motes of ash & dust in the air while simultaneously pushing them away. In line w/ what I've said previously & how the game typically handles this info, the telegraph should remain until the attack is made.

**Comment by Pr0methean** [comment] 2022-11-10 05:39
The best accessible color for the reticle is probably white or blue. Red-blue color blindness is much rarer than red-green.

**Comment by 00-Evan** [comment] 2022-11-10 14:34
Duplicate of #451. To re-iterate on that:

The current system arises out of not having a clear danger indicator that would fit thematically with the beam or ripper jump, so a more generic one was chosen. It doesn't persist forever to avoid excessive visual clutter.

Your point about them being a "dexterity-based mechanic" is a huge exaggeration though, the indicators persist for two whole sections, much longer than a brief glance or framerate hitch. As mentioned before they don't last longer to avoid cluttering up the scene.

Rather than changing these things on a case-by-case basis, I would prefer to at some point come up with a more clear and universal locational damage indicator, as that would also help address other feedback points such as players sometimes not knowing the exact cells that gasses are on. This is a low priority though as it's not as easily as it would appear to be from a UI/UX perspective.

**Closed by 00-Evan** 2022-11-10 14:34 UTC

**Comment by LeahLuong** [comment] 2022-12-14 20:53
@00-Evan Pitfall trap is another example of a temporary telegraph that can only be glimpsed briefly. This should also be addressed when/if you get around to making a universal indicator.
