### ISSUE TITLE
Music breaks when the application is not in the foreground. 

### ISSUE THREAD

**Issue by flying-ph0enix** [00-Evan/shattered-pixel-dungeon#1649] opened 2024-03-22 15:59 UTC
First, I must pay my respects to the recent updates to the game. I love the mining challenge and the new soundtracks!

As for the issue that I'm experiencing, when the application is not in the foreground, the music pauses every other second resuming in between pauses, which is super annoying.

I'm using the Flatpak distribution of the game on Fedora 38.

Thanks :D

**Comment by TheShadowOfHassen** [comment] 2024-03-22 16:23
Unfortunately, the Flatpak is not officially supposed by  @00-Evan, it's maintained by the community (like me!)

Don't worry, though, I might be able to help you figure out whether the problem is flatpak or an actual Shattered Pixel Dungeon bug.

First, is your computer completely up to date? I use Pop!_OS, so I couldn't tell you how but make sure you have the latest Fedora released. Then restart your computer.

Then uninstall and reinstall Shattered Pixel Dungeon.

Does it still happen after that?

**Comment by 00-Evan** [comment] 2024-03-23 15:25
As mentioned, I don't provide support for unofficial distributions, and am not in a great position to help with Linux issues in general. I'm going to close this issue, but please feel free to discuss and hopefully find a resolution in the comments.

**Closed by 00-Evan** 2024-03-23 15:25 UTC

**Comment by TheShadowOfHassen** [comment] 2024-03-23 15:36
@00-Evan, I'll try to help with Linux/Flatpak related stuff. I know you don't accept contributions but I can try to figure out if it's a shattered pixel problem or a Linux problem, and try to help the user (or you) figure out what they need to do to fix it.

Any luck @flying-ph0enix ?

**Comment by 00-Evan** [comment] 2024-03-23 15:40
@TheShadowOfHassen Yeah I don't accept contributions directly, but well researched bug reports are obviously welcome. It's mainly that I don't want people to send me code or detailed solution descriptions, mainly due to legal reasons.

**Comment by TheShadowOfHassen** [comment] 2024-03-23 16:26
@00-Evan I understand your concern, and while I think a simple contributor contract could fix it, I can see how you'd want to be super careful.

Fortunately, you don't have to worry about me sending code or in depth solutions, I don't know Java. The only thing I could possibly contribute, is writing/editing skills, which if you want a set of informed set of eyes on your amazing lore dumps I would be willing to do it. Again, for legal reasons, I understand if you don't want to do that, but I know you've had people help with other parts of the game like music, character art, and translations, so I thought I could just offer.

Development aside, though, I'm going to haunt the repo and try to help other Linux/ Flatpak users. At the very least, I can help people figure out whether it's a problem with their platform, or if it's an actual Shattered Pixel Dungeon issue. (And I'm going to make sure the people who use Flatpak can have an up-to-date experience with this amazing game)

@flying-ph0enix I had another idea. Are you running X11 or wayland? I've had some weird problems with flatpak and X11/ Wayland and if I know which it might help me figure out what's wrong.

**Comment by flying-ph0enix** [comment] 2024-03-23 16:30
@TheShadowOfHassen thanks for reaching out!

I have updated to Fedora 39 (using Wayland) and reinstalled SPD. Unfortunately, it did not fix the issue. 

Also, is it possible that I can get involved on the flatpak distribution? I'm not familiar with coding or packaging, but I'd love to learn and start contributing where I can.

**Comment by TheShadowOfHassen** [comment] 2024-03-23 17:16
> I have updated to Fedora 39 (using Wayland) and reinstalled SPD. Unfortunately, it did not fix the issue.

Ok, could you run shattered pixel dungeon from the terminal? (flatpak run com.shatteredpixel.shatteredpixeldungeon) Copy and paste what the terminal says here.

> Also, is it possible that I can get involved on the flatpak distribution? I'm not familiar with coding or packaging, but I'd love to learn and start contributing where I can.

The flatpak repo is here: https://github.com/flathub/com.shatteredpixel.shatteredpixeldungeon

Unfortunately, there isn't much to do. Other people (smarter than me) set everything up, and all I've done is tell the repo to use the latest version of the game. All I do is open a PR whenever there's a new release. You could follow the repository and test the build whenever theirs a new version of the game.

**Comment by flying-ph0enix** [comment] 2024-03-23 19:07
> Ok, could you run shattered pixel dungeon from the terminal? (flatpak run com.shatteredpixel.shatteredpixeldungeon) Copy and paste what the terminal says here.
> 
> >

The only relevant information the terminal provides is the error below, with the rest being gameplay messages.

`[ALSOFT] (EE) Failed to connect PipeWire event context (errno: 112)`

**Comment by TheShadowOfHassen** [comment] 2024-03-23 19:44
Ok. Could you install flatseal and turn on anything related to audio?

**Comment by flying-ph0enix** [comment] 2024-03-23 20:10
> Ok. Could you install flatseal and turn on anything related to audio?



The only thing I found was the PulseAudio toggle, which is enabled by default. When it is turned off, it stops the application from play audio.

I went ahead and ran the installed .jar file, and it produced the same results as if I had run it from the flatpak. That being said, I believe the flatpak is working as desired and the “Play Music in Background” toggle within the game is at fault.

**Comment by TheShadowOfHassen** [comment] 2024-03-23 20:11
Ok. I'll try to replicate it.

**Comment by TheShadowOfHassen** [comment] 2024-03-23 20:16
I can't replicate it. Which is strange. What version of pipewire are you running?

**Comment by flying-ph0enix** [comment] 2024-03-23 21:19
> I can't replicate it. Which is strange. What version of pipewire are you running?

`$ pipewire --version
`
```
pipewire
Compiled with libpipewire 1.0.4
Linked with libpipewire 1.0.4
```

**Comment by TheShadowOfHassen** [comment] 2024-03-23 21:43
I have 1.0.3. Strange.

@00-Evan, does Shattered Pixel Dungeon use LibGDX for sound?

@flying-ph0enix could you install mindustry from Flathub(https://flathub.org/apps/com.github.Anuken.Mindustry) and see if you can replicate the problem (They both use LibGDX). Warning, like Shattered Pixel Dungeon, Mindustry is addictive.

**Comment by flying-ph0enix** [comment] 2024-03-23 22:10
> @flying-ph0enix could you install mindustry from Flathub(https://flathub.org/apps/com.github.Anuken.Mindustry) and see if you can replicate the problem (They both use LibGDX). Warning, like Shattered Pixel Dungeon, Mindustry is addictive.

Sounds like I'll have to give it a try in the near future. The opening page plays the theme both in the foreground and background without issue. While in a campaign, the game seems to pause as a whole when out of the foreground.

**Comment by TheShadowOfHassen** [comment] 2024-03-23 22:24
> Sounds like I'll have to give it a try in the near future. The opening page plays the theme both in the foreground and background without issue. While in a campaign, the game seems to pause as a whole when out of the foreground.

OK. I need to wait for @00-Evan to answer the question, but I think I have an idea.

@00-Evan LibGDX does handle sound, you also know what version of LibGDX shattered pixel dungeon uses?

**Comment by TheShadowOfHassen** [comment] 2024-03-24 02:56
Actually @flying-ph0enix I did some research and I have 2 questions 

1. Can you get this game to run (https://github.com/yairm210/Unciv)

2. Can you install super tux from your default repos and does anything happen?

I think I narrowed it down to something with your version between pipewire and/or something about gdx or Open AL. Unciv runs the same library version of gdx (and apparently mindustry does not) but if that doesn't work we know it's something between gdx and pipewire.

For a while, pop!_OS was having issues with open AL failing with a certain pipewire version, and I wonder if something similar is afoot (thus the super tux).

Let me know with what you find out!

**Comment by 00-Evan** [comment] 2024-03-24 18:35
@TheShadowOfHassen Yes Shattered uses libGDX for sound, in what I think is a pretty standard implementaiton. 
For SFX: https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/SPD-classes/src/main/java/com/watabou/noosa/audio/Sample.java
For Music: https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/SPD-classes/src/main/java/com/watabou/noosa/audio/Music.java

on desktop these should use OpenALLWJGL3Audio and OpenALMusic in libGDX.
