### ISSUE TITLE
Memory and other smaller issues

### ISSUE THREAD

**Issue by myxture** [00-Evan/shattered-pixel-dungeon#231] opened 2018-02-26 17:46 UTC
Hey Evan,

I gathered a few things which I found worth mentioning.

1. When playing for a couple of hours continuously, the amount of memory being used grows with time, which causes lagging. The memory being used can be as high as 1 Gigabyte, see attached sreenshot.
![pdmemory](https://user-images.githubusercontent.com/36456503/36684985-4a918d1a-1b22-11e8-8bc6-5fb81151389d.png)

2. In the latest update, the resume button doesn't always appear after being stopped. I don't have a complete list, but among others, starving causes this.

3. When fighting with a mimic, turns last a bit longer than usual.

4. Scrolls can't burn up when they're lying on the ground.

I'm really impressed of the work you've put in the game, and I hope this helps making it a bit better!

**Comment by 00-Evan** [comment] 2018-02-26 23:45
Thanks for the reports!

Firstly, can you tell me your device model?

1. This may be due to a memory leak, but clearly it's a slow leak. can you tell me how long your sessions with the game have been in the past few days? This will help when looking into what may be causing this.

2. This will depend on the action you were performing before being interrupted. Generally the resume indicator will only show if you are walking to an empty location or towards stairs.

3. do you mean longer in real time, or in game turns?

4. Scrolls defnitely can burn on the floor. Perhaps it was a scroll of upgrade you saw, which is immune to burning.

**Comment by myxture** [comment] 2018-02-27 11:58
My phone is a Nexus 5X running stock 8.1 ROM.

1. As for the memory leak, the game stops lagging after quitting and relaunching the app. The problem only appears when it's open for about 3 or 4 hours.

2. I'll try to gather a few specific examples.

3. In real time.

4. That's not a misbehaviour then. It was a scroll of upgrade.

**Comment by 00-Evan** [comment] 2018-02-28 03:26
Okay, so, i've been looking into this and have a probable cause for the memory issues.

It seems some changes to the android platform in 8.0 have caused the game's text system to not correctly clean up cached text bitmaps. This would cause the game's memory usage (especially GPU usage) to increase steadily over time, as cleaned up entries were not truly being cleaned. if you're willing, could you try installing a tester APK for me and letting me know if the issue is corrected for you?

**Comment by myxture** [comment] 2018-02-28 19:12
Sure, I'll do that. It will take a few days though for me to find some spare time for it :)

**Comment by 00-Evan** [comment] 2018-03-01 00:10
To be honest the text issue is almost certainly what's causing this, and is a serious bug either way. I'm going to release 0.6.3b shortly, so just let me know if that corrects things for you.

**Comment by myxture** [comment] 2018-03-03 09:17
As I see, the memory problem is fixed. Maximum usage is now capped at just a bit more than 100 MB which is a 90% decrease :)

I'd have two more notices though. The first is, when using a weapon with reach with Huntress, you are able to attack through wall. Specifically, I think of the small circular rooms with a single tile of wall in the center.
The other happened to me in only one run (but multiple times). When the hero was teleported, the discovered areas became unknown again. I had an Unstable Spellbook equipped, and a Lloyd's Beacon in my bag.

**Comment by 00-Evan** [comment] 2018-03-03 14:57
Glad to hear the memory leak is fixed! I'll mark this as resolved once the source is released and there is a commit to reference.

Both of your other mentions sound like intended functionality. The former is how the projecting enchant works on a ranged weapon, the latter is the warping trap, which was adjusted in 0.6.2.

**Comment by 00-Evan** [comment] 2018-03-10 03:52
fixed in commit c471cc6b96cd163ed1943d74f41d07a0904a8168

**Closed by 00-Evan** 2018-03-10 03:52 UTC
Labels: Fixed Indev, Major
