### ISSUE TITLE
Arcane stylus deleted armor 

### ISSUE THREAD

**Issue by mkldn** [00-Evan/shattered-pixel-dungeon#787] opened 2021-08-24 15:42 UTC
Used an arcane stylus on a +7 plate armor and the armory vanished. No message about it and it was neither in my inventory or on the ground.

Version 1.0 on Samsung Galaxy S21+ running Android 11

**Comment by 00-Evan** [comment] 2021-08-24 16:25
Arcane styli can modify the properties of an armor, but do not affect their position in the inventory in any way. There shouldn't be any way for this to occur.

Was the armor equipped, or in your inventory, and were there any other buffs or similar effects on you at the time?

**Comment by mkldn** [comment] 2021-08-24 16:33
It was equipped, after using the stylus I had no armor equipped. Only thing I had left was an older unmodified plate armor in my backpack but I had that before using the stylus as well. 

There was no trace of my original armor.

**Comment by 00-Evan** [comment] 2021-08-25 01:37
Did you have any other items in your inventory that you could have used accidentally, such as a merchant's beacon?

There simply shouldn't be any way for this to happen, and unless it's extremely specific I would be getting flooded with reports about it.

**Comment by mkldn** [comment] 2021-08-25 10:09
No merchant's beacon, I'm sure of that at least, I tend to never buy it. Don't think I had anything else that I could've used to this effect, what else could that have been?

I'm willing to accept the error was at my end but I can't really think of anything I could've done to cause it. There weren't any holes close by either that I might've tossed it down into.

**Comment by 00-Evan** [comment] 2021-08-25 16:33
I'm going to close this as there seems to be no way to reproduce the issue. Please feel free to comment if you run into it again and I'll re-open.

**Closed by 00-Evan** 2021-08-25 16:33 UTC

**Comment by mkldn** [comment] 2021-08-28 15:14
Similar issue. Had two whips, one of them not identified. Used a scroll of identify on it and it vanished. No trace of it, neither in my bag nor on the floor.
![Screenshot_20210828-171113](https://user-images.githubusercontent.com/16347928/131222591-89fae3af-01f9-4894-bf00-c2e8fa5ede66.jpg)

![Screenshot_20210828-171124](https://user-images.githubusercontent.com/16347928/131222593-ad5e5552-e031-47ce-8e53-6fff62a2dc83.jpg)

Wish I could send you some logs or something!
